PATL: uxn::patl::lca_oracle< SuffixCont > Class Template Reference
uxn::patl::lca_oracle< SuffixCont > Class Template Reference
#include <lca_oracle.hpp>
Public Types
typedef suffix_cont::vertex vertex
typedef suffix_cont::prefix prefix
Public Member Functions
const lca_type * get_by (const vertex &vtx) const
utility func
lca_type * get_by (const vertex &vtx)
utility func
vertex new_algo (const lca_type *cur) const
utility func
lca_oracle (const suffix_cont &cont)
ctor
~lca_oracle ()
void init ()
vertex operator() (vertex vx, vertex vy) const
return LCA(vx, vy)
Private Types
typedef SuffixCont suffix_cont
typedef suffix_cont::allocator_type allocator_type
typedef impl::lca_base< lca_oracle< suffix_cont > > lca_type
Private Attributes
const suffix_cont * cont_
allocator_type::template rebind< lca_type >::other lca_alloc_
lca_type * lca_
word_t lca_size_
word_t lca_root_h_
word_t * lca_map_
allocator_type::template rebind< word_t >::other unsigned_alloc_
Detailed Description
template<typename SuffixCont>
class uxn::patl::lca_oracle< SuffixCont >
Definition at line 17 of file lca_oracle.hpp.
Member Typedef Documentation
allocator_type
template<typename SuffixCont > typedef suffix_cont::allocator_type uxn::patl::lca_oracle< SuffixCont >::allocator_type private
Definition at line 20 of file lca_oracle.hpp.
lca_type
template<typename SuffixCont > typedef impl::lca_base<lca_oracle<suffix_cont> > uxn::patl::lca_oracle< SuffixCont >::lca_type private
Definition at line 21 of file lca_oracle.hpp.
prefix
template<typename SuffixCont > typedef suffix_cont::prefix uxn::patl::lca_oracle< SuffixCont >::prefix
Definition at line 25 of file lca_oracle.hpp.
suffix_cont
template<typename SuffixCont > typedef SuffixCont uxn::patl::lca_oracle< SuffixCont >::suffix_cont private
Definition at line 19 of file lca_oracle.hpp.
vertex
template<typename SuffixCont > typedef suffix_cont::vertex uxn::patl::lca_oracle< SuffixCont >::vertex
Definition at line 24 of file lca_oracle.hpp.
Constructor & Destructor Documentation
lca_oracle()
template<typename SuffixCont > uxn::patl::lca_oracle< SuffixCont >::lca_oracle (const suffix_cont & cont) inline
ctor
Definition at line 47 of file lca_oracle.hpp.
        : cont_(&cont)
        , lca_alloc_(allocator_type())
        , lca_(0)
        , unsigned_alloc_(allocator_type())
        , lca_map_(0)
    {
        init();
    }
References uxn::patl::lca_oracle< SuffixCont >::init().
~lca_oracle()
template<typename SuffixCont > uxn::patl::lca_oracle< SuffixCont >::~lca_oracle () inline
Definition at line 57 of file lca_oracle.hpp.
    {
        lca_alloc_.deallocate(lca_, lca_size_);
        unsigned_alloc_.deallocate(lca_map_, lca_size_ + 1);
    }
References uxn::patl::lca_oracle< SuffixCont >::lca_, uxn::patl::lca_oracle< SuffixCont >::lca_alloc_, uxn::patl::lca_oracle< SuffixCont >::lca_map_, uxn::patl::lca_oracle< SuffixCont >::lca_size_, and uxn::patl::lca_oracle< SuffixCont >::unsigned_alloc_.
Member Function Documentation
get_by() [1/2]
template<typename SuffixCont > lca_type * uxn::patl::lca_oracle< SuffixCont >::get_by (const vertex & vtx) inline
utility func
Definition at line 34 of file lca_oracle.hpp.
    {
        return lca_ + cont_->vertex_index_of(vtx);
    }
References uxn::patl::lca_oracle< SuffixCont >::cont_, and uxn::patl::lca_oracle< SuffixCont >::lca_.
get_by() [2/2]
template<typename SuffixCont > const lca_type * uxn::patl::lca_oracle< SuffixCont >::get_by (const vertex & vtx) const inline
utility func
Definition at line 28 of file lca_oracle.hpp.
    {
        return lca_ + cont_->vertex_index_of(vtx);
    }
References uxn::patl::lca_oracle< SuffixCont >::cont_, and uxn::patl::lca_oracle< SuffixCont >::lca_.
Referenced by uxn::patl::lca_oracle< SuffixCont >::init(), and uxn::patl::lca_oracle< SuffixCont >::operator()().
init()
template<typename SuffixCont > void uxn::patl::lca_oracle< SuffixCont >::init () inline
Definition at line 63 of file lca_oracle.hpp.
    {
        // deallocate old
        lca_alloc_.deallocate(lca_, lca_size_);
        lca_ = 0;
        unsigned_alloc_.deallocate(lca_map_, lca_size_ + 1);
        lca_map_ = 0;
        //
        if (cont_->size() == 0)
            return;
        lca_ = lca_alloc_.allocate(lca_size_ = 2 * cont_->size());
        memset(lca_, 0, lca_size_ * sizeof(lca_type));
        lca_map_ = unsigned_alloc_.allocate(lca_size_ + 1);
        // numerate, set I- & L-nodes
        word_t num = 0;
        vertex vtx(cont_->root());
        const vertex vtxEnd(vtx.sibling());
        while (vtx != vtxEnd)
        {
            // descend to the leaves
            for (; !vtx.get_qtag(); vtx.iterate(0))
                get_by(vtx)->numerate(++num);
            //
            lca_type *cur = get_by(vtx);
            cur->numerate(++num);
            cur->set_inode();
            // move to the next
            if (vtx.get_qid())
            {
                while (vtx.get_parent_id())
                {
                    vtx.ascend();
                    get_by(vtx)->setup_i(this);
                }
                //
                vtx.ascend();
                get_by(vtx)->setup_i(this);
            }
            vtx.toggle();
        }
        // num - last numerator
        lca_root_h_ = impl::get_highest_bit_id(num);
        // set A bits
        vtx = cont_->root();
        lca_type *cur = get_by(vtx);
        cur->set_root_a();
        if (!vtx.get_qtag())
            vtx.iterate(0);
        for (; vtx != vtxEnd; vtx.template move_subtree<1>())
        {
            // descend to the leaves
            for (; !vtx.get_qtag(); vtx.iterate(0))
                get_by(vtx)->setup_a(this);
            //
            get_by(vtx)->setup_a(this);
        }
        // generate map: number -> index
        for (word_t i = 0; i != lca_size_; ++i)
            lca_map_[lca_[i].number()] = i;
    }
References uxn::patl::lca_oracle< SuffixCont >::cont_, uxn::patl::lca_oracle< SuffixCont >::get_by(), uxn::patl::impl::get_highest_bit_id(), uxn::patl::lca_oracle< SuffixCont >::lca_, uxn::patl::lca_oracle< SuffixCont >::lca_alloc_, uxn::patl::lca_oracle< SuffixCont >::lca_map_, uxn::patl::lca_oracle< SuffixCont >::lca_root_h_, uxn::patl::lca_oracle< SuffixCont >::lca_size_, uxn::patl::impl::lca_base< Oracle >::numerate(), uxn::patl::impl::lca_base< Oracle >::set_inode(), uxn::patl::impl::lca_base< Oracle >::set_root_a(), uxn::patl::impl::lca_base< Oracle >::setup_a(), uxn::patl::impl::lca_base< Oracle >::setup_i(), and uxn::patl::lca_oracle< SuffixCont >::unsigned_alloc_.
Referenced by uxn::patl::lca_oracle< SuffixCont >::lca_oracle().
new_algo()
template<typename SuffixCont > vertex uxn::patl::lca_oracle< SuffixCont >::new_algo (const lca_type * cur) const inline
utility func
Definition at line 40 of file lca_oracle.hpp.
    {
        const word_t id = cur - lca_;
        return cont_->vertex_by(id / 2, id & word_t(1));
    }
References uxn::patl::lca_oracle< SuffixCont >::cont_, and uxn::patl::lca_oracle< SuffixCont >::lca_.
Referenced by uxn::patl::lca_oracle< SuffixCont >::operator()().
operator()()
template<typename SuffixCont > vertex uxn::patl::lca_oracle< SuffixCont >::operator() (vertex vx, vertex vy) const inline
return LCA(vx, vy)
Definition at line 125 of file lca_oracle.hpp.
    {
        const lca_type
            *xPrime = get_by(vx),
            *xI = xPrime->get_i(),
            *yPrime = get_by(vy),
            *yI = yPrime->get_i();
        const word_t
            b = impl::get_binary_lca(lca_root_h_, xI->number(), yI->number()),
            i = impl::get_lowest_bit_id(b),
            xA = xPrime->get_a(),
            yA = yPrime->get_a(),
            j = impl::get_lowest_bit_id((xA & yA) >> i << i);
        //
        vertex
            xCap = new_algo(xPrime),
            yCap = new_algo(yPrime);
        if (impl::get_lowest_bit_id(xA) < j)
        {
            const word_t
                k = impl::get_highest_bit_id(xA & (word_t(1) << j) - 1),
                wINum = (xI->number() >> k | word_t(1)) << k;
            const lca_type
                *wI = lca_ + lca_map_[wINum],
                *wLI = wI->get_l_i();
            xCap = new_algo(wLI);
            xCap.ascend();
        }
        if (impl::get_lowest_bit_id(yA) < j)
        {
            const word_t
                k = impl::get_highest_bit_id(yA & (word_t(1) << j) - 1),
                wINum = (yI->number() >> k | word_t(1)) << k;
            const lca_type
                *wI = lca_ + lca_map_[wINum],
                *wLI = wI->get_l_i();
            yCap = new_algo(wLI);
            yCap.ascend();
        }
        return get_by(xCap)->number() < get_by(yCap)->number() ? xCap : yCap;
    }
References uxn::patl::impl::lca_base< Oracle >::get_a(), uxn::patl::impl::get_binary_lca(), uxn::patl::lca_oracle< SuffixCont >::get_by(), uxn::patl::impl::get_highest_bit_id(), uxn::patl::impl::lca_base< Oracle >::get_i(), uxn::patl::impl::lca_base< Oracle >::get_l_i(), uxn::patl::impl::get_lowest_bit_id(), uxn::patl::lca_oracle< SuffixCont >::lca_, uxn::patl::lca_oracle< SuffixCont >::lca_map_, uxn::patl::lca_oracle< SuffixCont >::lca_root_h_, uxn::patl::lca_oracle< SuffixCont >::new_algo(), and uxn::patl::impl::lca_base< Oracle >::number().
Member Data Documentation
cont_
template<typename SuffixCont > const suffix_cont* uxn::patl::lca_oracle< SuffixCont >::cont_ private
Definition at line 168 of file lca_oracle.hpp.
Referenced by uxn::patl::lca_oracle< SuffixCont >::get_by(), uxn::patl::lca_oracle< SuffixCont >::init(), and uxn::patl::lca_oracle< SuffixCont >::new_algo().
lca_
template<typename SuffixCont > lca_type* uxn::patl::lca_oracle< SuffixCont >::lca_ private
Definition at line 170 of file lca_oracle.hpp.
Referenced by uxn::patl::lca_oracle< SuffixCont >::get_by(), uxn::patl::lca_oracle< SuffixCont >::init(), uxn::patl::lca_oracle< SuffixCont >::new_algo(), uxn::patl::lca_oracle< SuffixCont >::operator()(), and uxn::patl::lca_oracle< SuffixCont >::~lca_oracle().
lca_alloc_
template<typename SuffixCont > allocator_type::template rebind<lca_type>::other uxn::patl::lca_oracle< SuffixCont >::lca_alloc_ private
Definition at line 169 of file lca_oracle.hpp.
Referenced by uxn::patl::lca_oracle< SuffixCont >::init(), and uxn::patl::lca_oracle< SuffixCont >::~lca_oracle().
lca_map_
template<typename SuffixCont > word_t* uxn::patl::lca_oracle< SuffixCont >::lca_map_ private
Definition at line 172 of file lca_oracle.hpp.
Referenced by uxn::patl::lca_oracle< SuffixCont >::init(), uxn::patl::lca_oracle< SuffixCont >::operator()(), and uxn::patl::lca_oracle< SuffixCont >::~lca_oracle().
lca_root_h_
template<typename SuffixCont > word_t uxn::patl::lca_oracle< SuffixCont >::lca_root_h_ private
Definition at line 171 of file lca_oracle.hpp.
Referenced by uxn::patl::lca_oracle< SuffixCont >::init(), and uxn::patl::lca_oracle< SuffixCont >::operator()().
lca_size_
template<typename SuffixCont > word_t uxn::patl::lca_oracle< SuffixCont >::lca_size_ private
Definition at line 171 of file lca_oracle.hpp.
Referenced by uxn::patl::lca_oracle< SuffixCont >::init(), and uxn::patl::lca_oracle< SuffixCont >::~lca_oracle().
unsigned_alloc_
template<typename SuffixCont > allocator_type::template rebind<word_t>::other uxn::patl::lca_oracle< SuffixCont >::unsigned_alloc_ private
Definition at line 173 of file lca_oracle.hpp.
Referenced by uxn::patl::lca_oracle< SuffixCont >::init(), and uxn::patl::lca_oracle< SuffixCont >::~lca_oracle().
The documentation for this class was generated from the following file:
uxn/patl/lca_oracle.hpp