PATL: uxn::patl::super_maxrep_iterator< Container > Class Template Reference
uxn::patl::super_maxrep_iterator< Container > Class Template Reference
#include <super_maxrep_iterator.hpp>
Classes
struct functor
struct key_type_less
Public Member Functions
super_maxrep_iterator (const Container *cont)
const prefix & operator* () const
const prefix * operator-> () const
word_t freq () const
super_maxrep_iterator & operator++ ()
super_maxrep_iterator operator++ (int)
Private Types
typedef Container::prefix prefix
typedef Container::key_type key_type
typedef std::set< key_type, key_type_less > unique_type
Private Member Functions
void push_new_pair ()
void unique_update (unique_type &us, const prefix &pref)
void unique_update (unique_type &us, const unique_type &us1)
void merge ()
Private Attributes
prefix pref_
functor func_
std::vector< std::pair< word_t, unique_type > > sfreq_
Detailed Description
template<typename Container>
class uxn::patl::super_maxrep_iterator< Container >
Definition at line 19 of file super_maxrep_iterator.hpp.
Member Typedef Documentation
key_type
template<typename Container > typedef Container::key_type uxn::patl::super_maxrep_iterator< Container >::key_type private
Definition at line 25 of file super_maxrep_iterator.hpp.
prefix
template<typename Container > typedef Container::prefix uxn::patl::super_maxrep_iterator< Container >::prefix private
Definition at line 24 of file super_maxrep_iterator.hpp.
unique_type
template<typename Container > typedef std::set<key_type, key_type_less> uxn::patl::super_maxrep_iterator< Container >::unique_type private
Definition at line 51 of file super_maxrep_iterator.hpp.
Constructor & Destructor Documentation
super_maxrep_iterator()
template<typename Container > uxn::patl::super_maxrep_iterator< Container >::super_maxrep_iterator (const Container * cont) inline
Definition at line 143 of file super_maxrep_iterator.hpp.
        : pref_(cont->root_prefix())
    {
        push_new_pair();
        func_.init(this);
        pref_.postorder_init(func_);
    }
References uxn::patl::super_maxrep_iterator< Container >::func_, uxn::patl::super_maxrep_iterator< Container >::functor::init(), uxn::patl::super_maxrep_iterator< Container >::pref_, and uxn::patl::super_maxrep_iterator< Container >::push_new_pair().
Member Function Documentation
freq()
template<typename Container > word_t uxn::patl::super_maxrep_iterator< Container >::freq () const inline
Definition at line 161 of file super_maxrep_iterator.hpp.
    {
        return sfreq_.back().first;
    }
References uxn::patl::super_maxrep_iterator< Container >::sfreq_.
merge()
template<typename Container > void uxn::patl::super_maxrep_iterator< Container >::merge () inline private
Definition at line 96 of file super_maxrep_iterator.hpp.
    {
        std::pair<word_t, unique_type>
            *sfreq1 = &sfreq_.back(),
            *sfreq0 = sfreq1 - 1;
        sfreq0->first += sfreq1->first;
        unique_update(sfreq0->second, sfreq1->second);
        sfreq_.pop_back();
    }
References uxn::patl::super_maxrep_iterator< Container >::sfreq_, and uxn::patl::super_maxrep_iterator< Container >::unique_update().
Referenced by uxn::patl::super_maxrep_iterator< Container >::functor::merge().
operator*()
template<typename Container > const prefix & uxn::patl::super_maxrep_iterator< Container >::operator* () const inline
Definition at line 151 of file super_maxrep_iterator.hpp.
    {
        return pref_;
    }
References uxn::patl::super_maxrep_iterator< Container >::pref_.
operator++() [1/2]
template<typename Container > super_maxrep_iterator & uxn::patl::super_maxrep_iterator< Container >::operator++ () inline
Definition at line 166 of file super_maxrep_iterator.hpp.
    {
        sfreq_.back().second.clear();
        pref_.postorder_incr(func_);
        return *this;
    }
References uxn::patl::super_maxrep_iterator< Container >::func_, uxn::patl::super_maxrep_iterator< Container >::pref_, and uxn::patl::super_maxrep_iterator< Container >::sfreq_.
operator++() [2/2]
template<typename Container > super_maxrep_iterator uxn::patl::super_maxrep_iterator< Container >::operator++ (int) inline
Definition at line 173 of file super_maxrep_iterator.hpp.
    {
        super_maxrep_iterator it(*this);
        ++*this;
        return it;
    }
operator->()
template<typename Container > const prefix * uxn::patl::super_maxrep_iterator< Container >::operator-> () const inline
Definition at line 156 of file super_maxrep_iterator.hpp.
    {
        return &**this;
    }
push_new_pair()
template<typename Container > void uxn::patl::super_maxrep_iterator< Container >::push_new_pair () inline private
Definition at line 53 of file super_maxrep_iterator.hpp.
    {
        sfreq_.push_back(std::make_pair(
            1,
            unique_type(key_type_less(pref_.cont()->keys()))));
    }
References uxn::patl::super_maxrep_iterator< Container >::pref_, and uxn::patl::super_maxrep_iterator< Container >::sfreq_.
Referenced by uxn::patl::super_maxrep_iterator< Container >::functor::push(), and uxn::patl::super_maxrep_iterator< Container >::super_maxrep_iterator().
unique_update() [1/2]
template<typename Container > void uxn::patl::super_maxrep_iterator< Container >::unique_update (unique_type & us, const prefix & pref) inline private
Definition at line 60 of file super_maxrep_iterator.hpp.
    {
        if (pref.is_root())
            us.clear();
        else if (pref.leaf(0))
        {
            // us is empty!
            us.insert(pref.key(0));
            if (!us.insert(pref.key(1)).second)
                us.clear();
        }
        else if (!us.empty() && !us.insert(pref.key(1)).second)
            us.clear();
    }
Referenced by uxn::patl::super_maxrep_iterator< Container >::functor::incr(), and uxn::patl::super_maxrep_iterator< Container >::merge().
unique_update() [2/2]
template<typename Container > void uxn::patl::super_maxrep_iterator< Container >::unique_update (unique_type & us, const unique_type & us1) inline private
Definition at line 75 of file super_maxrep_iterator.hpp.
    {
        if (us.empty() || us1.empty())
        {
            us.clear();
            return;
        }
        unique_type isect(key_type_less(pref_.cont()->keys()));
        std::set_intersection(
            us.begin(),
            us.end(),
            us1.begin(),
            us1.end(),
            std::inserter(isect, isect.end()),
            us.key_comp());
        if (isect.empty())
            us.insert(us1.begin(), us1.end());
        else
            us.clear();
    }
References uxn::patl::super_maxrep_iterator< Container >::pref_.
Member Data Documentation
func_
template<typename Container > functor uxn::patl::super_maxrep_iterator< Container >::func_ private
Definition at line 182 of file super_maxrep_iterator.hpp.
Referenced by uxn::patl::super_maxrep_iterator< Container >::operator++(), and uxn::patl::super_maxrep_iterator< Container >::super_maxrep_iterator().
pref_
template<typename Container > prefix uxn::patl::super_maxrep_iterator< Container >::pref_ private
Definition at line 181 of file super_maxrep_iterator.hpp.
Referenced by uxn::patl::super_maxrep_iterator< Container >::functor::incr(), uxn::patl::super_maxrep_iterator< Container >::operator*(), uxn::patl::super_maxrep_iterator< Container >::operator++(), uxn::patl::super_maxrep_iterator< Container >::push_new_pair(), uxn::patl::super_maxrep_iterator< Container >::super_maxrep_iterator(), and uxn::patl::super_maxrep_iterator< Container >::unique_update().
sfreq_
template<typename Container > std::vector<std::pair<word_t, unique_type> > uxn::patl::super_maxrep_iterator< Container >::sfreq_ private
Definition at line 183 of file super_maxrep_iterator.hpp.
Referenced by uxn::patl::super_maxrep_iterator< Container >::functor::cond(), uxn::patl::super_maxrep_iterator< Container >::freq(), uxn::patl::super_maxrep_iterator< Container >::functor::incr(), uxn::patl::super_maxrep_iterator< Container >::merge(), uxn::patl::super_maxrep_iterator< Container >::operator++(), and uxn::patl::super_maxrep_iterator< Container >::push_new_pair().
The documentation for this class was generated from the following file:
uxn/patl/super_maxrep_iterator.hpp