PATL: uxn::patl::aux::bit_input< Input > Class Template Reference
uxn::patl::aux::bit_input< Input > Class Template Reference
#include <bitwise_io.hpp>
Public Member Functions
bit_input (Input &src, word_t size=1<< 16)
~bit_input ()
word_t get_bit ()
word_t get_bits (word_t n)
word_t get_fib_code ()
word_t get_word ()
void get_bytes (char *bytes, word_t n)
Private Member Functions
bit_input & operator= (const bit_input &)
void read_full ()
Private Attributes
Input & src_
word_t *const beg_
word_t *const *const end_
word_t *const *const * cur_
word_t num_
Detailed Description
template<typename Input>
class uxn::patl::aux::bit_input< Input >
Definition at line 146 of file bitwise_io.hpp.
Constructor & Destructor Documentation
bit_input()
template<typename Input > uxn::patl::aux::bit_input< Input >::bit_input (Input & src, word_t size = 1 << 16) inline
Definition at line 151 of file bitwise_io.hpp.
        : src_(src)
        , beg_(new word_t [size])
        , end_(beg_ + size)
        , cur_(beg_)
        , num_(0)
    {
        src_(beg_, size * sizeof(word_t));
    }
References uxn::patl::aux::bit_input< Input >::beg_, and uxn::patl::aux::bit_input< Input >::src_.
~bit_input()
template<typename Input > uxn::patl::aux::bit_input< Input >::~bit_input () inline
Definition at line 161 of file bitwise_io.hpp.
    {
        delete[] beg_;
    }
References uxn::patl::aux::bit_input< Input >::beg_.
Member Function Documentation
get_bit()
template<typename Input > word_t uxn::patl::aux::bit_input< Input >::get_bit () inline
Definition at line 166 of file bitwise_io.hpp.
    {
        const word_t bit = *cur_ >> num_ & 1;
        if (++num_ & bits_in_word)
        {
            num_ = 0;
            read_full();
        }
        return bit;
    }
References bits_in_word, uxn::patl::aux::bit_input< Input >::cur_, uxn::patl::aux::bit_input< Input >::num_, and uxn::patl::aux::bit_input< Input >::read_full().
Referenced by uxn::patl::aux::bit_input< Input >::get_fib_code().
get_bits()
template<typename Input > word_t uxn::patl::aux::bit_input< Input >::get_bits (word_t n) inline
Definition at line 177 of file bitwise_io.hpp.
    {
        word_t bits = *cur_ >> num_;
        if ((num_ += n) & bits_in_word)
        {
            num_ &= bits_in_word - 1;
            read_full();
            bits |= *cur_ << (n - num_);
        }
        return bits & (1 << n) - 1;
    }
References bits_in_word, uxn::patl::aux::bit_input< Input >::cur_, uxn::patl::aux::bit_input< Input >::num_, and uxn::patl::aux::bit_input< Input >::read_full().
Referenced by uxn::patl::aux::bit_input< Input >::get_bytes().
get_bytes()
template<typename Input > void uxn::patl::aux::bit_input< Input >::get_bytes (char * bytes, word_t n) inline
Definition at line 218 of file bitwise_io.hpp.
    {
        word_t
            *cur = reinterpret_cast<word_t*>(bytes),
            *end = cur + n / sizeof(word_t);
        for (; cur != end; ++cur)
            *cur = get_word();
        if (n % sizeof(word_t))
            *cur = get_bits((n % sizeof(word_t)) * 8);
    }
References uxn::patl::aux::bit_input< Input >::get_bits(), and uxn::patl::aux::bit_input< Input >::get_word().
get_fib_code()
template<typename Input > word_t uxn::patl::aux::bit_input< Input >::get_fib_code () inline
Definition at line 189 of file bitwise_io.hpp.
    {
        for (word_t n = 0, i = 0; ; ++i)
        {
            if (get_bit())
            {
                n += fibs[i++];
                if (get_bit())
                    return n;
            }
        }
    }
References uxn::patl::aux::fibs, and uxn::patl::aux::bit_input< Input >::get_bit().
get_word()
template<typename Input > word_t uxn::patl::aux::bit_input< Input >::get_word () inline
Definition at line 202 of file bitwise_io.hpp.
    {
        if (num_)
        {
            const word_t dword = *cur_ >> num_;
            read_full();
            return dword | *cur_ << (bits_in_word - num_);
        }
        else
        {
            const word_t dword = *cur_;
            read_full();
            return dword;
        }
    }
References bits_in_word, uxn::patl::aux::bit_input< Input >::cur_, uxn::patl::aux::bit_input< Input >::num_, and uxn::patl::aux::bit_input< Input >::read_full().
Referenced by uxn::patl::aux::bit_input< Input >::get_bytes().
operator=()
template<typename Input > bit_input & uxn::patl::aux::bit_input< Input >::operator= (const bit_input< Input > &) private
read_full()
template<typename Input > void uxn::patl::aux::bit_input< Input >::read_full () inline private
Definition at line 230 of file bitwise_io.hpp.
    {
        if (++cur_ == end_)
        {
            src_(beg_, (end_ - beg_) * sizeof(word_t));
            cur_ = beg_;
        }
    }
References uxn::patl::aux::bit_input< Input >::beg_, uxn::patl::aux::bit_input< Input >::cur_, uxn::patl::aux::bit_input< Input >::end_, and uxn::patl::aux::bit_input< Input >::src_.
Referenced by uxn::patl::aux::bit_input< Input >::get_bit(), uxn::patl::aux::bit_input< Input >::get_bits(), and uxn::patl::aux::bit_input< Input >::get_word().
Member Data Documentation
beg_
template<typename Input > word_t* const uxn::patl::aux::bit_input< Input >::beg_ private
Definition at line 241 of file bitwise_io.hpp.
Referenced by uxn::patl::aux::bit_input< Input >::bit_input(), uxn::patl::aux::bit_input< Input >::read_full(), and uxn::patl::aux::bit_input< Input >::~bit_input().
cur_
template<typename Input > word_t* const * const * uxn::patl::aux::bit_input< Input >::cur_ private
Definition at line 243 of file bitwise_io.hpp.
Referenced by uxn::patl::aux::bit_input< Input >::get_bit(), uxn::patl::aux::bit_input< Input >::get_bits(), uxn::patl::aux::bit_input< Input >::get_word(), and uxn::patl::aux::bit_input< Input >::read_full().
end_
template<typename Input > word_t* const * const uxn::patl::aux::bit_input< Input >::end_ private
Definition at line 242 of file bitwise_io.hpp.
Referenced by uxn::patl::aux::bit_input< Input >::read_full().
num_
template<typename Input > word_t uxn::patl::aux::bit_input< Input >::num_ private
Definition at line 244 of file bitwise_io.hpp.
Referenced by uxn::patl::aux::bit_input< Input >::get_bit(), uxn::patl::aux::bit_input< Input >::get_bits(), and uxn::patl::aux::bit_input< Input >::get_word().
src_
template<typename Input > Input& uxn::patl::aux::bit_input< Input >::src_ private
Definition at line 239 of file bitwise_io.hpp.
Referenced by uxn::patl::aux::bit_input< Input >::bit_input(), and uxn::patl::aux::bit_input< Input >::read_full().
The documentation for this class was generated from the following file:
uxn/patl/aux_/bitwise_io.hpp