PATL: uxn/patl/config.hpp File Reference
config.hpp File Reference
Macros
#define PATL_NN
#define PATL_INTRINSIC
#define PATL_ALIGNHACK
#define PATL_ASSERT(x)
Typedefs
typedef undefined word_t
typedef undefined sword_t
Variables
const word_t bits_in_word = 8 * sizeof(word_t)
const word_t highest_bit = word_t(1) << (bits_in_word - 1)
Macro Definition Documentation
PATL_ALIGNHACK
#define PATL_ALIGNHACK
Definition at line 54 of file config.hpp.
PATL_ASSERT
#define PATL_ASSERT (x)
Definition at line 67 of file config.hpp.
PATL_INTRINSIC
#define PATL_INTRINSIC
Definition at line 44 of file config.hpp.
PATL_NN
#define PATL_NN
Definition at line 39 of file config.hpp.
Typedef Documentation
sword_t
typedef undefined sword_t
Definition at line 41 of file config.hpp.
word_t
typedef undefined word_t
Definition at line 40 of file config.hpp.
Variable Documentation
bits_in_word
const word_t bits_in_word = 8 * sizeof(word_t)
Definition at line 49 of file config.hpp.
Referenced by uxn::patl::impl::primes< Natural >::for(), uxn::patl::aux::bit_input< Input >::get_bit(), uxn::patl::reverse_bit_comparator< T, N >::get_bits(), uxn::patl::aux::bit_input< Input >::get_bits(), uxn::patl::impl::get_highest_bit(), uxn::patl::aux::bit_input< Input >::get_word(), uxn::patl::impl::max0(), uxn::patl::aux::bit_output< Output >::put_bit(), uxn::patl::aux::bit_output< Output >::put_bits(), and uxn::patl::aux::bit_output< Output >::put_word().
highest_bit
const word_t highest_bit = word_t(1) << (bits_in_word - 1)
Definition at line 50 of file config.hpp.
Referenced by uxn::patl::maxrep_iterator< Container >::bit31_update(), uxn::patl::maxrep_iterator< Container >::merge(), uxn::patl::impl::trie_generic< T, 0 >::read(), uxn::patl::impl::trie_generic< T, 0 >::show(), uxn::patl::levenshtein_tp_distance< Container, SameLength >::transitions(), and uxn::patl::levenshtein_ms_distance< Container, SameLength >::transitions().