PATL: uxn::patl::maxrep_iterator< Container > Class Template Reference
uxn::patl::maxrep_iterator< Container > Class Template Reference
#include <maxrep_iterator.hpp>
Classes
struct functor
Public Member Functions
maxrep_iterator (const Container *cont)
const prefix & operator* () const
const prefix * operator-> () const
word_t freq () const
maxrep_iterator & operator++ ()
maxrep_iterator operator++ (int)
Private Types
typedef Container::prefix prefix
typedef Container::key_type key_type
Private Member Functions
bool left_diff () const
void bit31_update ()
void merge ()
Private Attributes
prefix pref_
functor func_
std::vector< word_t > sfreq_
Detailed Description
template<typename Container>
class uxn::patl::maxrep_iterator< Container >
Definition at line 19 of file maxrep_iterator.hpp.
Member Typedef Documentation
key_type
template<typename Container > typedef Container::key_type uxn::patl::maxrep_iterator< Container >::key_type private
Definition at line 25 of file maxrep_iterator.hpp.
prefix
template<typename Container > typedef Container::prefix uxn::patl::maxrep_iterator< Container >::prefix private
Definition at line 24 of file maxrep_iterator.hpp.
Constructor & Destructor Documentation
maxrep_iterator()
template<typename Container > uxn::patl::maxrep_iterator< Container >::maxrep_iterator (const Container * cont) inline
Definition at line 93 of file maxrep_iterator.hpp.
        : pref_(cont->root_prefix())
        , sfreq_(1, 1)
    {
        func_.init(this);
        pref_.postorder_init(func_);
    }
References uxn::patl::maxrep_iterator< Container >::func_, uxn::patl::maxrep_iterator< Container >::functor::init(), and uxn::patl::maxrep_iterator< Container >::pref_.
Member Function Documentation
bit31_update()
template<typename Container > void uxn::patl::maxrep_iterator< Container >::bit31_update () inline private
Definition at line 40 of file maxrep_iterator.hpp.
    {
        if (!impl::get_highest_bit(sfreq_.back()) && left_diff())
            sfreq_.back() |= highest_bit;
    }
References uxn::patl::impl::get_highest_bit(), highest_bit, uxn::patl::maxrep_iterator< Container >::left_diff(), and uxn::patl::maxrep_iterator< Container >::sfreq_.
Referenced by uxn::patl::maxrep_iterator< Container >::functor::update().
freq()
template<typename Container > word_t uxn::patl::maxrep_iterator< Container >::freq () const inline
Definition at line 111 of file maxrep_iterator.hpp.
    {
        return impl::bits_but_highest(sfreq_.back());
    }
References uxn::patl::impl::bits_but_highest(), and uxn::patl::maxrep_iterator< Container >::sfreq_.
left_diff()
template<typename Container > bool uxn::patl::maxrep_iterator< Container >::left_diff () const inline private
Definition at line 27 of file maxrep_iterator.hpp.
    {
        if (pref_.is_root())
            return true;
        const key_type
            key0 = pref_.key(0),
            key1 = pref_.key(1);
        return
            key0 == pref_.cont()->keys() ||
            key1 == pref_.cont()->keys() ||
            key0[-1] != key1[-1];
    }
References uxn::patl::maxrep_iterator< Container >::pref_.
Referenced by uxn::patl::maxrep_iterator< Container >::bit31_update().
merge()
template<typename Container > void uxn::patl::maxrep_iterator< Container >::merge () inline private
Definition at line 46 of file maxrep_iterator.hpp.
    {
        const word_t sfreq1 = sfreq_.back();
        sfreq_.pop_back();
        sfreq_.back() =
            ((sfreq_.back() | sfreq1) & highest_bit) |
            (impl::bits_but_highest(sfreq_.back()) + impl::bits_but_highest(sfreq1));
    }
References uxn::patl::impl::bits_but_highest(), highest_bit, and uxn::patl::maxrep_iterator< Container >::sfreq_.
Referenced by uxn::patl::maxrep_iterator< Container >::functor::merge().
operator*()
template<typename Container > const prefix & uxn::patl::maxrep_iterator< Container >::operator* () const inline
Definition at line 101 of file maxrep_iterator.hpp.
    {
        return pref_;
    }
References uxn::patl::maxrep_iterator< Container >::pref_.
operator++() [1/2]
template<typename Container > maxrep_iterator & uxn::patl::maxrep_iterator< Container >::operator++ () inline
Definition at line 116 of file maxrep_iterator.hpp.
    {
        pref_.postorder_incr(func_);
        return *this;
    }
References uxn::patl::maxrep_iterator< Container >::func_, and uxn::patl::maxrep_iterator< Container >::pref_.
operator++() [2/2]
template<typename Container > maxrep_iterator uxn::patl::maxrep_iterator< Container >::operator++ (int) inline
Definition at line 122 of file maxrep_iterator.hpp.
    {
        maxrep_iterator it(*this);
        ++*this;
        return it;
    }
operator->()
template<typename Container > const prefix * uxn::patl::maxrep_iterator< Container >::operator-> () const inline
Definition at line 106 of file maxrep_iterator.hpp.
    {
        return &**this;
    }
Member Data Documentation
func_
template<typename Container > functor uxn::patl::maxrep_iterator< Container >::func_ private
Definition at line 131 of file maxrep_iterator.hpp.
Referenced by uxn::patl::maxrep_iterator< Container >::maxrep_iterator(), and uxn::patl::maxrep_iterator< Container >::operator++().
pref_
template<typename Container > prefix uxn::patl::maxrep_iterator< Container >::pref_ private
Definition at line 130 of file maxrep_iterator.hpp.
Referenced by uxn::patl::maxrep_iterator< Container >::left_diff(), uxn::patl::maxrep_iterator< Container >::maxrep_iterator(), uxn::patl::maxrep_iterator< Container >::operator*(), and uxn::patl::maxrep_iterator< Container >::operator++().
sfreq_
template<typename Container > std::vector<word_t> uxn::patl::maxrep_iterator< Container >::sfreq_ private
Definition at line 132 of file maxrep_iterator.hpp.
Referenced by uxn::patl::maxrep_iterator< Container >::bit31_update(), uxn::patl::maxrep_iterator< Container >::functor::cond(), uxn::patl::maxrep_iterator< Container >::freq(), uxn::patl::maxrep_iterator< Container >::functor::incr(), uxn::patl::maxrep_iterator< Container >::merge(), and uxn::patl::maxrep_iterator< Container >::functor::push().
The documentation for this class was generated from the following file:
uxn/patl/maxrep_iterator.hpp