PATL: uxn::patl::impl::trie_generic< T, 0 > Class Template Reference
uxn::patl::impl::trie_generic< T, 0 > Class Template Reference
#include <trie_generic.hpp>
Classes
struct default_read_value
struct default_show_value
struct void_merge_handler
Public Types
typedef super::key_type key_type
typedef super::value_type value_type
typedef super::bit_compare bit_compare
typedef super::allocator_type allocator_type
typedef super::size_type size_type
typedef super::const_iterator const_iterator
typedef super::iterator iterator
typedef super::const_vertex const_vertex
typedef super::vertex vertex
typedef super::const_preorder_iterator const_preorder_iterator
typedef super::const_postorder_iterator const_postorder_iterator
typedef super::preorder_iterator preorder_iterator
typedef super::postorder_iterator postorder_iterator
typedef algorithm::const_key_reference const_key_reference
Public Types inherited from uxn::patl::impl::assoc_generic< trie_generic< T, T::N_ >, trie_generic_traits< T, node_gen, algorithm_gen, core_prefix_generic, trie_generic< T, T::N_ > >, T::N_ >
typedef T::prefix prefix
typedef vertex_generic< algorithm > vertex
typedef preorder_iterator_generic< vertex > preorder_iterator
typedef postorder_iterator_generic< vertex > postorder_iterator
typedef T::key_type key_type
typedef T::value_type value_type
typedef T::bit_compare bit_compare
typedef T::allocator_type allocator_type
typedef const value_type * const_pointer
typedef const value_type & const_reference
typedef value_type * pointer
typedef value_type & reference
typedef allocator_type::difference_type difference_type
typedef word_t size_type
typedef const_iterator_generic< vertex > const_iterator
typedef iterator_generic< vertex > iterator
Public Member Functions
trie_generic (const bit_compare &bit_comp, const allocator_type &alloc)
trie_generic (const this_t &b)
trie_generic (const value_type *first, const value_type *last, const bit_compare &bit_comp, const allocator_type &alloc)
~trie_generic ()
this_t & operator= (const this_t &b)
void swap (this_t &b)
void clear ()
size_type size () const
size_type max_size () const
allocator_type get_allocator () const
iter_bool_pair insert (const value_type &val)
iterator insert (iterator hint, const value_type &val)
hinted insertion method
template<typename Iter >
void insert (Iter first, Iter last)
template of insert range
template<typename Handler >
void merge (const_iterator first, const_iterator last, Handler handler)
merge two identical tries (instances of bit_compare must be equal)
void merge (const_iterator first, const_iterator last)
template<typename OutIter , typename ShowValue >
void show (OutIter oit, ShowValue show_val) const
serialize trie
template<typename OutIter >
void show (OutIter oit) const
template<typename InIter , typename ReadValue >
void read (InIter iit, InIter iit_end, ReadValue read_val)
deserialize trie
template<typename InIter >
void read (InIter iit, InIter iit_end)
void erase (iterator del_it)
size_type erase (const key_type &key, word_t prefixLen=~word_t(0))
erase all values with specified prefix
Public Member Functions inherited from uxn::patl::impl::assoc_generic< trie_generic< T, T::N_ >, trie_generic_traits< T, node_gen, algorithm_gen, core_prefix_generic, trie_generic< T, T::N_ > >, T::N_ >
assoc_generic ()
assoc_generic (const bit_compare &bit_comp)
Static Public Attributes
static const word_t N_ = T::N_
Static Public Attributes inherited from uxn::patl::impl::assoc_generic< trie_generic< T, T::N_ >, trie_generic_traits< T, node_gen, algorithm_gen, core_prefix_generic, trie_generic< T, T::N_ > >, T::N_ >
static const word_t N_
Protected Types
typedef traits::node_type node_type
typedef traits::algorithm algorithm
Protected Types inherited from uxn::patl::impl::assoc_generic< trie_generic< T, T::N_ >, trie_generic_traits< T, node_gen, algorithm_gen, core_prefix_generic, trie_generic< T, T::N_ > >, T::N_ >
typedef T::algorithm algorithm
typedef T::node_type node_type
Protected Member Functions
algorithm add_root (const value_type &val)
create root in empty trie
algorithm add (const value_type &val, algorithm &pal, word_t prefixLen)
add new node with unique key
Protected Member Functions inherited from uxn::patl::impl::assoc_generic< trie_generic< T, T::N_ >, trie_generic_traits< T, node_gen, algorithm_gen, core_prefix_generic, trie_generic< T, T::N_ > >, T::N_ >
word_t * get_shortcut (word_t a) const
word_t * create_shortcut (word_t a)
Protected Attributes
allocator_type::template rebind< node_type >::other alloc_
size_type size_
Private Types
typedef trie_generic< T, T::N_ > this_t
typedef trie_generic_traits< T, node_gen, algorithm_gen, core_prefix_generic, this_t > traits
typedef assoc_generic< trie_generic< T, T::N_ >, traits, T::N_ > super
typedef std::pair< iterator, bool > iter_bool_pair
Private Member Functions
void del_tree (node_type *node)
void del_node (node_type *node)
void erase_subtree (algorithm pal)
void erase_node (algorithm pal)
Detailed Description
template<typename T>
class uxn::patl::impl::trie_generic< T, 0 >
Definition at line 255 of file trie_generic.hpp.
Member Typedef Documentation
algorithm
template<typename T > typedef traits::algorithm uxn::patl::impl::trie_generic< T, 0 >::algorithm protected
Definition at line 267 of file trie_generic.hpp.
allocator_type
template<typename T > typedef super::allocator_type uxn::patl::impl::trie_generic< T, 0 >::allocator_type
Definition at line 273 of file trie_generic.hpp.
bit_compare
template<typename T > typedef super::bit_compare uxn::patl::impl::trie_generic< T, 0 >::bit_compare
Definition at line 272 of file trie_generic.hpp.
const_iterator
template<typename T > typedef super::const_iterator uxn::patl::impl::trie_generic< T, 0 >::const_iterator
Definition at line 275 of file trie_generic.hpp.
const_key_reference
template<typename T > typedef algorithm::const_key_reference uxn::patl::impl::trie_generic< T, 0 >::const_key_reference
Definition at line 284 of file trie_generic.hpp.
const_postorder_iterator
template<typename T > typedef super::const_postorder_iterator uxn::patl::impl::trie_generic< T, 0 >::const_postorder_iterator
Definition at line 280 of file trie_generic.hpp.
const_preorder_iterator
template<typename T > typedef super::const_preorder_iterator uxn::patl::impl::trie_generic< T, 0 >::const_preorder_iterator
Definition at line 279 of file trie_generic.hpp.
const_vertex
template<typename T > typedef super::const_vertex uxn::patl::impl::trie_generic< T, 0 >::const_vertex
Definition at line 277 of file trie_generic.hpp.
iter_bool_pair
template<typename T > typedef std::pair<iterator, bool> uxn::patl::impl::trie_generic< T, 0 >::iter_bool_pair private
Definition at line 361 of file trie_generic.hpp.
iterator
template<typename T > typedef super::iterator uxn::patl::impl::trie_generic< T, 0 >::iterator
Definition at line 276 of file trie_generic.hpp.
key_type
template<typename T > typedef super::key_type uxn::patl::impl::trie_generic< T, 0 >::key_type
Definition at line 270 of file trie_generic.hpp.
node_type
template<typename T > typedef traits::node_type uxn::patl::impl::trie_generic< T, 0 >::node_type protected
Definition at line 266 of file trie_generic.hpp.
postorder_iterator
template<typename T > typedef super::postorder_iterator uxn::patl::impl::trie_generic< T, 0 >::postorder_iterator
Definition at line 282 of file trie_generic.hpp.
preorder_iterator
template<typename T > typedef super::preorder_iterator uxn::patl::impl::trie_generic< T, 0 >::preorder_iterator
Definition at line 281 of file trie_generic.hpp.
size_type
template<typename T > typedef super::size_type uxn::patl::impl::trie_generic< T, 0 >::size_type
Definition at line 274 of file trie_generic.hpp.
super
template<typename T > typedef assoc_generic<trie_generic<T, T::N_>, traits, T::N_> uxn::patl::impl::trie_generic< T, 0 >::super private
Definition at line 263 of file trie_generic.hpp.
this_t
template<typename T > typedef trie_generic<T, T::N_> uxn::patl::impl::trie_generic< T, 0 >::this_t private
Definition at line 261 of file trie_generic.hpp.
traits
template<typename T > typedef trie_generic_traits<T, node_gen, algorithm_gen, core_prefix_generic, this_t> uxn::patl::impl::trie_generic< T, 0 >::traits private
Definition at line 262 of file trie_generic.hpp.
value_type
template<typename T > typedef super::value_type uxn::patl::impl::trie_generic< T, 0 >::value_type
Definition at line 271 of file trie_generic.hpp.
vertex
template<typename T > typedef super::vertex uxn::patl::impl::trie_generic< T, 0 >::vertex
Definition at line 278 of file trie_generic.hpp.
Constructor & Destructor Documentation
trie_generic() [1/3]
template<typename T > uxn::patl::impl::trie_generic< T, 0 >::trie_generic (const bit_compare & bit_comp, const allocator_type & alloc) inline
Definition at line 288 of file trie_generic.hpp.
        : super(bit_comp)
        , alloc_(alloc)
        , size_(0)
    {
    }
trie_generic() [2/3]
template<typename T > uxn::patl::impl::trie_generic< T, 0 >::trie_generic (const this_t & b) inline
Definition at line 295 of file trie_generic.hpp.
        : super(b.bit_comp_)
        , alloc_(b.alloc_)
        , size_(0)
    {
        insert(b.begin(), b.end());
    }
References uxn::patl::impl::trie_generic< T, N >::insert().
trie_generic() [3/3]
template<typename T > uxn::patl::impl::trie_generic< T, 0 >::trie_generic (const value_type * first, const value_type * last, const bit_compare & bit_comp, const allocator_type & alloc) inline
Definition at line 303 of file trie_generic.hpp.
        : super(bit_comp)
        , alloc_(alloc)
        , size_(0)
    {
        insert(first, last);
    }
References uxn::patl::impl::trie_generic< T, N >::insert().
~trie_generic()
template<typename T > uxn::patl::impl::trie_generic< T, 0 >::~trie_generic () inline
Definition at line 315 of file trie_generic.hpp.
    {
        del_tree(this->root_);
    }
Member Function Documentation
add()
template<typename T > algorithm uxn::patl::impl::trie_generic< T, 0 >::add (const value_type & val, algorithm & pal, word_t prefixLen) inline protected
add new node with unique key
Definition at line 648 of file trie_generic.hpp.
    {
        // brave new node
        node_type *r = alloc_.allocate(1);
        alloc_.construct(r, node_type(val));
        // add new node into trie
        const word_t b = this->bit_comp_.get_bit(T::ref_key(val), prefixLen);
        pal.add(r, b, prefixLen);
        ++size_;
        return algorithm(CSELF, r, b);
    }
References CSELF.
add_root()
template<typename T > algorithm uxn::patl::impl::trie_generic< T, 0 >::add_root (const value_type & val) inline protected
create root in empty trie
Definition at line 638 of file trie_generic.hpp.
    {
        this->root_ = alloc_.allocate(1);
        alloc_.construct(this->root_, node_type(val));
        this->root_->init_root();
        size_ = 1;
        return algorithm(CSELF, this->root_, 0);
    }
References CSELF.
clear()
template<typename T > void uxn::patl::impl::trie_generic< T, 0 >::clear () inline
Definition at line 339 of file trie_generic.hpp.
    {
        del_tree(this->root_);
        this->root_ = 0;
    }
del_node()
template<typename T > void uxn::patl::impl::trie_generic< T, 0 >::del_node (node_type * node) inline private
Definition at line 604 of file trie_generic.hpp.
    {
        alloc_.destroy(node);
        alloc_.deallocate(node, 1);
        --size_;
    }
del_tree()
template<typename T > void uxn::patl::impl::trie_generic< T, 0 >::del_tree (node_type * node) inline private
Definition at line 588 of file trie_generic.hpp.
    {
        if (node)
        {
            vertex vtx(this->root());
            for (postorder_iterator pit = vtx.postorder_begin()
                ; pit != vtx.postorder_end()
                ; ++pit)
            {
                if (!pit->get_qtag())
                    del_node(static_cast<algorithm&>(*pit).get_p());
            }
            del_node(node);
        }
    }
References uxn::patl::impl::vertex_generic< Algorithm >::postorder_begin(), and uxn::patl::impl::vertex_generic< Algorithm >::postorder_end().
erase() [1/2]
template<typename T > size_type uxn::patl::impl::trie_generic< T, 0 >::erase (const key_type & key, word_t prefixLen = ~word_t(0)) inline
erase all values with specified prefix
Definition at line 566 of file trie_generic.hpp.
    {
        if (this->root_)
        {
            algorithm pal(this, this->root_, 0);
            if (pal.mismatch(key, prefixLen) >= prefixLen)
            {
                const size_type pastSize = size();
                // if erase entire tree
                if (pal.get_q() == this->root_)
                {
                    clear();
                    return pastSize;
                }
                erase_subtree(pal);
                return pastSize - size();
            }
        }
        return 0;
    }
erase() [2/2]
template<typename T > void uxn::patl::impl::trie_generic< T, 0 >::erase (iterator del_it) inline
Definition at line 559 of file trie_generic.hpp.
    {
        // retrieve algorithm structure from iterator
        erase_node(static_cast<algorithm&>(static_cast<vertex&>(del_it)));
    }
erase_node()
template<typename T > void uxn::patl::impl::trie_generic< T, 0 >::erase_node (algorithm pal) inline private
Definition at line 626 of file trie_generic.hpp.
    {
        node_type *p = pal.erase();
        // special case: del root
        if (p == this->root_)
            this->root_ = pal.get_q() == p ? 0 : pal.get_q();
        // sic transit gloria mundi
        del_node(p);
    }
erase_subtree()
template<typename T > void uxn::patl::impl::trie_generic< T, 0 >::erase_subtree (algorithm pal) inline private
Definition at line 611 of file trie_generic.hpp.
    {
        // if erase subtree
        if (!pal.get_qtag())
        {
            // deallocate subtree
            del_tree(pal.get_p());
            // need to find the node with key whose prefix
            // we erase among nodes from pal.get_q() up to root_
            pal.get_q()->set_xlinktag(pal.get_qid(),
                pal.get_subtree_node(), 1);
        }
        erase_node(pal);
    }
get_allocator()
template<typename T > allocator_type uxn::patl::impl::trie_generic< T, 0 >::get_allocator () const inline
Definition at line 355 of file trie_generic.hpp.
    {
        return alloc_;
    }
insert() [1/3]
template<typename T > iter_bool_pair uxn::patl::impl::trie_generic< T, 0 >::insert (const value_type & val) inline
Definition at line 364 of file trie_generic.hpp.
    {
        if (this->root_)
        {
            algorithm pal(CSELF, this->root_, 0);
            // find a number of first mismatching bit
            const word_t l = pal.mismatch(T::ref_key(val));
            // if this number end at infinity
            if (~word_t(0) == l)
                // then this key already in trie
                return iter_bool_pair(iterator(vertex(pal)), false);
            // add new node for value with unique key
            return iter_bool_pair(iterator(vertex(add(val, pal, l))), true);
        }
        // if trie is empty then add root
        return iter_bool_pair(iterator(vertex(add_root(val))), true);
    }
References CSELF.
insert() [2/3]
template<typename T > template<typename Iter > void uxn::patl::impl::trie_generic< T, 0 >::insert (Iter first, Iter last) inline
template of insert range
Definition at line 420 of file trie_generic.hpp.
    {
        for (; first != last; ++first)
            insert(*first);
    }
References uxn::patl::impl::trie_generic< T, N >::insert().
insert() [3/3]
template<typename T > iterator uxn::patl::impl::trie_generic< T, 0 >::insert (iterator hint, const value_type & val) inline
hinted insertion method
Definition at line 383 of file trie_generic.hpp.
    {
        if (this->root_)
        {
            algorithm &pal = static_cast<algorithm&>(static_cast<vertex&>(hint));
            const key_type &key = T::ref_key(val);
            const word_t skip = this->bit_comp_.bit_mismatch(key, pal.get_key());
            if (~word_t(0) == skip)
                return iterator(vertex(pal));
            pal.ascend_less(skip);
            // find a number of first mismatching bit
            {
                const word_t len = this->bit_comp_.bit_length(key);
                if (len == ~word_t(0))
                    pal.run(key);
                else
                    pal.run(key, len);
            }
            const word_t l =
                this->bit_comp_.bit_mismatch(key, pal.get_key(), skip);
            // if this number end at infinity
            if (~word_t(0) == l)
                // then this key already in trie
                return iterator(vertex(pal));
            else
            {
                pal.ascend(l);
                // add new node for value with unique key
                return iterator(vertex(add(val, pal, l)));
            }
        }
        // if trie is empty then add root
        return iterator(vertex(add_root(val)));
    }
max_size()
template<typename T > size_type uxn::patl::impl::trie_generic< T, 0 >::max_size () const inline
Definition at line 350 of file trie_generic.hpp.
    {
        return alloc_.max_size();
    }
merge() [1/2]
template<typename T > void uxn::patl::impl::trie_generic< T, 0 >::merge (const_iterator first, const_iterator last) inline
Definition at line 471 of file trie_generic.hpp.
    {
        merge(first, last, void_merge_handler());
    }
merge() [2/2]
template<typename T > template<typename Handler > void uxn::patl::impl::trie_generic< T, 0 >::merge (const_iterator first, const_iterator last, Handler handler) inline
merge two identical tries (instances of bit_compare must be equal)
Definition at line 436 of file trie_generic.hpp.
    {
        // if trie is empty it is necessary to insert first element
        if (!this->root_ && first != last)
        {
            insert(*first);
            ++first;
        }
        algorithm pal_cur(this, this->root_, 0);
        const_vertex vtx(first);
        const algorithm &pal_end(static_cast<const const_vertex&>(last));
        word_t skip = 0;
        while (static_cast<const algorithm&>(vtx) != pal_end)
        {
            pal_cur.ascend_less(skip);
            const word_t l = pal_cur.mismatch(vtx.key());
            if (~word_t(0) == l)
                // identical keys found - handler must be applied
                handler(iterator(vertex(pal_cur)), const_iterator(vtx));
            else
                add(vtx.value(), pal_cur, l);
            // move to the next
            if (vtx.get_qid())
            {
                const node_type *cur = static_cast<const algorithm&>(vtx).get_q();
                for (; cur->get_parent_id(); cur = cur->get_parent()) ;
                vtx = vertex(this, cur->get_parent(), 1);
            }
            else
                vtx.toggle();
            skip = static_cast<const algorithm&>(vtx).get_q()->get_skip();
            vtx.template descend<0>();
        }
    }
References uxn::patl::impl::trie_generic< T, N >::insert().
operator=()
template<typename T > this_t & uxn::patl::impl::trie_generic< T, 0 >::operator= (const this_t & b) inline
Definition at line 320 of file trie_generic.hpp.
    {
        del_tree(this->root_);
        this->bit_comp_ = b.bit_comp_;
        alloc_ = b.alloc_;
        this->root_ = 0;
        size_ = 0;
        insert(b.begin(), b.end());
        return *this;
    }
References uxn::patl::impl::trie_generic< T, N >::insert().
read() [1/2]
template<typename T > template<typename InIter > void uxn::patl::impl::trie_generic< T, 0 >::read (InIter iit, InIter iit_end) inline
Definition at line 554 of file trie_generic.hpp.
    {
        read(iit, iit_end, default_read_value<InIter>());
    }
read() [2/2]
template<typename T > template<typename InIter , typename ReadValue > void uxn::patl::impl::trie_generic< T, 0 >::read (InIter iit, InIter iit_end, ReadValue read_val) inline
deserialize trie
Definition at line 532 of file trie_generic.hpp.
    {
        clear();
        if (iit == iit_end)
            return;
        preorder_iterator pit(vertex(add_root(read_val(iit))));
        while (iit != iit_end)
        {
            const word_t skip = *iit++;
            if (skip & highest_bit)
                std::advance(pit, bits_but_highest(skip));
            else
            {
                static_cast<algorithm&>(*pit) =
                    add(read_val(iit), *pit, skip);
                if (pit->get_qid())
                    pit->toggle();
            }
        }
    }
References uxn::patl::impl::bits_but_highest(), and highest_bit.
show() [1/2]
template<typename T > template<typename OutIter > void uxn::patl::impl::trie_generic< T, 0 >::show (OutIter oit) const inline
Definition at line 515 of file trie_generic.hpp.
    {
        show(oit, default_show_value<OutIter>());
    }
show() [2/2]
template<typename T > template<typename OutIter , typename ShowValue > void uxn::patl::impl::trie_generic< T, 0 >::show (OutIter oit, ShowValue show_val) const inline
serialize trie
Definition at line 488 of file trie_generic.hpp.
    {
        if (!this->root_)
            return;
        const_vertex vtx(this->root());
        show_val(oit, vtx.parent_key());
        word_t skip_ins = 0;
        for (const_preorder_iterator pit = vtx.preorder_begin()
            ; pit != vtx.preorder_end()
            ; ++pit)
        {
            if (pit->get_qtag())
                ++skip_ins;
            else
            {
                if (skip_ins)
                {
                    *oit++ = highest_bit | skip_ins;
                    skip_ins = 0;
                }
                *oit++ = pit->next_skip();
                show_val(oit, pit->key());
            }
        }
    }
References highest_bit.
size()
template<typename T > size_type uxn::patl::impl::trie_generic< T, 0 >::size () const inline
Definition at line 345 of file trie_generic.hpp.
    {
        return size_;
    }
swap()
template<typename T > void uxn::patl::impl::trie_generic< T, 0 >::swap (this_t & b) inline
Definition at line 331 of file trie_generic.hpp.
    {
        std::swap(this->bit_comp_, b.bit_comp_);
        std::swap(alloc_, b.alloc_);
        std::swap(this->root_, b.root_);
        std::swap(size_, b.size_);
    }
References uxn::patl::swap().
Member Data Documentation
alloc_
template<typename T > allocator_type::template rebind<node_type>::other uxn::patl::impl::trie_generic< T, 0 >::alloc_ protected
Definition at line 661 of file trie_generic.hpp.
N_
template<typename T > const word_t uxn::patl::impl::trie_generic< T, 0 >::N_ = T::N_ static
Definition at line 286 of file trie_generic.hpp.
size_
template<typename T > size_type uxn::patl::impl::trie_generic< T, 0 >::size_ protected
Definition at line 662 of file trie_generic.hpp.
The documentation for this class was generated from the following file:
uxn/patl/impl/trie_generic.hpp