PATL: uxn::patl::impl Namespace Reference
uxn::patl::impl Namespace Reference
Classes
class algorithm_gen
class algorithm_gen_ngram
class algorithm_gen_suffix
struct algorithm_gen_traits
class algorithm_generic
class algorithm_generic< T, This, Container, 0 >
class assoc_generic
class assoc_generic< This, T, 0 >
class const_iterator_generic
class const_partimator_generic
class const_postorder_iterator_generic
class const_preorder_iterator_generic
class const_vertex_generic
class core_algorithm_generic
core memory algorithm template
class core_prefix_generic
class generator_base
class hash_node
class iterator_generic
class lca_base
class levenshtein_generic
class ngram_stat_traits
class node_gen
class node_gen_ngram
class node_gen_suffix
class node_generic
Base class of PATRICIA node.
class partial_base
class partimator_generic
class patricia_dot_base
class patricia_dot_base< suffix_set< Type, N, Delta, BitComp, Allocator >, OutStream >
class postorder_iterator_generic
class prefix_generic
class preorder_iterator_generic
class primes
class range_coder_base
class ring_buffer
class suffix_generic
struct suffix_generic_traits
class suffix_map_traits
class suffix_set_traits
class trie_generic
class trie_generic< T, 0 >
struct trie_generic_traits
class trie_map_traits
class trie_set_traits
class vertex_generic
Functions
std::string graphviz_printable_string (const char *p, word_t l)
template<typename Natural >
Natural sqrt_int (Natural x)
template<typename T , word_t N>
bool operator== (const trie_generic< T, N > &a, const trie_generic< T, N > &b)
template<typename T , word_t N>
bool operator!= (const trie_generic< T, N > &a, const trie_generic< T, N > &b)
word_t get_highest_bit (word_t x)
word_t bits_but_highest (word_t x)
word_t get_lowest_bit_id (word_t x)
word_t get_highest_bit_id (word_t x)
template<typename T >
T get_min (T a, T b)
template<typename T >
T get_max (T a, T b)
word_t get_binary_lca (word_t rootH, word_t i, word_t j)
template<word_t Align>
word_t align_down (word_t value)
template<word_t Align>
word_t align_up (word_t value)
word_t max0 (sword_t x)
template<typename Source >
word_t unsigned_cast (Source val)
word_t unsigned_cast (word_t val)
template<typename T >
word_t bit_mismatch_scalar (T a, T b)
Function Documentation
align_down()
template<word_t Align> word_t uxn::patl::impl::align_down (word_t value) inline
Definition at line 128 of file trivial.hpp.
{
    return value & (word_t(0) - Align);
}
align_up()
template<word_t Align> word_t uxn::patl::impl::align_up (word_t value) inline
Definition at line 134 of file trivial.hpp.
{
    return value + Align - word_t(1) & (word_t(0) - Align);
}
Referenced by uxn::patl::aux::file_mapping_input::create_view().
bit_mismatch_scalar()
template<typename T > word_t uxn::patl::impl::bit_mismatch_scalar (T a, T b) inline
Definition at line 157 of file trivial.hpp.
{
    return 8 * sizeof(T) - 1 -
        get_highest_bit_id(unsigned_cast(a) ^ unsigned_cast(b));
}
References get_highest_bit_id(), and unsigned_cast().
Referenced by uxn::patl::bit_comparator< T, 0 >::bit_mismatch().
bits_but_highest()
word_t uxn::patl::impl::bits_but_highest (word_t x) inline
Definition at line 29 of file trivial.hpp.
{
    return x & ~highest_bit;
}
Referenced by uxn::patl::maxrep_iterator< Container >::freq(), uxn::patl::maxrep_iterator< Container >::merge(), uxn::patl::impl::levenshtein_generic< This, Container, SameLength >::operator()(), uxn::patl::impl::trie_generic< T, 0 >::read(), uxn::patl::levenshtein_tp_distance< Container, SameLength >::transitions(), and uxn::patl::levenshtein_ms_distance< Container, SameLength >::transitions().
get_binary_lca()
word_t uxn::patl::impl::get_binary_lca (word_t rootH, word_t i, word_t j) inline
Definition at line 112 of file trivial.hpp.
{
    if (i == j)
        return i;
    //sort_2(i, j); // à íóæíî ëè?
    const word_t
        iDeep = rootH - get_lowest_bit_id(i),
        jDeep = rootH - get_lowest_bit_id(j),
        xDeep = rootH - get_highest_bit_id(i ^ j);
    if (xDeep > get_min(iDeep, jDeep))
        return iDeep < jDeep ? i : j;
    const word_t sh = rootH - xDeep;
    return (i >> sh | word_t(1)) << sh;
}
References get_highest_bit_id(), get_lowest_bit_id(), and get_min().
Referenced by uxn::patl::lca_oracle< SuffixCont >::operator()().
get_highest_bit()
word_t uxn::patl::impl::get_highest_bit (word_t x) inline
Definition at line 24 of file trivial.hpp.
{
    return x >> (bits_in_word - 1);
}
References bits_in_word.
Referenced by uxn::patl::maxrep_iterator< Container >::bit31_update(), and uxn::patl::maxrep_iterator< Container >::functor::cond().
get_highest_bit_id()
word_t uxn::patl::impl::get_highest_bit_id (word_t x) inline
Definition at line 71 of file trivial.hpp.
{
    PATL_ASSERT(x);
#ifdef PATL_INTRINSIC
    unsigned long r;
#ifdef PATL_64
    _BitScanReverse64(&r, x);
#endif // PATL_64
#ifdef PATL_32
    _BitScanReverse(&r, x);
#endif // PATL_32
#else // PATL_INTRINSIC
    word_t r = 0;
#ifdef PATL_64
    if (x & 0xFFFFFFFF00000000) { x >>= 32; r += 32; }
#endif // PATL_64
    if (x & 0xFFFF0000) { x >>= 16; r += 16; }
    if (x & 0x0000FF00) { x >>= 8; r += 8; }
    if (x & 0x000000F0) { x >>= 4; r += 4; }
    if (x & 0x0000000C) { x >>= 2; r += 2; }
    if (x & 0x00000002) ++r;
#endif // PATL_INTRINSIC
    return r;
}
References PATL_ASSERT.
Referenced by bit_mismatch_scalar(), get_binary_lca(), uxn::patl::lca_oracle< SuffixCont >::init(), lz_compress(), lz_decompress(), and uxn::patl::lca_oracle< SuffixCont >::operator()().
get_lowest_bit_id()
word_t uxn::patl::impl::get_lowest_bit_id (word_t x) inline
Definition at line 34 of file trivial.hpp.
{
    PATL_ASSERT(x);
#ifdef PATL_INTRINSIC
    unsigned long r;
#ifdef PATL_64
    _BitScanForward64(&r, x);
#endif // PATL_64
#ifdef PATL_32
    _BitScanForward(&r, x);
#endif // PATL_32
#else // PATL_INTRINSIC
    word_t r = 0;
    x &= word_t(0) - x; // isolate lowest bit
#ifdef PATL_64
    if (x & 0xFFFFFFFF00000000) r += 32;
    if (x & 0xFFFF0000FFFF0000) r += 16;
    if (x & 0xFF00FF00FF00FF00) r += 8;
    if (x & 0xF0F0F0F0F0F0F0F0) r += 4;
    if (x & 0xCCCCCCCCCCCCCCCC) r += 2;
    if (x & 0xAAAAAAAAAAAAAAAA) ++r;
#endif // PATL_64
#ifdef PATL_32
    if (x & 0xFFFF0000) r += 16;
    if (x & 0xFF00FF00) r += 8;
    if (x & 0xF0F0F0F0) r += 4;
    if (x & 0xCCCCCCCC) r += 2;
    if (x & 0xAAAAAAAA) ++r;
#endif // PATL_32
#endif // PATL_INTRINSIC
    return r;
}
References PATL_ASSERT.
Referenced by uxn::patl::impl::primes< Natural >::for(), get_binary_lca(), uxn::patl::impl::lca_base< Oracle >::height(), and uxn::patl::lca_oracle< SuffixCont >::operator()().
get_max()
template<typename T > T uxn::patl::impl::get_max (T a, T b) inline
Definition at line 107 of file trivial.hpp.
{
    return a < b ? b : a;
}
get_min()
template<typename T > T uxn::patl::impl::get_min (T a, T b) inline
Definition at line 101 of file trivial.hpp.
{
    return b < a ? b : a;
}
Referenced by uxn::patl::aux::file_mapping_input::create_view(), uxn::patl::impl::primes< Natural >::for(), get_binary_lca(), uxn::patl::get_lce(), main(), uxn::patl::impl::algorithm_generic< T, This, Container, 0 >::mismatch(), multiple_common_substring(), uxn::patl::levenshtein_distance< Container, SameLength >::transitions(), and uxn::patl::levenshtein_tp_distance< Container, SameLength >::transitions().
graphviz_printable_string()
std::string uxn::patl::impl::graphviz_printable_string (const char * p, word_t l) inline
Definition at line 16 of file patricia_dot_base.hpp.
{
    std::string s(l, ' ');
    for (word_t i = 0; i != l; ++i)
        s[i] = !p[i] || p[i] < 0 ? ' ' : p[i];
    return s;
}
Referenced by patricia_dot_base< Cont, OutStream >::out_node(), and uxn::patl::impl::patricia_dot_base< suffix_set< Type, N, Delta, BitComp, Allocator >, OutStream >::out_node().
max0()
word_t uxn::patl::impl::max0 (sword_t x) inline
Definition at line 140 of file trivial.hpp.
{
    return static_cast<word_t>(x & ~(x >> (bits_in_word - 1)));
}
References bits_in_word.
Referenced by uxn::patl::impl::trie_generic< T, N >::insert(), lz_compress(), multiple_common_substring(), uxn::patl::impl::suffix_generic< T >::match_iterator::operator++(), patricia_dot_base< Cont, OutStream >::out_node(), uxn::patl::impl::patricia_dot_base< suffix_set< Type, N, Delta, BitComp, Allocator >, OutStream >::out_node(), uxn::patl::impl::const_partimator_generic< PreorderIter, Decision >::prove_branch(), and uxn::patl::impl::suffix_generic< T >::push_back_generic().
operator!=()
template<typename T , word_t N> bool uxn::patl::impl::operator!= (const trie_generic< T, N > & a, const trie_generic< T, N > & b) inline
Definition at line 675 of file trie_generic.hpp.
{
    return !(a == b);
}
operator==()
template<typename T , word_t N> bool uxn::patl::impl::operator== (const trie_generic< T, N > & a, const trie_generic< T, N > & b) inline
Definition at line 669 of file trie_generic.hpp.
{
    return a.size() == b.size() && std::equal(a.begin(), a.end(), b.begin());
}
sqrt_int()
template<typename Natural > Natural uxn::patl::impl::sqrt_int (Natural x) inline
Definition at line 22 of file primes.hpp.
{ return static_cast<Natural>(sqrt(static_cast<double>(x))); }
Referenced by uxn::patl::impl::primes< Natural >::for().
unsigned_cast() [1/2]
template<typename Source > word_t uxn::patl::impl::unsigned_cast (Source val) inline
Definition at line 146 of file trivial.hpp.
{
    return static_cast<word_t>(static_cast<typename std::make_unsigned<Source>::type>(val));
}
Referenced by bit_mismatch_scalar(), uxn::patl::bit_comparator< T, 0 >::get_bit(), uxn::patl::bit_comparator< T, 8 >::get_bits(), and lz_compress().
unsigned_cast() [2/2]
word_t uxn::patl::impl::unsigned_cast (word_t val) inline
Definition at line 151 of file trivial.hpp.
{
    return val;
}