PATL: uxn::patl::patricia_dot_creator< Cont, OutStream, Base > Class Template Reference
uxn::patl::patricia_dot_creator< Cont, OutStream, Base > Class Template Reference
#include <patricia_dot_creator.hpp>
Public Member Functions
patricia_dot_creator (OutStream &out=std::cout, const Base &base=Base(), word_t dpi=96)
~patricia_dot_creator ()
void create (const const_vertex &vtx, bool clustering=false) const
Private Types
typedef Cont cont_type
typedef patricia_dot_creator< cont_type, OutStream, Base > this_t
typedef cont_type::const_vertex const_vertex
typedef cont_type::vertex vertex
typedef cont_type::const_preorder_iterator const_preorder_iterator
typedef cont_type::preorder_iterator preorder_iterator
typedef cont_type::bit_compare bit_compare
typedef cont_type::prefix prefix
typedef cont_type::key_type key_type
Private Member Functions
patricia_dot_creator & operator= (const patricia_dot_creator &)
void out_node (const const_vertex &vtx) const
void out_edge (const const_vertex &vtx) const
void out_cluster (word_t &n, const prefix &root) const
Private Attributes
OutStream & out_
Base base_
Static Private Attributes
static const word_t bit_size = bit_compare::bit_size
Detailed Description
template<typename Cont, typename OutStream = std::ostream, typename Base = impl::patricia_dot_base<Cont, OutStream>>
class uxn::patl::patricia_dot_creator< Cont, OutStream, Base >
Definition at line 22 of file patricia_dot_creator.hpp.
Member Typedef Documentation
bit_compare
template<typename Cont , typename OutStream = std::ostream, typename Base = impl::patricia_dot_base<Cont, OutStream>> typedef cont_type::bit_compare uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::bit_compare private
Definition at line 32 of file patricia_dot_creator.hpp.
const_preorder_iterator
template<typename Cont , typename OutStream = std::ostream, typename Base = impl::patricia_dot_base<Cont, OutStream>> typedef cont_type::const_preorder_iterator uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::const_preorder_iterator private
Definition at line 30 of file patricia_dot_creator.hpp.
const_vertex
template<typename Cont , typename OutStream = std::ostream, typename Base = impl::patricia_dot_base<Cont, OutStream>> typedef cont_type::const_vertex uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::const_vertex private
Definition at line 28 of file patricia_dot_creator.hpp.
cont_type
template<typename Cont , typename OutStream = std::ostream, typename Base = impl::patricia_dot_base<Cont, OutStream>> typedef Cont uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::cont_type private
Definition at line 26 of file patricia_dot_creator.hpp.
key_type
template<typename Cont , typename OutStream = std::ostream, typename Base = impl::patricia_dot_base<Cont, OutStream>> typedef cont_type::key_type uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::key_type private
Definition at line 34 of file patricia_dot_creator.hpp.
prefix
template<typename Cont , typename OutStream = std::ostream, typename Base = impl::patricia_dot_base<Cont, OutStream>> typedef cont_type::prefix uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::prefix private
Definition at line 33 of file patricia_dot_creator.hpp.
preorder_iterator
template<typename Cont , typename OutStream = std::ostream, typename Base = impl::patricia_dot_base<Cont, OutStream>> typedef cont_type::preorder_iterator uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::preorder_iterator private
Definition at line 31 of file patricia_dot_creator.hpp.
this_t
template<typename Cont , typename OutStream = std::ostream, typename Base = impl::patricia_dot_base<Cont, OutStream>> typedef patricia_dot_creator<cont_type, OutStream, Base> uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::this_t private
Definition at line 27 of file patricia_dot_creator.hpp.
vertex
template<typename Cont , typename OutStream = std::ostream, typename Base = impl::patricia_dot_base<Cont, OutStream>> typedef cont_type::vertex uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::vertex private
Definition at line 29 of file patricia_dot_creator.hpp.
Constructor & Destructor Documentation
patricia_dot_creator()
template<typename Cont , typename OutStream = std::ostream, typename Base = impl::patricia_dot_base<Cont, OutStream>> uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::patricia_dot_creator (OutStream & out = std::cout, const Base & base = Base(), word_t dpi = 96) inline
Definition at line 39 of file patricia_dot_creator.hpp.
        : out_(out)
        , base_(base)
    {
        out_ << "strict digraph\n";
        out_ << "{\n";
        out_ << "// common props\n";
        out_ << "dpi = " << dpi << "\n";
        out_ << "edge[arrowhead = empty]\n";
    }
References uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::out_.
~patricia_dot_creator()
template<typename Cont , typename OutStream = std::ostream, typename Base = impl::patricia_dot_base<Cont, OutStream>> uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::~patricia_dot_creator () inline
Definition at line 50 of file patricia_dot_creator.hpp.
    {
        out_ << "}\n";
    }
References uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::out_.
Member Function Documentation
create()
template<typename Cont , typename OutStream = std::ostream, typename Base = impl::patricia_dot_base<Cont, OutStream>> void uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::create (const const_vertex & vtx, bool clustering = false) const inline
Definition at line 55 of file patricia_dot_creator.hpp.
    {
        out_ << "\n// BEGIN create from vertex\n";
        out_ << "\n// node definitions (preorder depth-first)\n";
        const word_t
            init_id = vtx.get_qid(),
            sibl_qtag = vtx.sibling().get_qtag();
        out_ << "sibling[shape = plaintext, label = "
            << (vtx.skip() == ~word_t(0) ? "\"nil\"" : "\"...\"")
            << "]\n";
        const const_preorder_iterator pit_end(vtx.preorder_end());
        for (const_preorder_iterator pit(vtx.preorder_begin()); pit != pit_end; ++pit)
            if (init_id == pit->get_qid())
                out_node(*pit);
        //
        out_ << std::hex;
        //
        out_ << "\n// root link to sibling\n";
        out_ << 'n' << vtx.node_q_uid() << "->sibling[tailport = "
            << (init_id ? "sw" : "se") << ", headport = "
            << (sibl_qtag ? (init_id ? "se" : "sw") : (init_id ? "ne" : "nw")) << ", style = "
            << (sibl_qtag ? "dotted" : "solid") << "]\n";
        out_ << "\n// forward left links\n";
        out_ << "edge[tailport = sw, weight = 2]\n";
        for (const_preorder_iterator pit(vtx.preorder_begin()); pit != pit_end; ++pit)
        {
            if (!pit->get_qtag() && !pit->get_qid())
                out_edge(*pit);
        }
        out_ << "\n// forward right links\n";
        out_ << "edge[tailport = se]\n";
        for (const_preorder_iterator pit(vtx.preorder_begin()); pit != pit_end; ++pit)
        {
            if (!pit->get_qtag() && pit->get_qid())
                out_edge(*pit);
        }
        out_ << "\n// backward left links\n";
        out_ << "edge[style = dotted, tailport = sw, weight = 1]\n";
        for (const_preorder_iterator pit(vtx.preorder_begin()); pit != pit_end; ++pit)
        {
            if (pit->get_qtag() && !pit->get_qid())
                out_edge(*pit);
        }
        out_ << "\n// backward right links\n";
        out_ << "edge[tailport = se]\n";
        for (const_preorder_iterator pit(vtx.preorder_begin()); pit != pit_end; ++pit)
        {
            if (pit->get_qtag() && pit->get_qid())
                out_edge(*pit);
        }
        if (clustering)
        {
            out_ << "\n// clustering nodes by symbols (recursive levelorder traversal)\n";
            word_t n = 0;
            out_cluster(n, vtx.get_prefix());
        }
        out_ << "\n// END create from vertex\n";
    }
References uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::out_, uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::out_cluster(), uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::out_edge(), and uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::out_node().
Referenced by main().
operator=()
template<typename Cont , typename OutStream = std::ostream, typename Base = impl::patricia_dot_base<Cont, OutStream>> patricia_dot_creator & uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::operator= (const patricia_dot_creator< Cont, OutStream, Base > &) private
out_cluster()
template<typename Cont , typename OutStream = std::ostream, typename Base = impl::patricia_dot_base<Cont, OutStream>> void uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::out_cluster (word_t & n, const prefix & root) const inline private
Definition at line 129 of file patricia_dot_creator.hpp.
    {
        const bool clustp =
            (!root.get_xtag(0) && !root.symbol_limit(0)) ||
            (!root.get_xtag(1) && !root.symbol_limit(1));
        if (clustp)
            out_ << "subgraph cluster_" << n++ << "\n"
                << "{ style = \"dashed, rounded, setlinewidth(0.2)\"; ";
        std::vector<prefix> children;
        for (prefix cur(root); ; )
        {
            if (!cur.get_xtag(0) && cur.symbol_limit(0))
            {
                prefix pref(cur);
                pref.go_xlink(0);
                children.push_back(pref);
            }
            if (!cur.get_xtag(1) && cur.symbol_limit(1))
            {
                prefix pref(cur);
                pref.go_xlink(1);
                children.push_back(pref);
            }
            if (clustp)
            {
                if (root != cur)
                    out_ << "; ";
                out_ << 'n' << cur.node_uid();
            }
            //
            if (!cur.get_xtag(0) && !cur.symbol_limit(0))
                cur.go_xlink(0);
            else if (!cur.get_xtag(1) && !cur.symbol_limit(1))
                cur.go_xlink(1);
            else
            {
                if (cur == root)
                    break;
                for (;;)
                {
                    word_t parent_id;
                    do
                    {
                        parent_id = cur.get_parent_id();
                        cur.go_parent();
                    } while (cur != root && parent_id);
                    if (cur == root)
                        break;
                    if (!cur.get_xtag(1) && !cur.symbol_limit(1))
                    {
                        cur.go_xlink(1);
                        break;
                    }
                }
                if (cur == root)
                    break;
            }
        }
        if (clustp)
            out_ << " }\n";
        //
        for (word_t i = 0; i != children.size(); ++i)
            out_cluster(n, children[i]);
    }
References uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::out_, and uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::out_cluster().
Referenced by uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::create(), and uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::out_cluster().
out_edge()
template<typename Cont , typename OutStream = std::ostream, typename Base = impl::patricia_dot_base<Cont, OutStream>> void uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::out_edge (const const_vertex & vtx) const inline private
Definition at line 122 of file patricia_dot_creator.hpp.
    {
        out_ << 'n' << vtx.node_q_uid() << "->" << 'n' << vtx.node_p_uid();
        base_.out_edge(out_, vtx);
        out_ << '\n';
    }
References uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::base_, and uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::out_.
Referenced by uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::create().
out_node()
template<typename Cont , typename OutStream = std::ostream, typename Base = impl::patricia_dot_base<Cont, OutStream>> void uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::out_node (const const_vertex & vtx) const inline private
Definition at line 115 of file patricia_dot_creator.hpp.
    {
        out_ << 'n' << std::hex << vtx.node_q_uid() << std::dec;
        base_.out_node(out_, vtx);
        out_ << '\n';
    }
References uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::base_, and uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::out_.
Referenced by uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::create().
Member Data Documentation
base_
template<typename Cont , typename OutStream = std::ostream, typename Base = impl::patricia_dot_base<Cont, OutStream>> Base uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::base_ private
Definition at line 195 of file patricia_dot_creator.hpp.
Referenced by uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::out_edge(), and uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::out_node().
bit_size
template<typename Cont , typename OutStream = std::ostream, typename Base = impl::patricia_dot_base<Cont, OutStream>> const word_t uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::bit_size = bit_compare::bit_size static private
Definition at line 36 of file patricia_dot_creator.hpp.
out_
template<typename Cont , typename OutStream = std::ostream, typename Base = impl::patricia_dot_base<Cont, OutStream>> OutStream& uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::out_ private
Definition at line 194 of file patricia_dot_creator.hpp.
Referenced by uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::create(), uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::out_cluster(), uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::out_edge(), uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::out_node(), uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::patricia_dot_creator(), and uxn::patl::patricia_dot_creator< Cont, OutStream, Base >::~patricia_dot_creator().
The documentation for this class was generated from the following file:
uxn/patl/patricia_dot_creator.hpp