PATL: uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc > Class Template Reference
uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc > Class Template Reference
#include <unordered.hpp>
Classes
class iterator
Public Types
typedef Key key_type
typedef std::pair< const key_type, mapped_type > value_type
typedef impl::hash_node< key_type, value_type > node_type
typedef HashFun hasher
typedef Pred key_equal
typedef Alloc allocator_type
typedef word_t size_type
Public Member Functions
unordered_map (word_t capacity=0, const hasher &hf=hasher(), const key_equal &eql=key_equal(), const allocator_type &alloc=allocator_type())
bool empty () const
word_t size () const
void clear ()
mapped_type & operator[] (const key_type &key)
size_type erase (const key_type &key)
Private Types
typedef Datum mapped_type
Private Member Functions
void init (word_t capacity)
void resize ()
Private Attributes
hasher hf_
key_equal eql_
allocator_type alloc_
std::vector< sword_t > buckets_
word_t size_
std::vector< node_type > nodes_
word_t free_size_
word_t free_list_
Detailed Description
template<typename Key, typename Datum, typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >>
class uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >
Definition at line 97 of file unordered.hpp.
Member Typedef Documentation
allocator_type
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> typedef Alloc uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::allocator_type
Definition at line 107 of file unordered.hpp.
hasher
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> typedef HashFun uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::hasher
Definition at line 105 of file unordered.hpp.
key_equal
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> typedef Pred uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::key_equal
Definition at line 106 of file unordered.hpp.
key_type
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> typedef Key uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::key_type
Definition at line 102 of file unordered.hpp.
mapped_type
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> typedef Datum uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::mapped_type private
Definition at line 99 of file unordered.hpp.
node_type
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> typedef impl::hash_node<key_type, value_type> uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::node_type
Definition at line 104 of file unordered.hpp.
size_type
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> typedef word_t uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::size_type
Definition at line 108 of file unordered.hpp.
value_type
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> typedef std::pair<const key_type, mapped_type> uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::value_type
Definition at line 103 of file unordered.hpp.
Constructor & Destructor Documentation
unordered_map()
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::unordered_map (word_t capacity = 0, const hasher & hf = hasher(), const key_equal & eql = key_equal(), const allocator_type & alloc = allocator_type()) inline explicit
Definition at line 110 of file unordered.hpp.
        : hf_(hf)
        , eql_(eql)
        , alloc_(alloc)
        , size_(0)
        , free_size_(0)
    {
        init(capacity);
    }
References uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::init().
Member Function Documentation
clear()
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> void uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::clear () inline
Definition at line 134 of file unordered.hpp.
    {
        if (size_)
        {
            std::fill(buckets_.begin(), buckets_.end(), ~word_t(0));
            std::fill(nodes_.begin(), nodes_.end(), node_type()); // ???
            free_list_ = ~word_t(0);
            free_size_ = size_ = 0;
        }
    }
References uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::buckets_, uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::free_list_, uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::free_size_, uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::nodes_, and uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::size_.
empty()
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> bool uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::empty () const inline
Definition at line 124 of file unordered.hpp.
    {
        return !size();
    }
References uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::size().
erase()
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> size_type uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::erase (const key_type & key) inline
Definition at line 176 of file unordered.hpp.
    {
        if (!buckets_.empty())
        {
            const word_t num = hf_(key) & 0x7FFFFFFF;
            word_t index = num % buckets_.size();
            word_t num3 = ~word_t(0);
            for (word_t i = buckets_[index]; i != ~word_t(0); i = nodes_[i].get_next())
            {
                if (nodes_[i].get_hash() == num && eql_(nodes_[i].get_key(), key))
                {
                    if (num3 == ~word_t(0))
                        buckets_[index] = nodes_[i].get_next();
                    else
                        nodes_[num3].set_next(nodes_[i].get_next());
                    nodes_[i].set_all(~word_t(0), free_list_, value_type());
                    free_list_ = i;
                    ++free_size_;
                    return 1;
                }
                num3 = i;
            }
        }
        return 0;
    }
References uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::buckets_, uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::eql_, uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::free_list_, uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::free_size_, uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::hf_, and uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::nodes_.
init()
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> void uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::init (word_t capacity) inline private
Definition at line 215 of file unordered.hpp.
    {
        impl::primes<word_t> ps(capacity);
        ps.next();
        const word_t prime = ps.value();
        buckets_.resize(prime, ~word_t(0));
        nodes_.resize(prime);
        free_list_ = ~word_t(0);
    }
References uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::buckets_, uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::free_list_, uxn::patl::impl::generator_base< Derived, Elem >::next(), uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::nodes_, and uxn::patl::impl::generator_base< Derived, Elem >::value().
Referenced by uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::operator[](), and uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::unordered_map().
operator[]()
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> mapped_type & uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::operator[] (const key_type & key) inline
Definition at line 145 of file unordered.hpp.
    {
        if (buckets_.empty())
            init(0);
        const word_t num = hf_(key) & 0x7FFFFFFF;
        word_t index = num % buckets_.size();
        for (word_t i = buckets_[index]; i != ~word_t(0); i = nodes_[i].get_next())
        {
            if (nodes_[i].get_hash() == num && eql_(nodes_[i].get_key(), key))
                return nodes_[i].get_value().second;
        }
        word_t free_list;
        if (free_size_ > 0)
        {
            free_list = free_list_;
            free_list_ = nodes_[free_list].get_next();
            --free_size_;
        }
        else
        {
            if (size_ == nodes_.size())
            {
                resize();
                index = num % buckets_.size();
            }
            free_list = size_++;
        }
        nodes_[free_list].set_all(num, buckets_[index], std::make_pair(key, mapped_type()));
        return nodes_[free_list].get_value().second;
    }
References uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::buckets_, uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::eql_, uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::free_list_, uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::free_size_, uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::hf_, uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::init(), uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::nodes_, uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::resize(), and uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::size_.
resize()
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> void uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::resize () inline private
Definition at line 225 of file unordered.hpp.
    {
        impl::primes<word_t> ps(size_ * 2);
        ps.next();
        const word_t prime = ps.value();
        std::vector<word_t> num_arr(prime, ~word_t(0));
        std::vector<node_type> dest_arr(prime);
        std::copy(nodes_.begin(), nodes_.begin() + size_, dest_arr);
        for (word_t j = 0; j != size_; ++j)
        {
            const word_t index = dest_arr[j].get_hash() % prime;
            dest_arr[j].set_next(num_arr[index]);
            num_arr[index] = j;
        }
        std::swap(buckets_, num_arr);
        std::swap(nodes_, dest_arr);
    }
References uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::buckets_, uxn::patl::impl::generator_base< Derived, Elem >::next(), uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::nodes_, uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::size_, uxn::patl::swap(), and uxn::patl::impl::generator_base< Derived, Elem >::value().
Referenced by uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::operator[]().
size()
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> word_t uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::size () const inline
Definition at line 129 of file unordered.hpp.
    {
        return size_ - free_size_;
    }
References uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::free_size_, and uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::size_.
Referenced by uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::empty().
Member Data Documentation
alloc_
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> allocator_type uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::alloc_ private
Definition at line 245 of file unordered.hpp.
buckets_
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> std::vector<sword_t> uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::buckets_ private
Definition at line 246 of file unordered.hpp.
Referenced by uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::clear(), uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::erase(), uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::init(), uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::operator[](), and uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::resize().
eql_
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> key_equal uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::eql_ private
Definition at line 244 of file unordered.hpp.
Referenced by uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::erase(), and uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::operator[]().
free_list_
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> word_t uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::free_list_ private
Definition at line 250 of file unordered.hpp.
Referenced by uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::clear(), uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::erase(), uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::init(), and uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::operator[]().
free_size_
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> word_t uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::free_size_ private
Definition at line 249 of file unordered.hpp.
Referenced by uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::clear(), uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::erase(), uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::operator[](), and uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::size().
hf_
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> hasher uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::hf_ private
Definition at line 243 of file unordered.hpp.
Referenced by uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::erase(), and uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::operator[]().
nodes_
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> std::vector<node_type> uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::nodes_ private
Definition at line 248 of file unordered.hpp.
Referenced by uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::clear(), uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::erase(), uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::init(), uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::operator[](), and uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::resize().
size_
template<typename Key , typename Datum , typename HashFun = hash<Key>, typename Pred = std::equal_to<Key>, typename Alloc = std::allocator<std::pair<const Key, Datum> >> word_t uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::size_ private
Definition at line 247 of file unordered.hpp.
Referenced by uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::clear(), uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::operator[](), uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::resize(), and uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::size().
The documentation for this class was generated from the following file:
uxn/patl/unordered.hpp