PATL: uxn::patl::impl::patricia_dot_base< suffix_set< Type, N, Delta, BitComp, Allocator >, OutStream > Class Template Reference
uxn::patl::impl::patricia_dot_base< suffix_set< Type, N, Delta, BitComp, Allocator >, OutStream > Class Template Reference
#include <patricia_dot_base.hpp>
Public Types
typedef suffix_set< Type, N, Delta, BitComp, Allocator > cont_type
typedef cont_type::vertex vertex
typedef cont_type::bit_compare bit_compare
Static Public Member Functions
static void out_node (OutStream &out, const vertex &vtx)
static void out_edge (OutStream &, const vertex &)
Static Public Attributes
static const word_t bit_size = bit_compare::bit_size
Detailed Description
template<typename Type, word_t N, word_t Delta, typename BitComp, typename Allocator, typename OutStream>
class uxn::patl::impl::patricia_dot_base< suffix_set< Type, N, Delta, BitComp, Allocator >, OutStream >
Definition at line 48 of file patricia_dot_base.hpp.
Member Typedef Documentation
bit_compare
template<typename Type , word_t N, word_t Delta, typename BitComp , typename Allocator , typename OutStream > typedef cont_type::bit_compare uxn::patl::impl::patricia_dot_base< suffix_set< Type, N, Delta, BitComp, Allocator >, OutStream >::bit_compare
Definition at line 53 of file patricia_dot_base.hpp.
cont_type
template<typename Type , word_t N, word_t Delta, typename BitComp , typename Allocator , typename OutStream > typedef suffix_set<Type, N, Delta, BitComp, Allocator> uxn::patl::impl::patricia_dot_base< suffix_set< Type, N, Delta, BitComp, Allocator >, OutStream >::cont_type
Definition at line 51 of file patricia_dot_base.hpp.
vertex
template<typename Type , word_t N, word_t Delta, typename BitComp , typename Allocator , typename OutStream > typedef cont_type::vertex uxn::patl::impl::patricia_dot_base< suffix_set< Type, N, Delta, BitComp, Allocator >, OutStream >::vertex
Definition at line 52 of file patricia_dot_base.hpp.
Member Function Documentation
out_edge()
template<typename Type , word_t N, word_t Delta, typename BitComp , typename Allocator , typename OutStream > static void uxn::patl::impl::patricia_dot_base< suffix_set< Type, N, Delta, BitComp, Allocator >, OutStream >::out_edge (OutStream & , const vertex &) inline static
Definition at line 67 of file patricia_dot_base.hpp.
    {
    }
out_node()
template<typename Type , word_t N, word_t Delta, typename BitComp , typename Allocator , typename OutStream > static void uxn::patl::impl::patricia_dot_base< suffix_set< Type, N, Delta, BitComp, Allocator >, OutStream >::out_node (OutStream & out, const vertex & vtx) inline static
Definition at line 57 of file patricia_dot_base.hpp.
    {
        out << "[label = \""
            << vtx.parent_key() - vtx.cont()->keys() << ": '"
            << graphviz_printable_string(vtx.parent_key(), align_up<bit_size>(max0(vtx.skip())) / bit_size)
            << "'\\n"
            << static_cast<sword_t>(vtx.skip())
            << "\"]\n";
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::cont(), uxn::patl::impl::graphviz_printable_string(), uxn::patl::impl::max0(), uxn::patl::impl::const_vertex_generic< Algorithm >::parent_key(), and uxn::patl::impl::const_vertex_generic< Algorithm >::skip().
Member Data Documentation
bit_size
template<typename Type , word_t N, word_t Delta, typename BitComp , typename Allocator , typename OutStream > const word_t uxn::patl::impl::patricia_dot_base< suffix_set< Type, N, Delta, BitComp, Allocator >, OutStream >::bit_size = bit_compare::bit_size static
Definition at line 55 of file patricia_dot_base.hpp.
The documentation for this class was generated from the following file:
uxn/patl/impl/patricia_dot_base.hpp