PATL: uxn::patl::impl::const_vertex_generic< Algorithm > Class Template Reference
uxn::patl::impl::const_vertex_generic< Algorithm > Class Template Reference
#include <vertex.hpp>
Public Types
typedef this_t const_vertex
typedef algorithm::cont_type cont_type
typedef algorithm::key_type key_type
typedef algorithm::const_key_reference const_key_reference
typedef algorithm::value_type value_type
Public Member Functions
const_vertex_generic (const algorithm &pal=algorithm())
const_vertex_generic (const cont_type *cont, const node_type *q, word_t qid)
const_vertex_generic (const cont_type *cont, word_t qq)
bool operator== (const this_t &r) const
bool operator!= (const this_t &r) const
bool operator< (const this_t &r) const
operator const algorithm & () const
prefix get_prefix () const
word_t compact () const
word_t node_q_uid () const
word_t node_p_uid () const
const_iterator begin () const
const_iterator end () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
const_postorder_iterator postorder_begin () const
const_postorder_iterator postorder_end () const
const_preorder_iterator preorder_begin () const
const_preorder_iterator preorder_begin (word_t limit) const
const_preorder_iterator preorder_end () const
bool the_end () const
const_key_reference key () const
const_key_reference parent_key () const
word_t prefix_length () const
const value_type & value () const
const value_type & parent_value () const
word_t skip () const
word_t next_skip () const
only for !leaf()
this_t sibling () const
bool limited (word_t limit) const
template<word_t Side>
void descend ()
trie descend to the leaves
template<word_t Side, typename Callback >
void descend (Callback &cb)
template<word_t Side>
void descend (word_t limit)
trie descend to the leaves limited by
template<word_t Side, typename Callback >
void descend (word_t limit, Callback &cb)
template<word_t Side>
void move_subtree ()
generic part of all move functions
template<word_t Side, typename Callback >
void move_subtree (Callback &cb)
template<word_t Side>
void move ()
move to the next leaf
word_t mismatch (const key_type &key, word_t prefixLen=~word_t(0))
word_t get_qid () const
word_t get_qtag () const
word_t get_parent_id () const
void toggle ()
void iterate (word_t id)
void ascend ()
void ascend (sword_t prefixLen)
void ascend_less (sword_t prefixLen)
const cont_type * cont () const
bit_compare bit_comp () const
Protected Types
typedef const_vertex_generic< Algorithm > this_t
typedef Algorithm algorithm
typedef algorithm::node_type node_type
typedef cont_type::bit_compare bit_compare
typedef cont_type::prefix prefix
typedef cont_type::const_preorder_iterator const_preorder_iterator
typedef cont_type::const_postorder_iterator const_postorder_iterator
typedef cont_type::preorder_iterator preorder_iterator
typedef cont_type::postorder_iterator postorder_iterator
typedef cont_type::const_iterator const_iterator
typedef cont_type::iterator iterator
typedef cont_type::const_reverse_iterator const_reverse_iterator
typedef cont_type::reverse_iterator reverse_iterator
Protected Attributes
algorithm pal_
Detailed Description
template<typename Algorithm>
class uxn::patl::impl::const_vertex_generic< Algorithm >
Definition at line 17 of file vertex.hpp.
Member Typedef Documentation
algorithm
template<typename Algorithm > typedef Algorithm uxn::patl::impl::const_vertex_generic< Algorithm >::algorithm protected
Definition at line 21 of file vertex.hpp.
bit_compare
template<typename Algorithm > typedef cont_type::bit_compare uxn::patl::impl::const_vertex_generic< Algorithm >::bit_compare protected
Definition at line 29 of file vertex.hpp.
const_iterator
template<typename Algorithm > typedef cont_type::const_iterator uxn::patl::impl::const_vertex_generic< Algorithm >::const_iterator protected
Definition at line 35 of file vertex.hpp.
const_key_reference
template<typename Algorithm > typedef algorithm::const_key_reference uxn::patl::impl::const_vertex_generic< Algorithm >::const_key_reference
Definition at line 42 of file vertex.hpp.
const_postorder_iterator
template<typename Algorithm > typedef cont_type::const_postorder_iterator uxn::patl::impl::const_vertex_generic< Algorithm >::const_postorder_iterator protected
Definition at line 32 of file vertex.hpp.
const_preorder_iterator
template<typename Algorithm > typedef cont_type::const_preorder_iterator uxn::patl::impl::const_vertex_generic< Algorithm >::const_preorder_iterator protected
Definition at line 31 of file vertex.hpp.
const_reverse_iterator
template<typename Algorithm > typedef cont_type::const_reverse_iterator uxn::patl::impl::const_vertex_generic< Algorithm >::const_reverse_iterator protected
Definition at line 37 of file vertex.hpp.
const_vertex
template<typename Algorithm > typedef this_t uxn::patl::impl::const_vertex_generic< Algorithm >::const_vertex
Definition at line 24 of file vertex.hpp.
cont_type
template<typename Algorithm > typedef algorithm::cont_type uxn::patl::impl::const_vertex_generic< Algorithm >::cont_type
Definition at line 25 of file vertex.hpp.
iterator
template<typename Algorithm > typedef cont_type::iterator uxn::patl::impl::const_vertex_generic< Algorithm >::iterator protected
Definition at line 36 of file vertex.hpp.
key_type
template<typename Algorithm > typedef algorithm::key_type uxn::patl::impl::const_vertex_generic< Algorithm >::key_type
Definition at line 41 of file vertex.hpp.
node_type
template<typename Algorithm > typedef algorithm::node_type uxn::patl::impl::const_vertex_generic< Algorithm >::node_type protected
Definition at line 28 of file vertex.hpp.
postorder_iterator
template<typename Algorithm > typedef cont_type::postorder_iterator uxn::patl::impl::const_vertex_generic< Algorithm >::postorder_iterator protected
Definition at line 34 of file vertex.hpp.
prefix
template<typename Algorithm > typedef cont_type::prefix uxn::patl::impl::const_vertex_generic< Algorithm >::prefix protected
Definition at line 30 of file vertex.hpp.
preorder_iterator
template<typename Algorithm > typedef cont_type::preorder_iterator uxn::patl::impl::const_vertex_generic< Algorithm >::preorder_iterator protected
Definition at line 33 of file vertex.hpp.
reverse_iterator
template<typename Algorithm > typedef cont_type::reverse_iterator uxn::patl::impl::const_vertex_generic< Algorithm >::reverse_iterator protected
Definition at line 38 of file vertex.hpp.
this_t
template<typename Algorithm > typedef const_vertex_generic<Algorithm> uxn::patl::impl::const_vertex_generic< Algorithm >::this_t protected
Definition at line 20 of file vertex.hpp.
value_type
template<typename Algorithm > typedef algorithm::value_type uxn::patl::impl::const_vertex_generic< Algorithm >::value_type
Definition at line 43 of file vertex.hpp.
Constructor & Destructor Documentation
const_vertex_generic() [1/3]
template<typename Algorithm > uxn::patl::impl::const_vertex_generic< Algorithm >::const_vertex_generic (const algorithm & pal = algorithm()) inline explicit
Definition at line 45 of file vertex.hpp.
        : pal_(pal)
    {
    }
const_vertex_generic() [2/3]
template<typename Algorithm > uxn::patl::impl::const_vertex_generic< Algorithm >::const_vertex_generic (const cont_type * cont, const node_type * q, word_t qid) inline
Definition at line 50 of file vertex.hpp.
        : pal_(cont, q, qid)
    {
    }
const_vertex_generic() [3/3]
template<typename Algorithm > uxn::patl::impl::const_vertex_generic< Algorithm >::const_vertex_generic (const cont_type * cont, word_t qq) inline
Definition at line 55 of file vertex.hpp.
        : pal_(cont, qq)
    {
    }
Member Function Documentation
ascend() [1/2]
template<typename Algorithm > void uxn::patl::impl::const_vertex_generic< Algorithm >::ascend () inline
Definition at line 316 of file vertex.hpp.
    {
        pal_.ascend();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
Referenced by uxn::patl::impl::const_vertex_generic< Algorithm >::move_subtree(), and uxn::patl::impl::suffix_generic< T >::match_iterator::operator++().
ascend() [2/2]
template<typename Algorithm > void uxn::patl::impl::const_vertex_generic< Algorithm >::ascend (sword_t prefixLen) inline
Definition at line 321 of file vertex.hpp.
    {
        pal_.ascend(prefixLen);
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
ascend_less()
template<typename Algorithm > void uxn::patl::impl::const_vertex_generic< Algorithm >::ascend_less (sword_t prefixLen) inline
Definition at line 326 of file vertex.hpp.
    {
        pal_.ascend_less(prefixLen);
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
begin()
template<typename Algorithm > const_iterator uxn::patl::impl::const_vertex_generic< Algorithm >::begin () const inline
Definition at line 99 of file vertex.hpp.
    {
        return const_iterator(*postorder_begin());
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::postorder_begin().
Referenced by uxn::patl::impl::const_vertex_generic< Algorithm >::rend().
bit_comp()
template<typename Algorithm > bit_compare uxn::patl::impl::const_vertex_generic< Algorithm >::bit_comp () const inline
Definition at line 336 of file vertex.hpp.
    {
        return pal_.bit_comp();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
compact()
template<typename Algorithm > word_t uxn::patl::impl::const_vertex_generic< Algorithm >::compact () const inline
Definition at line 84 of file vertex.hpp.
    {
        return pal_.compact();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
Referenced by uxn::patl::impl::const_vertex_generic< Algorithm >::operator<(), uxn::patl::impl::vertex_generic< Algorithm >::postorder_begin(), uxn::patl::impl::const_vertex_generic< Algorithm >::postorder_begin(), uxn::patl::impl::vertex_generic< Algorithm >::preorder_begin(), and uxn::patl::impl::const_vertex_generic< Algorithm >::preorder_begin().
cont()
template<typename Algorithm > const cont_type * uxn::patl::impl::const_vertex_generic< Algorithm >::cont () const inline
Definition at line 331 of file vertex.hpp.
    {
        return pal_.cont();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
Referenced by uxn::patl::impl::suffix_generic< T >::match_iterator::operator++(), uxn::patl::impl::patricia_dot_base< suffix_set< Type, N, Delta, BitComp, Allocator >, OutStream >::out_node(), uxn::patl::impl::vertex_generic< Algorithm >::preorder_begin(), and uxn::patl::impl::const_vertex_generic< Algorithm >::preorder_begin().
descend() [1/4]
template<typename Algorithm > template<word_t Side> void uxn::patl::impl::const_vertex_generic< Algorithm >::descend () inline
trie descend to the leaves
Definition at line 223 of file vertex.hpp.
    {
        while (!get_qtag())
            iterate(Side);
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::get_qtag(), and uxn::patl::impl::const_vertex_generic< Algorithm >::iterate().
Referenced by uxn::patl::impl::const_vertex_generic< Algorithm >::postorder_begin().
descend() [2/4]
template<typename Algorithm > template<word_t Side, typename Callback > void uxn::patl::impl::const_vertex_generic< Algorithm >::descend (Callback & cb) inline
Definition at line 229 of file vertex.hpp.
    {
        while (!get_qtag())
        {
            cb(this);
            iterate(Side);
        }
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::get_qtag(), and uxn::patl::impl::const_vertex_generic< Algorithm >::iterate().
descend() [3/4]
template<typename Algorithm > template<word_t Side> void uxn::patl::impl::const_vertex_generic< Algorithm >::descend (word_t limit) inline
trie descend to the leaves limited by
Definition at line 240 of file vertex.hpp.
    {
        while (!limited(limit))
            iterate(Side);
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::iterate(), and uxn::patl::impl::const_vertex_generic< Algorithm >::limited().
descend() [4/4]
template<typename Algorithm > template<word_t Side, typename Callback > void uxn::patl::impl::const_vertex_generic< Algorithm >::descend (word_t limit, Callback & cb) inline
Definition at line 246 of file vertex.hpp.
    {
        while (!limited(limit))
        {
            cb(this);
            iterate(Side);
        }
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::iterate(), and uxn::patl::impl::const_vertex_generic< Algorithm >::limited().
end()
template<typename Algorithm > const_iterator uxn::patl::impl::const_vertex_generic< Algorithm >::end () const inline
Definition at line 104 of file vertex.hpp.
    {
        return const_iterator(*postorder_end());
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::postorder_end().
Referenced by uxn::patl::impl::const_vertex_generic< Algorithm >::rbegin().
get_parent_id()
template<typename Algorithm > word_t uxn::patl::impl::const_vertex_generic< Algorithm >::get_parent_id () const inline
Definition at line 301 of file vertex.hpp.
    {
        return pal_.get_q()->get_parent_id();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
get_prefix()
template<typename Algorithm > prefix uxn::patl::impl::const_vertex_generic< Algorithm >::get_prefix () const inline
Definition at line 79 of file vertex.hpp.
    {
        return prefix(pal_.cont(), pal_.get_q());
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
get_qid()
template<typename Algorithm > word_t uxn::patl::impl::const_vertex_generic< Algorithm >::get_qid () const inline
Definition at line 291 of file vertex.hpp.
    {
        return pal_.get_qid();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
Referenced by uxn::patl::impl::const_vertex_generic< Algorithm >::move_subtree(), uxn::patl::impl::vertex_generic< Algorithm >::preorder_begin(), and uxn::patl::impl::const_vertex_generic< Algorithm >::preorder_begin().
get_qtag()
template<typename Algorithm > word_t uxn::patl::impl::const_vertex_generic< Algorithm >::get_qtag () const inline
Definition at line 296 of file vertex.hpp.
    {
        return pal_.get_qtag();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
Referenced by uxn::patl::impl::const_vertex_generic< Algorithm >::descend(), and uxn::patl::impl::const_vertex_generic< Algorithm >::limited().
iterate()
template<typename Algorithm > void uxn::patl::impl::const_vertex_generic< Algorithm >::iterate (word_t id) inline
Definition at line 311 of file vertex.hpp.
    {
        pal_.iterate(id);
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
Referenced by uxn::patl::impl::const_vertex_generic< Algorithm >::descend().
key()
template<typename Algorithm > const_key_reference uxn::patl::impl::const_vertex_generic< Algorithm >::key () const inline
Definition at line 175 of file vertex.hpp.
    {
        return pal_.get_key();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
Referenced by lz_compress(), and uxn::patl::impl::const_vertex_generic< Algorithm >::mismatch().
limited()
template<typename Algorithm > bool uxn::patl::impl::const_vertex_generic< Algorithm >::limited (word_t limit) const inline
Definition at line 216 of file vertex.hpp.
    {
        return get_qtag() || next_skip() >= limit;
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::get_qtag(), and uxn::patl::impl::const_vertex_generic< Algorithm >::next_skip().
Referenced by uxn::patl::impl::const_vertex_generic< Algorithm >::descend().
mismatch()
template<typename Algorithm > word_t uxn::patl::impl::const_vertex_generic< Algorithm >::mismatch (const key_type & key, word_t prefixLen = ~word_t(0)) inline
Definition at line 284 of file vertex.hpp.
    {
        return pal_.mismatch(key, prefixLen);
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::key(), and uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
Referenced by uxn::patl::impl::assoc_generic< This, T, 0 >::equal_range(), uxn::patl::impl::assoc_generic< This, T, 0 >::find(), uxn::patl::impl::assoc_generic< This, T, 0 >::lower_bound(), and uxn::patl::impl::assoc_generic< This, T, 0 >::upper_bound().
move()
template<typename Algorithm > template<word_t Side> void uxn::patl::impl::const_vertex_generic< Algorithm >::move () inline
move to the next leaf
Definition at line 276 of file vertex.hpp.
    {
        move_subtree<Side>();
        descend<word_t(1) ^ Side>();
    }
Referenced by uxn::patl::impl::const_vertex_generic< Algorithm >::postorder_end().
move_subtree() [1/2]
template<typename Algorithm > template<word_t Side> void uxn::patl::impl::const_vertex_generic< Algorithm >::move_subtree () inline
generic part of all move functions
Definition at line 257 of file vertex.hpp.
    {
        while (get_qid() == Side)
            ascend();
        toggle();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::ascend(), uxn::patl::impl::const_vertex_generic< Algorithm >::get_qid(), and uxn::patl::impl::const_vertex_generic< Algorithm >::toggle().
move_subtree() [2/2]
template<typename Algorithm > template<word_t Side, typename Callback > void uxn::patl::impl::const_vertex_generic< Algorithm >::move_subtree (Callback & cb) inline
Definition at line 264 of file vertex.hpp.
    {
        while (get_qid() == Side)
        {
            ascend();
            cb(this);
        }
        toggle();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::ascend(), uxn::patl::impl::const_vertex_generic< Algorithm >::get_qid(), and uxn::patl::impl::const_vertex_generic< Algorithm >::toggle().
next_skip()
template<typename Algorithm > word_t uxn::patl::impl::const_vertex_generic< Algorithm >::next_skip () const inline
only for !leaf()
Definition at line 206 of file vertex.hpp.
    {
        return pal_.get_p()->get_skip();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
Referenced by uxn::patl::impl::const_vertex_generic< Algorithm >::limited().
node_p_uid()
template<typename Algorithm > word_t uxn::patl::impl::const_vertex_generic< Algorithm >::node_p_uid () const inline
Definition at line 94 of file vertex.hpp.
    {
        return reinterpret_cast<word_t>(pal_.get_p());
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
node_q_uid()
template<typename Algorithm > word_t uxn::patl::impl::const_vertex_generic< Algorithm >::node_q_uid () const inline
Definition at line 89 of file vertex.hpp.
    {
        return reinterpret_cast<word_t>(pal_.get_q());
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
operator const algorithm &()
template<typename Algorithm > uxn::patl::impl::const_vertex_generic< Algorithm >::operator const algorithm & () const inline
Definition at line 74 of file vertex.hpp.
    {
        return pal_;
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
operator!=()
template<typename Algorithm > bool uxn::patl::impl::const_vertex_generic< Algorithm >::operator!= (const this_t & r) const inline
Definition at line 64 of file vertex.hpp.
    {
        return !(*this == r);
    }
operator<()
template<typename Algorithm > bool uxn::patl::impl::const_vertex_generic< Algorithm >::operator< (const this_t & r) const inline
Definition at line 69 of file vertex.hpp.
    {
        return compact() < r.compact();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::compact().
operator==()
template<typename Algorithm > bool uxn::patl::impl::const_vertex_generic< Algorithm >::operator== (const this_t & r) const inline
Definition at line 60 of file vertex.hpp.
    {
        return pal_ == r.pal_;
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
parent_key()
template<typename Algorithm > const_key_reference uxn::patl::impl::const_vertex_generic< Algorithm >::parent_key () const inline
Definition at line 180 of file vertex.hpp.
    {
        return pal_.get_key(pal_.get_q());
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
Referenced by uxn::patl::impl::patricia_dot_base< suffix_set< Type, N, Delta, BitComp, Allocator >, OutStream >::out_node().
parent_value()
template<typename Algorithm > const value_type & uxn::patl::impl::const_vertex_generic< Algorithm >::parent_value () const inline
Definition at line 195 of file vertex.hpp.
    {
        return pal_.get_value(pal_.get_q());
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
postorder_begin()
template<typename Algorithm > const_postorder_iterator uxn::patl::impl::const_vertex_generic< Algorithm >::postorder_begin () const inline
Definition at line 119 of file vertex.hpp.
    {
        this_t vtx(*this);
        if (compact())
            vtx.descend<0>();
        else
            vtx.toggle();
        return const_postorder_iterator(vtx);
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::compact(), uxn::patl::impl::const_vertex_generic< Algorithm >::descend(), and uxn::patl::impl::const_vertex_generic< Algorithm >::toggle().
Referenced by uxn::patl::impl::const_vertex_generic< Algorithm >::begin().
postorder_end()
template<typename Algorithm > const_postorder_iterator uxn::patl::impl::const_vertex_generic< Algorithm >::postorder_end () const inline
Definition at line 129 of file vertex.hpp.
    {
        this_t vtx(*this);
        if (pal_.get_q())
            vtx.move<1>();
        else
            vtx.toggle();
        return const_postorder_iterator(vtx);
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::move(), uxn::patl::impl::const_vertex_generic< Algorithm >::pal_, and uxn::patl::impl::const_vertex_generic< Algorithm >::toggle().
Referenced by uxn::patl::impl::const_vertex_generic< Algorithm >::end().
prefix_length()
template<typename Algorithm > word_t uxn::patl::impl::const_vertex_generic< Algorithm >::prefix_length () const inline
Definition at line 185 of file vertex.hpp.
    {
        return pal_.get_prefix_length();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
Referenced by main().
preorder_begin() [1/2]
template<typename Algorithm > const_preorder_iterator uxn::patl::impl::const_vertex_generic< Algorithm >::preorder_begin () const inline
Definition at line 139 of file vertex.hpp.
    {
        const node_type *q = pal_.get_q();
        return const_preorder_iterator(this_t(cont(), q, q ? get_qid() : 1));
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::cont(), uxn::patl::impl::const_vertex_generic< Algorithm >::get_qid(), and uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
preorder_begin() [2/2]
template<typename Algorithm > const_preorder_iterator uxn::patl::impl::const_vertex_generic< Algorithm >::preorder_begin (word_t limit) const inline
Definition at line 144 of file vertex.hpp.
    {
        this_t vtx(*this);
        if (compact())
            vtx.template descend<0>(limit);
        else
            vtx.toggle();
        return const_preorder_iterator(vtx);
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::compact(), and uxn::patl::impl::const_vertex_generic< Algorithm >::toggle().
preorder_end()
template<typename Algorithm > const_preorder_iterator uxn::patl::impl::const_vertex_generic< Algorithm >::preorder_end () const inline
Definition at line 154 of file vertex.hpp.
    {
        if (pal_.get_q())
        {
            const_preorder_iterator pit(*this);
            pit.next_subtree();
            return pit;
        }
        else
        {
            this_t vtx(*this);
            vtx.toggle();
            return const_preorder_iterator(vtx);
        }
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_, and uxn::patl::impl::const_vertex_generic< Algorithm >::toggle().
rbegin()
template<typename Algorithm > const_reverse_iterator uxn::patl::impl::const_vertex_generic< Algorithm >::rbegin () const inline
Definition at line 109 of file vertex.hpp.
    {
        return const_reverse_iterator(end());
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::end().
rend()
template<typename Algorithm > const_reverse_iterator uxn::patl::impl::const_vertex_generic< Algorithm >::rend () const inline
Definition at line 114 of file vertex.hpp.
    {
        return const_reverse_iterator(begin());
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::begin().
sibling()
template<typename Algorithm > this_t uxn::patl::impl::const_vertex_generic< Algorithm >::sibling () const inline
Definition at line 211 of file vertex.hpp.
    {
        return this_t(pal_.sibling());
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
skip()
template<typename Algorithm > word_t uxn::patl::impl::const_vertex_generic< Algorithm >::skip () const inline
Definition at line 200 of file vertex.hpp.
    {
        return pal_.get_q()->get_skip();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
Referenced by uxn::patl::impl::trie_generic< T, N >::insert(), lz_compress(), and uxn::patl::impl::patricia_dot_base< suffix_set< Type, N, Delta, BitComp, Allocator >, OutStream >::out_node().
the_end()
template<typename Algorithm > bool uxn::patl::impl::const_vertex_generic< Algorithm >::the_end () const inline
Definition at line 170 of file vertex.hpp.
    {
        return pal_.the_end();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
toggle()
template<typename Algorithm > void uxn::patl::impl::const_vertex_generic< Algorithm >::toggle () inline
Definition at line 306 of file vertex.hpp.
    {
        pal_.toggle();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
Referenced by uxn::patl::impl::assoc_generic< This, T, 0 >::begin(), uxn::patl::impl::assoc_generic< This, T, 0 >::end(), uxn::patl::impl::const_vertex_generic< Algorithm >::move_subtree(), uxn::patl::impl::vertex_generic< Algorithm >::postorder_begin(), uxn::patl::impl::const_vertex_generic< Algorithm >::postorder_begin(), uxn::patl::impl::vertex_generic< Algorithm >::postorder_end(), uxn::patl::impl::const_vertex_generic< Algorithm >::postorder_end(), uxn::patl::impl::vertex_generic< Algorithm >::preorder_begin(), uxn::patl::impl::const_vertex_generic< Algorithm >::preorder_begin(), uxn::patl::impl::vertex_generic< Algorithm >::preorder_end(), and uxn::patl::impl::const_vertex_generic< Algorithm >::preorder_end().
value()
template<typename Algorithm > const value_type & uxn::patl::impl::const_vertex_generic< Algorithm >::value () const inline
Definition at line 190 of file vertex.hpp.
    {
        return pal_.get_value();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
Member Data Documentation
pal_
template<typename Algorithm > algorithm uxn::patl::impl::const_vertex_generic< Algorithm >::pal_ protected
Definition at line 342 of file vertex.hpp.
Referenced by uxn::patl::impl::const_vertex_generic< Algorithm >::ascend(), uxn::patl::impl::const_vertex_generic< Algorithm >::ascend_less(), uxn::patl::impl::const_vertex_generic< Algorithm >::bit_comp(), uxn::patl::impl::const_vertex_generic< Algorithm >::compact(), uxn::patl::impl::const_vertex_generic< Algorithm >::cont(), uxn::patl::impl::const_vertex_generic< Algorithm >::get_parent_id(), uxn::patl::impl::const_vertex_generic< Algorithm >::get_prefix(), uxn::patl::impl::const_vertex_generic< Algorithm >::get_qid(), uxn::patl::impl::const_vertex_generic< Algorithm >::get_qtag(), uxn::patl::impl::const_vertex_generic< Algorithm >::iterate(), uxn::patl::impl::const_vertex_generic< Algorithm >::key(), uxn::patl::impl::const_vertex_generic< Algorithm >::mismatch(), uxn::patl::impl::const_vertex_generic< Algorithm >::next_skip(), uxn::patl::impl::const_vertex_generic< Algorithm >::node_p_uid(), uxn::patl::impl::const_vertex_generic< Algorithm >::node_q_uid(), uxn::patl::impl::vertex_generic< Algorithm >::operator algorithm &(), uxn::patl::impl::const_vertex_generic< Algorithm >::operator const algorithm &(), uxn::patl::impl::const_vertex_generic< Algorithm >::operator==(), uxn::patl::impl::const_vertex_generic< Algorithm >::parent_key(), uxn::patl::impl::vertex_generic< Algorithm >::parent_value(), uxn::patl::impl::const_vertex_generic< Algorithm >::parent_value(), uxn::patl::impl::vertex_generic< Algorithm >::postorder_end(), uxn::patl::impl::const_vertex_generic< Algorithm >::postorder_end(), uxn::patl::impl::const_vertex_generic< Algorithm >::prefix_length(), uxn::patl::impl::vertex_generic< Algorithm >::preorder_begin(), uxn::patl::impl::const_vertex_generic< Algorithm >::preorder_begin(), uxn::patl::impl::vertex_generic< Algorithm >::preorder_end(), uxn::patl::impl::const_vertex_generic< Algorithm >::preorder_end(), uxn::patl::impl::vertex_generic< Algorithm >::sibling(), uxn::patl::impl::const_vertex_generic< Algorithm >::sibling(), uxn::patl::impl::const_vertex_generic< Algorithm >::skip(), uxn::patl::impl::const_vertex_generic< Algorithm >::the_end(), uxn::patl::impl::const_vertex_generic< Algorithm >::toggle(), uxn::patl::impl::vertex_generic< Algorithm >::value(), and uxn::patl::impl::const_vertex_generic< Algorithm >::value().
The documentation for this class was generated from the following file:
uxn/patl/impl/vertex.hpp