PATL: uxn::patl::maxrep_iterator< Container >::functor Struct Reference
uxn::patl::maxrep_iterator< Container >::functor Struct Reference
Public Member Functions
void init (maxrep_iterator *mrit)
void push ()
void incr ()
void update ()
void merge ()
bool cond () const
Private Attributes
maxrep_iterator * mrit_
Detailed Description
template<typename Container>
struct uxn::patl::maxrep_iterator< Container >::functor
Definition at line 55 of file maxrep_iterator.hpp.
Member Function Documentation
cond()
template<typename Container > bool uxn::patl::maxrep_iterator< Container >::functor::cond () const inline
Definition at line 83 of file maxrep_iterator.hpp.
        {
            return !impl::get_highest_bit(mrit_->sfreq_.back());
        }
References uxn::patl::impl::get_highest_bit(), uxn::patl::maxrep_iterator< Container >::functor::mrit_, and uxn::patl::maxrep_iterator< Container >::sfreq_.
incr()
template<typename Container > void uxn::patl::maxrep_iterator< Container >::functor::incr () inline
Definition at line 67 of file maxrep_iterator.hpp.
        {
            ++mrit_->sfreq_.back();
            update();
        }
References uxn::patl::maxrep_iterator< Container >::functor::mrit_, uxn::patl::maxrep_iterator< Container >::sfreq_, and uxn::patl::maxrep_iterator< Container >::functor::update().
init()
template<typename Container > void uxn::patl::maxrep_iterator< Container >::functor::init (maxrep_iterator * mrit) inline
Definition at line 57 of file maxrep_iterator.hpp.
        {
            mrit_ = mrit;
        }
References uxn::patl::maxrep_iterator< Container >::functor::mrit_.
Referenced by uxn::patl::maxrep_iterator< Container >::maxrep_iterator().
merge()
template<typename Container > void uxn::patl::maxrep_iterator< Container >::functor::merge () inline
Definition at line 78 of file maxrep_iterator.hpp.
        {
            mrit_->merge();
        }
References uxn::patl::maxrep_iterator< Container >::merge(), and uxn::patl::maxrep_iterator< Container >::functor::mrit_.
push()
template<typename Container > void uxn::patl::maxrep_iterator< Container >::functor::push () inline
Definition at line 62 of file maxrep_iterator.hpp.
        {
            mrit_->sfreq_.push_back(1);
        }
References uxn::patl::maxrep_iterator< Container >::functor::mrit_, and uxn::patl::maxrep_iterator< Container >::sfreq_.
update()
template<typename Container > void uxn::patl::maxrep_iterator< Container >::functor::update () inline
Definition at line 73 of file maxrep_iterator.hpp.
        {
            mrit_->bit31_update();
        }
References uxn::patl::maxrep_iterator< Container >::bit31_update(), and uxn::patl::maxrep_iterator< Container >::functor::mrit_.
Referenced by uxn::patl::maxrep_iterator< Container >::functor::incr().
Member Data Documentation
mrit_
template<typename Container > maxrep_iterator* uxn::patl::maxrep_iterator< Container >::functor::mrit_ private
Definition at line 89 of file maxrep_iterator.hpp.
Referenced by uxn::patl::maxrep_iterator< Container >::functor::cond(), uxn::patl::maxrep_iterator< Container >::functor::incr(), uxn::patl::maxrep_iterator< Container >::functor::init(), uxn::patl::maxrep_iterator< Container >::functor::merge(), uxn::patl::maxrep_iterator< Container >::functor::push(), and uxn::patl::maxrep_iterator< Container >::functor::update().
The documentation for this struct was generated from the following file:
uxn/patl/maxrep_iterator.hpp