PATL: uxn::patl::bit_comparator< piece< T > > Class Template Reference
uxn::patl::bit_comparator< piece< T > > Class Template Reference
bit-comparator for piece<T>
Public Types
typedef T char_type
Public Member Functions
word_t bit_length (const value_type &s) const
word_t get_bit (const value_type &s, word_t id) const
word_t bit_mismatch (const value_type &a, const value_type &b) const
Static Public Attributes
static const word_t bit_size = 8 * sizeof(T)
Private Types
typedef bit_comparator< T > super
typedef piece< T > value_type
Private Member Functions
word_t mismatch_intern (const value_type &a, const value_type &b) const
Detailed Description
template<typename T>
class uxn::patl::bit_comparator< piece< T > >
bit-comparator for piece<T>
Definition at line 68 of file sort_lin.cpp.
Member Typedef Documentation
char_type
template<typename T > typedef T uxn::patl::bit_comparator< piece< T > >::char_type
Definition at line 75 of file sort_lin.cpp.
super
template<typename T > typedef bit_comparator<T> uxn::patl::bit_comparator< piece< T > >::super private
Definition at line 71 of file sort_lin.cpp.
value_type
template<typename T > typedef piece<T> uxn::patl::bit_comparator< piece< T > >::value_type private
Definition at line 72 of file sort_lin.cpp.
Member Function Documentation
bit_length()
template<typename T > word_t uxn::patl::bit_comparator< piece< T > >::bit_length (const value_type & s) const inline
Definition at line 79 of file sort_lin.cpp.
    {
        return bit_size * s.length();
    }
References piece< T >::length().
bit_mismatch()
template<typename T > word_t uxn::patl::bit_comparator< piece< T > >::bit_mismatch (const value_type & a, const value_type & b) const inline
Definition at line 89 of file sort_lin.cpp.
    {
        if (&a == &b)
            return ~word_t(0);
        return b.length() < a.length()
            ? mismatch_intern(b, a)
            : mismatch_intern(a, b);
    }
References piece< T >::length().
get_bit()
template<typename T > word_t uxn::patl::bit_comparator< piece< T > >::get_bit (const value_type & s, word_t id) const inline
Definition at line 84 of file sort_lin.cpp.
    {
        return super::get_bit(s[id / bit_size], id % bit_size);
    }
mismatch_intern()
template<typename T > word_t uxn::patl::bit_comparator< piece< T > >::mismatch_intern (const value_type & a, const value_type & b) const inline private
Definition at line 99 of file sort_lin.cpp.
    {
        word_t i = 0;
        for (; i != a.length(); ++i)
        {
            const word_t m = super::bit_mismatch(a[i], b[i]);
            if (m != ~word_t(0))
                return i * bit_size + m;
        }
        return ~word_t(0);
    }
References piece< T >::length().
Member Data Documentation
bit_size
template<typename T > const word_t uxn::patl::bit_comparator< piece< T > >::bit_size = 8 * sizeof(T) static
Definition at line 77 of file sort_lin.cpp.
The documentation for this class was generated from the following file:
uxn/demos/sort_lin/sort_lin.cpp