PATL: piece< T > Class Template Reference
piece< T > Class Template Reference
Public Member Functions
piece ()
piece (const T *begin, const T *end)
bool empty () const
word_t length () const
const T & operator[] (sword_t off) const
T & operator[] (sword_t off)
const T * begin () const
const T * end () const
Private Attributes
const T * begin_
const T * end_
Detailed Description
template<typename T>
class piece< T >
Definition at line 27 of file sort_lin.cpp.
Constructor & Destructor Documentation
piece() [1/2]
template<typename T > piece< T >::piece () inline
Definition at line 30 of file sort_lin.cpp.
        : begin_(0)
        , end_(0)
    { }
piece() [2/2]
template<typename T > piece< T >::piece (const T * begin, const T * end) inline
Definition at line 35 of file sort_lin.cpp.
        : begin_(begin)
        , end_(end)
    { }
Member Function Documentation
begin()
template<typename T > const T * piece< T >::begin () const inline
Definition at line 51 of file sort_lin.cpp.
    { return begin_; }
References piece< T >::begin_.
Referenced by sort_huge_text_file().
empty()
template<typename T > bool piece< T >::empty () const inline
Definition at line 40 of file sort_lin.cpp.
    { return !begin_ && !end_; }
References piece< T >::begin_, and piece< T >::end_.
Referenced by sort_huge_text_file().
end()
template<typename T > const T * piece< T >::end () const inline
Definition at line 54 of file sort_lin.cpp.
    { return end_; }
References piece< T >::end_.
length()
template<typename T > word_t piece< T >::length () const inline
Definition at line 43 of file sort_lin.cpp.
    { return end_ - begin_; }
References piece< T >::begin_, and piece< T >::end_.
Referenced by uxn::patl::bit_comparator< piece< T > >::bit_length(), uxn::patl::bit_comparator< piece< T > >::bit_mismatch(), uxn::patl::bit_comparator< piece< T > >::mismatch_intern(), and sort_huge_text_file().
operator[]() [1/2]
template<typename T > T & piece< T >::operator[] (sword_t off) inline
Definition at line 48 of file sort_lin.cpp.
    { return begin_[off]; }
References piece< T >::begin_.
operator[]() [2/2]
template<typename T > const T & piece< T >::operator[] (sword_t off) const inline
Definition at line 46 of file sort_lin.cpp.
    { return begin_[off]; }
References piece< T >::begin_.
Member Data Documentation
begin_
template<typename T > const T* piece< T >::begin_ private
Definition at line 58 of file sort_lin.cpp.
Referenced by piece< T >::begin(), piece< T >::empty(), piece< T >::length(), and piece< T >::operator[]().
end_
template<typename T > const T * piece< T >::end_ private
Definition at line 58 of file sort_lin.cpp.
Referenced by piece< T >::empty(), piece< T >::end(), and piece< T >::length().
The documentation for this class was generated from the following file:
uxn/demos/sort_lin/sort_lin.cpp