PATL: uxn::patl::impl::suffix_generic< T > Class Template Reference
uxn::patl::impl::suffix_generic< T > Class Template Reference
#include <suffix_generic.hpp>
Classes
class match_iterator
Public Types
typedef super::key_type key_type
typedef super::value_type value_type
typedef super::bit_compare bit_compare
typedef super::allocator_type allocator_type
typedef super::size_type size_type
typedef super::const_iterator const_iterator
typedef super::iterator iterator
typedef super::prefix prefix
typedef super::const_vertex const_vertex
typedef super::vertex vertex
typedef super::const_preorder_iterator const_preorder_iterator
typedef super::const_postorder_iterator const_postorder_iterator
typedef super::preorder_iterator preorder_iterator
typedef super::postorder_iterator postorder_iterator
typedef algorithm::const_key_reference const_key_reference
Public Types inherited from uxn::patl::impl::assoc_generic< suffix_generic< T >, suffix_generic_traits< T, algorithm_gen_suffix, core_prefix_generic, suffix_generic< T > >, T::N_ >
typedef T::prefix prefix
typedef vertex_generic< algorithm > vertex
typedef preorder_iterator_generic< vertex > preorder_iterator
typedef postorder_iterator_generic< vertex > postorder_iterator
typedef T::key_type key_type
typedef T::value_type value_type
typedef T::bit_compare bit_compare
typedef T::allocator_type allocator_type
typedef const value_type * const_pointer
typedef const value_type & const_reference
typedef value_type * pointer
typedef value_type & reference
typedef allocator_type::difference_type difference_type
typedef word_t size_type
typedef const_iterator_generic< vertex > const_iterator
typedef iterator_generic< vertex > iterator
Public Member Functions
const_key_reference get_key (const node_type *node) const
suffix_generic (key_type keys, size_type size, const bit_compare &bit_comp, const allocator_type &alloc)
size_type size () const
size_type capacity () const
const key_type keys () const
void rebind (const key_type keys)
word_t vertex_index_of (const const_vertex &vtx) const
word_t index_of (const const_vertex &vtx) const
word_t index_of (const prefix &pref) const
prefix prefix_by (word_t id) const
const_vertex vertex_by (word_t id, word_t qid) const
vertex vertex_by (word_t id, word_t qid)
bool endpoint () const
return true if suffix_cont is empty OR full
void pop_front ()
erase front suffix
void pop_back ()
erase back suffix
void clear ()
void reserve (size_type new_size)
Public Member Functions inherited from uxn::patl::impl::assoc_generic< suffix_generic< T >, suffix_generic_traits< T, algorithm_gen_suffix, core_prefix_generic, suffix_generic< T > >, T::N_ >
assoc_generic ()
assoc_generic (const bit_compare &bit_comp)
Static Public Attributes
static const word_t N_ = T::N_
static const word_t delta = T::delta
static const word_t bit_size = bit_compare::bit_size
Static Public Attributes inherited from uxn::patl::impl::assoc_generic< suffix_generic< T >, suffix_generic_traits< T, algorithm_gen_suffix, core_prefix_generic, suffix_generic< T > >, T::N_ >
static const word_t N_
Protected Types
typedef traits::node_type node_type
typedef traits::algorithm algorithm
Protected Types inherited from uxn::patl::impl::assoc_generic< suffix_generic< T >, suffix_generic_traits< T, algorithm_gen_suffix, core_prefix_generic, suffix_generic< T > >, T::N_ >
typedef T::algorithm algorithm
typedef T::node_type node_type
Protected Member Functions
vertex push_back_generic (const node_type &init_node)
vertex push_back_root (const node_type &init_node)
void erase_node (algorithm &pal)
Protected Member Functions inherited from uxn::patl::impl::assoc_generic< suffix_generic< T >, suffix_generic_traits< T, algorithm_gen_suffix, core_prefix_generic, suffix_generic< T > >, T::N_ >
word_t * get_shortcut (word_t a) const
word_t * create_shortcut (word_t a)
Protected Attributes
key_type keys_
ring_buffer< node_type, typename allocator_type::template rebind< node_type >::other > trie_
Private Types
typedef suffix_generic< T > this_t
typedef suffix_generic_traits< T, algorithm_gen_suffix, core_prefix_generic, this_t > traits
typedef assoc_generic< this_t, traits, T::N_ > super
Detailed Description
template<typename T>
class uxn::patl::impl::suffix_generic< T >
Definition at line 101 of file suffix_generic.hpp.
Member Typedef Documentation
algorithm
template<typename T > typedef traits::algorithm uxn::patl::impl::suffix_generic< T >::algorithm protected
Definition at line 113 of file suffix_generic.hpp.
allocator_type
template<typename T > typedef super::allocator_type uxn::patl::impl::suffix_generic< T >::allocator_type
Definition at line 119 of file suffix_generic.hpp.
bit_compare
template<typename T > typedef super::bit_compare uxn::patl::impl::suffix_generic< T >::bit_compare
Definition at line 118 of file suffix_generic.hpp.
const_iterator
template<typename T > typedef super::const_iterator uxn::patl::impl::suffix_generic< T >::const_iterator
Definition at line 121 of file suffix_generic.hpp.
const_key_reference
template<typename T > typedef algorithm::const_key_reference uxn::patl::impl::suffix_generic< T >::const_key_reference
Definition at line 131 of file suffix_generic.hpp.
const_postorder_iterator
template<typename T > typedef super::const_postorder_iterator uxn::patl::impl::suffix_generic< T >::const_postorder_iterator
Definition at line 127 of file suffix_generic.hpp.
const_preorder_iterator
template<typename T > typedef super::const_preorder_iterator uxn::patl::impl::suffix_generic< T >::const_preorder_iterator
Definition at line 126 of file suffix_generic.hpp.
const_vertex
template<typename T > typedef super::const_vertex uxn::patl::impl::suffix_generic< T >::const_vertex
Definition at line 124 of file suffix_generic.hpp.
iterator
template<typename T > typedef super::iterator uxn::patl::impl::suffix_generic< T >::iterator
Definition at line 122 of file suffix_generic.hpp.
key_type
template<typename T > typedef super::key_type uxn::patl::impl::suffix_generic< T >::key_type
Definition at line 116 of file suffix_generic.hpp.
node_type
template<typename T > typedef traits::node_type uxn::patl::impl::suffix_generic< T >::node_type protected
Definition at line 112 of file suffix_generic.hpp.
postorder_iterator
template<typename T > typedef super::postorder_iterator uxn::patl::impl::suffix_generic< T >::postorder_iterator
Definition at line 129 of file suffix_generic.hpp.
prefix
template<typename T > typedef super::prefix uxn::patl::impl::suffix_generic< T >::prefix
Definition at line 123 of file suffix_generic.hpp.
preorder_iterator
template<typename T > typedef super::preorder_iterator uxn::patl::impl::suffix_generic< T >::preorder_iterator
Definition at line 128 of file suffix_generic.hpp.
size_type
template<typename T > typedef super::size_type uxn::patl::impl::suffix_generic< T >::size_type
Definition at line 120 of file suffix_generic.hpp.
super
template<typename T > typedef assoc_generic<this_t, traits, T::N_> uxn::patl::impl::suffix_generic< T >::super private
Definition at line 109 of file suffix_generic.hpp.
this_t
template<typename T > typedef suffix_generic<T> uxn::patl::impl::suffix_generic< T >::this_t private
Definition at line 107 of file suffix_generic.hpp.
traits
template<typename T > typedef suffix_generic_traits<T, algorithm_gen_suffix, core_prefix_generic, this_t> uxn::patl::impl::suffix_generic< T >::traits private
Definition at line 108 of file suffix_generic.hpp.
value_type
template<typename T > typedef super::value_type uxn::patl::impl::suffix_generic< T >::value_type
Definition at line 117 of file suffix_generic.hpp.
vertex
template<typename T > typedef super::vertex uxn::patl::impl::suffix_generic< T >::vertex
Definition at line 125 of file suffix_generic.hpp.
Constructor & Destructor Documentation
suffix_generic()
template<typename T > uxn::patl::impl::suffix_generic< T >::suffix_generic (key_type keys, size_type size, const bit_compare & bit_comp, const allocator_type & alloc) inline
Definition at line 144 of file suffix_generic.hpp.
        : super(bit_comp)
        , keys_(keys)
        , trie_(size, alloc)
    {
    }
Member Function Documentation
capacity()
template<typename T > size_type uxn::patl::impl::suffix_generic< T >::capacity () const inline
Definition at line 160 of file suffix_generic.hpp.
    {
        return trie_.capacity();
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::capacity(), and uxn::patl::impl::suffix_generic< T >::trie_.
clear()
template<typename T > void uxn::patl::impl::suffix_generic< T >::clear () inline
Definition at line 237 of file suffix_generic.hpp.
    {
        trie_.clear();
        this->root_ = 0;
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::clear(), and uxn::patl::impl::suffix_generic< T >::trie_.
Referenced by lz_compress(), and main().
endpoint()
template<typename T > bool uxn::patl::impl::suffix_generic< T >::endpoint () const inline
return true if suffix_cont is empty OR full
Definition at line 207 of file suffix_generic.hpp.
    {
        return trie_.endpoint();
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::endpoint(), and uxn::patl::impl::suffix_generic< T >::trie_.
Referenced by main().
erase_node()
template<typename T > void uxn::patl::impl::suffix_generic< T >::erase_node (algorithm & pal) inline protected
Definition at line 385 of file suffix_generic.hpp.
    {
        node_type *p = pal.erase();
        // special case: del root
        if (p == this->root_)
        {
            node_type *q = pal.get_q();
            this->root_ = q == p ? 0 : q;
        }
    }
Referenced by uxn::patl::impl::suffix_generic< T >::pop_back(), and uxn::patl::impl::suffix_generic< T >::pop_front().
get_key()
template<typename T > const_key_reference uxn::patl::impl::suffix_generic< T >::get_key (const node_type * node) const inline
Definition at line 138 of file suffix_generic.hpp.
    {
        return keys_ + trie_.index_of(node) * delta;
    }
References uxn::patl::impl::suffix_generic< T >::delta, uxn::patl::impl::ring_buffer< Type, Allocator >::index_of(), uxn::patl::impl::suffix_generic< T >::keys_, and uxn::patl::impl::suffix_generic< T >::trie_.
Referenced by uxn::patl::impl::suffix_generic< T >::pop_back().
index_of() [1/2]
template<typename T > word_t uxn::patl::impl::suffix_generic< T >::index_of (const const_vertex & vtx) const inline
Definition at line 182 of file suffix_generic.hpp.
    {
        return trie_.index_of(static_cast<const algorithm&>(vtx).get_p());
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::index_of(), and uxn::patl::impl::suffix_generic< T >::trie_.
Referenced by main(), and multiple_common_substring().
index_of() [2/2]
template<typename T > word_t uxn::patl::impl::suffix_generic< T >::index_of (const prefix & pref) const inline
Definition at line 187 of file suffix_generic.hpp.
    {
        return trie_.index_of(static_cast<const node_type*>(pref));
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::index_of(), and uxn::patl::impl::suffix_generic< T >::trie_.
keys()
template<typename T > const key_type uxn::patl::impl::suffix_generic< T >::keys () const inline
Definition at line 165 of file suffix_generic.hpp.
    {
        return keys_;
    }
References uxn::patl::impl::suffix_generic< T >::keys_.
Referenced by main(), multiple_common_substring(), and uxn::patl::impl::suffix_generic< T >::rebind().
pop_back()
template<typename T > void uxn::patl::impl::suffix_generic< T >::pop_back () inline
erase back suffix
Definition at line 226 of file suffix_generic.hpp.
    {
        node_type *back = trie_.back();
        algorithm pal(this, back, back != this->root_
            ? this->bit_comp_.get_bit(get_key(back), back->get_skip())
            : 0);
        pal.run(get_key(back));
        erase_node(pal);
        trie_.pop_back();
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::back(), uxn::patl::impl::suffix_generic< T >::erase_node(), uxn::patl::impl::suffix_generic< T >::get_key(), uxn::patl::impl::ring_buffer< Type, Allocator >::pop_back(), and uxn::patl::impl::suffix_generic< T >::trie_.
pop_front()
template<typename T > void uxn::patl::impl::suffix_generic< T >::pop_front () inline
erase front suffix
Definition at line 213 of file suffix_generic.hpp.
    {
        node_type *front = trie_.front();
        algorithm pal(this, front, front != this->root_
            ? this->bit_comp_.get_bit(keys_, front->get_skip())
            : 0);
        pal.run(keys_);
        erase_node(pal);
        trie_.pop_front();
        keys_ += delta;
    }
References uxn::patl::impl::suffix_generic< T >::delta, uxn::patl::impl::suffix_generic< T >::erase_node(), uxn::patl::impl::ring_buffer< Type, Allocator >::front(), uxn::patl::impl::suffix_generic< T >::keys_, uxn::patl::impl::ring_buffer< Type, Allocator >::pop_front(), and uxn::patl::impl::suffix_generic< T >::trie_.
Referenced by lz_compress(), and main().
prefix_by()
template<typename T > prefix uxn::patl::impl::suffix_generic< T >::prefix_by (word_t id) const inline
Definition at line 192 of file suffix_generic.hpp.
    {
        return prefix(this, trie_[id]);
    }
References uxn::patl::impl::suffix_generic< T >::trie_.
push_back_generic()
template<typename T > vertex uxn::patl::impl::suffix_generic< T >::push_back_generic (const node_type & init_node) inline protected
Definition at line 351 of file suffix_generic.hpp.
    {
        const key_type key = keys_ + trie_.size() * delta;
        node_type *back = trie_.back();
        word_t skip = max0(static_cast<sword_t>(back->get_skip()) - delta * bit_size);
        algorithm pal(this, this->root_, 0);
        if (skip)
        {
            node_type *back_p = back->get_xlink(back->get_xlink(1) == back ? 0 : 1);
            pal.init(trie_.following(back_p), 0);
            pal.ascend(skip);
            node_type *pretender = pal.get_q();
            if (pretender != this->root_)
                pal.init(pretender, this->bit_comp_.get_bit(key, pretender->get_skip()));
        }
        //
        skip = pal.mismatch_suffix(key, skip);
        // brave new node
        trie_.push_back(init_node);
        node_type *r = trie_.back();
        // add new node into trie
        const word_t bit = this->bit_comp_.get_bit(key, skip);
        pal.add(r, bit, skip);
        return vertex(this, r, bit);
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::back(), uxn::patl::impl::suffix_generic< T >::bit_size, uxn::patl::impl::suffix_generic< T >::delta, uxn::patl::impl::ring_buffer< Type, Allocator >::following(), uxn::patl::impl::suffix_generic< T >::keys_, uxn::patl::impl::max0(), uxn::patl::impl::ring_buffer< Type, Allocator >::push_back(), uxn::patl::impl::ring_buffer< Type, Allocator >::size(), and uxn::patl::impl::suffix_generic< T >::trie_.
push_back_root()
template<typename T > vertex uxn::patl::impl::suffix_generic< T >::push_back_root (const node_type & init_node) inline protected
Definition at line 377 of file suffix_generic.hpp.
    {
        trie_.push_back(init_node);
        this->root_ = trie_.back();
        this->root_->init_root();
        return vertex(this, this->root_, 0);
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::back(), uxn::patl::impl::ring_buffer< Type, Allocator >::push_back(), and uxn::patl::impl::suffix_generic< T >::trie_.
rebind()
template<typename T > void uxn::patl::impl::suffix_generic< T >::rebind (const key_type keys) inline
Definition at line 170 of file suffix_generic.hpp.
    {
        keys_ = keys;
    }
References uxn::patl::impl::suffix_generic< T >::keys(), and uxn::patl::impl::suffix_generic< T >::keys_.
Referenced by lz_compress(), and main().
reserve()
template<typename T > void uxn::patl::impl::suffix_generic< T >::reserve (size_type new_size) inline
Definition at line 243 of file suffix_generic.hpp.
    {
        word_t root_pos = trie_.index_of(this->root_);
        trie_.reserve(new_size);
        this->root_ = this->root_ ? trie_[root_pos] : 0;
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::index_of(), uxn::patl::impl::ring_buffer< Type, Allocator >::reserve(), and uxn::patl::impl::suffix_generic< T >::trie_.
size()
template<typename T > size_type uxn::patl::impl::suffix_generic< T >::size () const inline
Definition at line 155 of file suffix_generic.hpp.
    {
        return trie_.size();
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::size(), and uxn::patl::impl::suffix_generic< T >::trie_.
Referenced by lz_compress(), main(), and multiple_common_substring().
vertex_by() [1/2]
template<typename T > vertex uxn::patl::impl::suffix_generic< T >::vertex_by (word_t id, word_t qid) inline
Definition at line 201 of file suffix_generic.hpp.
    {
        return vertex(this, trie_[id], qid);
    }
References uxn::patl::impl::suffix_generic< T >::trie_.
vertex_by() [2/2]
template<typename T > const_vertex uxn::patl::impl::suffix_generic< T >::vertex_by (word_t id, word_t qid) const inline
Definition at line 197 of file suffix_generic.hpp.
    {
        return const_vertex(this, trie_[id], qid);
    }
References uxn::patl::impl::suffix_generic< T >::trie_.
vertex_index_of()
template<typename T > word_t uxn::patl::impl::suffix_generic< T >::vertex_index_of (const const_vertex & vtx) const inline
Definition at line 175 of file suffix_generic.hpp.
    {
        return
            trie_.index_of(static_cast<const algorithm&>(vtx).get_q()) * 2 |
            vtx.get_qid();
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::index_of(), and uxn::patl::impl::suffix_generic< T >::trie_.
Referenced by multiple_common_substring().
Member Data Documentation
bit_size
template<typename T > const word_t uxn::patl::impl::suffix_generic< T >::bit_size = bit_compare::bit_size static
Definition at line 136 of file suffix_generic.hpp.
Referenced by uxn::patl::impl::suffix_generic< T >::match_iterator::length(), uxn::patl::impl::suffix_generic< T >::match_iterator::operator++(), and uxn::patl::impl::suffix_generic< T >::push_back_generic().
delta
template<typename T > const word_t uxn::patl::impl::suffix_generic< T >::delta = T::delta static
Definition at line 134 of file suffix_generic.hpp.
Referenced by uxn::patl::impl::suffix_generic< T >::get_key(), uxn::patl::impl::suffix_generic< T >::match_iterator::operator++(), uxn::patl::impl::suffix_generic< T >::pop_front(), and uxn::patl::impl::suffix_generic< T >::push_back_generic().
keys_
template<typename T > key_type uxn::patl::impl::suffix_generic< T >::keys_ protected
Definition at line 397 of file suffix_generic.hpp.
Referenced by uxn::patl::impl::suffix_generic< T >::get_key(), uxn::patl::impl::suffix_generic< T >::keys(), uxn::patl::impl::suffix_generic< T >::pop_front(), uxn::patl::impl::suffix_generic< T >::push_back_generic(), and uxn::patl::impl::suffix_generic< T >::rebind().
N_
template<typename T > const word_t uxn::patl::impl::suffix_generic< T >::N_ = T::N_ static
Definition at line 133 of file suffix_generic.hpp.
trie_
template<typename T > ring_buffer< node_type, typename allocator_type::template rebind<node_type>::other> uxn::patl::impl::suffix_generic< T >::trie_ protected
Definition at line 400 of file suffix_generic.hpp.
Referenced by uxn::patl::impl::suffix_generic< T >::capacity(), uxn::patl::impl::suffix_generic< T >::clear(), uxn::patl::impl::suffix_generic< T >::endpoint(), uxn::patl::impl::suffix_generic< T >::get_key(), uxn::patl::impl::suffix_generic< T >::index_of(), uxn::patl::impl::suffix_generic< T >::match_iterator::operator++(), uxn::patl::impl::suffix_generic< T >::pop_back(), uxn::patl::impl::suffix_generic< T >::pop_front(), uxn::patl::impl::suffix_generic< T >::prefix_by(), uxn::patl::impl::suffix_generic< T >::push_back_generic(), uxn::patl::impl::suffix_generic< T >::push_back_root(), uxn::patl::impl::suffix_generic< T >::reserve(), uxn::patl::impl::suffix_generic< T >::size(), uxn::patl::impl::suffix_generic< T >::vertex_by(), and uxn::patl::impl::suffix_generic< T >::vertex_index_of().
The documentation for this class was generated from the following file:
uxn/patl/impl/suffix_generic.hpp