PATL: uxn/demos/sort_lin/sort_lin.cpp File Reference
sort_lin.cpp File Reference
#include <list>
#include <uxn/patl/impl/generator.hpp>
#include <uxn/patl/aux_/file_utils.hpp>
#include <uxn/patl/aux_/file_mapping_io.hpp>
#include <uxn/patl/aux_/buffered_io.hpp>
#include <uxn/patl/aux_/perf_timer.hpp>
#include <uxn/patl/trie_set.hpp>
#include <uxn/patl/trie_map.hpp>
Classes
class piece< T >
class uxn::patl::bit_comparator< piece< T > >
bit-comparator for piece<T>
class strings_from_file_generator
class tmp_sorted_files_generator
class strings_from_merged_files_generator
Namespaces
namespace uxn
namespace uxn::patl
Typedefs
typedef piece< unsigned char > line_t
typedef patl::trie_set< line_t > trie_t
typedef std::list< std::string > temps_t
typedef std::list< std::pair< std::string, strings_from_file_generator * > > merge_src_t
typedef patl::trie_map< line_t, merge_src_t::iterator > trie_map_t
Functions
void sort_huge_text_file (const char *infname, const char *outfname, word_t N)
int main (int argc, char *argv[])
Typedef Documentation
line_t
typedef piece<unsigned char> line_t
Definition at line 115 of file sort_lin.cpp.
merge_src_t
typedef std::list<std::pair<std::string, strings_from_file_generator*> > merge_src_t
Definition at line 119 of file sort_lin.cpp.
temps_t
typedef std::list<std::string> temps_t
Definition at line 117 of file sort_lin.cpp.
trie_map_t
typedef patl::trie_map<line_t, merge_src_t::iterator> trie_map_t
Definition at line 120 of file sort_lin.cpp.
trie_t
typedef patl::trie_set<line_t> trie_t
Definition at line 116 of file sort_lin.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 496 of file sort_lin.cpp.
{
    if (argc < 2)
    {
        printf("SORT_LIN <infile> <outfile> [N = 128]\n");
        return 0;
    }
#ifndef PATL_DEBUG
    try
#endif
    {
        word_t N = 128;
        if (argc > 3 && sscanf(argv[3], "%d", &N) != 1)
            printf("Illegal parameter: %s. Use default value.\n", argv[3]);
        patl::aux::performance_timer tim;
        sort_huge_text_file(argv[1], argv[2], N);
        tim.finish();
        printf("time: %.2f sec.\n", tim.get_seconds());
    }
#ifndef PATL_DEBUG
    catch (const std::exception &exc)
    {
        printf("Error: %s\n", exc.what());
    }
#endif
}
References N, and sort_huge_text_file().
sort_huge_text_file()
void sort_huge_text_file (const char * infname, const char * outfname, word_t N)
Definition at line 458 of file sort_lin.cpp.
{
    const word_t D = 4; // block's amount
    const word_t max_string_size = patl::impl::align_up<1 << 16>((N << 19) / D);
    std::string tmpfname(patl::aux::get_temp_file_name());
    std::auto_ptr<patl::aux::buffered_output> outbuf(
        new patl::aux::buffered_output(tmpfname.c_str()));
    strings_from_merged_files_generator sfmf_gen(infname, N, D, max_string_size);
    while (sfmf_gen.next())
    {
        const line_t value(sfmf_gen.value());
        if (value.empty())
        {
            sfmf_gen.push_front(merge_src_t::value_type(
                tmpfname,
                reinterpret_cast<strings_from_file_generator*>(0)));
#ifdef SORT_LIN_DEBUG
            outbuf->flush_buffer();
            printf("\nmerged to file: '%s', %5.3g Mb ***\n",
                tmpfname.c_str(),
                static_cast<double>(outbuf->get_file_length()) / 1048576.0);
#endif
            tmpfname = patl::aux::get_temp_file_name();
            outbuf.reset(new patl::aux::buffered_output(tmpfname.c_str()));
        }
        else
            outbuf->write_bytes(value.begin(), value.length());
    }
    outbuf.reset();
    if (sfmf_gen.sole_tmpfname())
    {
        patl::aux::delete_file(tmpfname.c_str());
        patl::aux::move_file(sfmf_gen.first_tmpfname().c_str(), outfname);
    }
    else
        patl::aux::move_file(tmpfname.c_str(), outfname);
}
References piece< T >::begin(), uxn::patl::aux::delete_file(), piece< T >::empty(), strings_from_merged_files_generator::first_tmpfname(), uxn::patl::aux::get_temp_file_name(), piece< T >::length(), uxn::patl::aux::move_file(), N, strings_from_merged_files_generator::push_front(), and strings_from_merged_files_generator::sole_tmpfname().
Referenced by main().