PATL: uxn::patl::super_maxrep_iterator< Container >::functor Struct Reference
uxn::patl::super_maxrep_iterator< Container >::functor Struct Reference
Public Member Functions
void init (super_maxrep_iterator *mrit)
void push ()
void incr ()
void update ()
void merge ()
bool cond () const
Private Attributes
super_maxrep_iterator * mrit_
Detailed Description
template<typename Container>
struct uxn::patl::super_maxrep_iterator< Container >::functor
Definition at line 106 of file super_maxrep_iterator.hpp.
Member Function Documentation
cond()
template<typename Container > bool uxn::patl::super_maxrep_iterator< Container >::functor::cond () const inline
Definition at line 133 of file super_maxrep_iterator.hpp.
        {
            return mrit_->sfreq_.back().second.empty();
        }
References uxn::patl::super_maxrep_iterator< Container >::functor::mrit_, and uxn::patl::super_maxrep_iterator< Container >::sfreq_.
incr()
template<typename Container > void uxn::patl::super_maxrep_iterator< Container >::functor::incr () inline
Definition at line 118 of file super_maxrep_iterator.hpp.
        {
            ++mrit_->sfreq_.back().first;
            mrit_->unique_update(mrit_->sfreq_.back().second, mrit_->pref_);
        }
References uxn::patl::super_maxrep_iterator< Container >::functor::mrit_, uxn::patl::super_maxrep_iterator< Container >::pref_, uxn::patl::super_maxrep_iterator< Container >::sfreq_, and uxn::patl::super_maxrep_iterator< Container >::unique_update().
init()
template<typename Container > void uxn::patl::super_maxrep_iterator< Container >::functor::init (super_maxrep_iterator * mrit) inline
Definition at line 108 of file super_maxrep_iterator.hpp.
        {
            mrit_ = mrit;
        }
References uxn::patl::super_maxrep_iterator< Container >::functor::mrit_.
Referenced by uxn::patl::super_maxrep_iterator< Container >::super_maxrep_iterator().
merge()
template<typename Container > void uxn::patl::super_maxrep_iterator< Container >::functor::merge () inline
Definition at line 128 of file super_maxrep_iterator.hpp.
        {
            mrit_->merge();
        }
References uxn::patl::super_maxrep_iterator< Container >::merge(), and uxn::patl::super_maxrep_iterator< Container >::functor::mrit_.
push()
template<typename Container > void uxn::patl::super_maxrep_iterator< Container >::functor::push () inline
Definition at line 113 of file super_maxrep_iterator.hpp.
        {
            mrit_->push_new_pair();
        }
References uxn::patl::super_maxrep_iterator< Container >::functor::mrit_, and uxn::patl::super_maxrep_iterator< Container >::push_new_pair().
update()
template<typename Container > void uxn::patl::super_maxrep_iterator< Container >::functor::update () inline
Definition at line 124 of file super_maxrep_iterator.hpp.
        {
        }
Member Data Documentation
mrit_
template<typename Container > super_maxrep_iterator* uxn::patl::super_maxrep_iterator< Container >::functor::mrit_ private
Definition at line 139 of file super_maxrep_iterator.hpp.
Referenced by uxn::patl::super_maxrep_iterator< Container >::functor::cond(), uxn::patl::super_maxrep_iterator< Container >::functor::incr(), uxn::patl::super_maxrep_iterator< Container >::functor::init(), uxn::patl::super_maxrep_iterator< Container >::functor::merge(), and uxn::patl::super_maxrep_iterator< Container >::functor::push().
The documentation for this struct was generated from the following file:
uxn/patl/super_maxrep_iterator.hpp