PATL: uxn::patl::aux::bit_output< Output > Class Template Reference
uxn::patl::aux::bit_output< Output > Class Template Reference
#include <bitwise_io.hpp>
Public Member Functions
bit_output (Output &dst, word_t size=1<< 16)
~bit_output ()
void put_bit (word_t bit)
void put_bits (word_t bits, word_t n)
void put_fib_code (word_t n)
void put_word (word_t w)
void put_bytes (const char *bytes, word_t n)
Private Member Functions
bit_output & operator= (const bit_output &)
void flush_full ()
void flush ()
Private Attributes
Output & dst_
word_t *const beg_
word_t *const *const end_
word_t *const *const * cur_
word_t num_
Detailed Description
template<typename Output>
class uxn::patl::aux::bit_output< Output >
Definition at line 26 of file bitwise_io.hpp.
Constructor & Destructor Documentation
bit_output()
template<typename Output > uxn::patl::aux::bit_output< Output >::bit_output (Output & dst, word_t size = 1 << 16) inline
Definition at line 31 of file bitwise_io.hpp.
        : dst_(dst)
        , beg_(new word_t [size])
        , end_(beg_ + size)
        , cur_(beg_)
        , num_(0)
    {
        ::memset(beg_, 0, size * sizeof(word_t));
    }
References uxn::patl::aux::bit_output< Output >::beg_.
~bit_output()
template<typename Output > uxn::patl::aux::bit_output< Output >::~bit_output () inline
Definition at line 41 of file bitwise_io.hpp.
    {
        flush();
        delete[] beg_;
    }
References uxn::patl::aux::bit_output< Output >::beg_, and uxn::patl::aux::bit_output< Output >::flush().
Member Function Documentation
flush()
template<typename Output > void uxn::patl::aux::bit_output< Output >::flush () inline private
Definition at line 124 of file bitwise_io.hpp.
    {
        const word_t size = (cur_ - beg_) * sizeof(word_t) +
            impl::align_up<8>(num_) / 8;
        if (size)
        {
            dst_(beg_, size);
            memset(beg_, 0, size);
            cur_ = beg_;
            num_ = 0;
        }
    }
References uxn::patl::aux::bit_output< Output >::beg_, uxn::patl::aux::bit_output< Output >::cur_, uxn::patl::aux::bit_output< Output >::dst_, and uxn::patl::aux::bit_output< Output >::num_.
Referenced by uxn::patl::aux::bit_output< Output >::~bit_output().
flush_full()
template<typename Output > void uxn::patl::aux::bit_output< Output >::flush_full () inline private
Definition at line 113 of file bitwise_io.hpp.
    {
        if (++cur_ == end_)
        {
            const word_t size = (end_ - beg_) * sizeof(word_t);
            dst_(beg_, size);
            memset(beg_, 0, size);
            cur_ = beg_;
        }
    }
References uxn::patl::aux::bit_output< Output >::beg_, uxn::patl::aux::bit_output< Output >::cur_, uxn::patl::aux::bit_output< Output >::dst_, and uxn::patl::aux::bit_output< Output >::end_.
Referenced by uxn::patl::aux::bit_output< Output >::put_bit(), uxn::patl::aux::bit_output< Output >::put_bits(), and uxn::patl::aux::bit_output< Output >::put_word().
operator=()
template<typename Output > bit_output & uxn::patl::aux::bit_output< Output >::operator= (const bit_output< Output > &) private
put_bit()
template<typename Output > void uxn::patl::aux::bit_output< Output >::put_bit (word_t bit) inline
Definition at line 47 of file bitwise_io.hpp.
    {
        *cur_ |= (bit & 1) << num_;
        if (++num_ & bits_in_word)
        {
            num_ = 0;
            flush_full();
        }
    }
References bits_in_word, uxn::patl::aux::bit_output< Output >::cur_, uxn::patl::aux::bit_output< Output >::flush_full(), and uxn::patl::aux::bit_output< Output >::num_.
put_bits()
template<typename Output > void uxn::patl::aux::bit_output< Output >::put_bits (word_t bits, word_t n) inline
Definition at line 57 of file bitwise_io.hpp.
    {
        const word_t bits0 = bits & (1 << n) - 1;
        *cur_ |= bits0 << num_;
        if ((num_ += n) & bits_in_word)
        {
            num_ &= bits_in_word - 1;
            flush_full();
            *cur_ = bits0 >> (n - num_);
        }
    }
References bits_in_word, uxn::patl::aux::bit_output< Output >::cur_, uxn::patl::aux::bit_output< Output >::flush_full(), and uxn::patl::aux::bit_output< Output >::num_.
Referenced by uxn::patl::aux::bit_output< Output >::put_bytes(), and uxn::patl::aux::bit_output< Output >::put_fib_code().
put_bytes()
template<typename Output > void uxn::patl::aux::bit_output< Output >::put_bytes (const char * bytes, word_t n) inline
Definition at line 101 of file bitwise_io.hpp.
    {
        const word_t
            *cur = reinterpret_cast<const word_t*>(bytes),
            *end = cur + n / sizeof(word_t);
        for (; cur != end; ++cur)
            put_word(*cur);
        if (n % sizeof(word_t))
            put_bits(*cur, (n % sizeof(word_t)) * 8);
    }
References uxn::patl::aux::bit_output< Output >::put_bits(), and uxn::patl::aux::bit_output< Output >::put_word().
put_fib_code()
template<typename Output > void uxn::patl::aux::bit_output< Output >::put_fib_code (word_t n) inline
Definition at line 69 of file bitwise_io.hpp.
    {
        word_t i = n < 1597 ? 14 : sizeof(fibs) / sizeof(*fibs) - 1;
        for (; fibs[i] > n; --i) ;
        const word_t highest = i + 1;
        word_t code = 1 << highest;
        for (; n; --i)
        {
            if (fibs[i] <= n)
            {
                code |= 1 << i;
                n -= fibs[i--];
            }
        }
        put_bits(code, highest + 1);
    }
References uxn::patl::aux::fibs, and uxn::patl::aux::bit_output< Output >::put_bits().
put_word()
template<typename Output > void uxn::patl::aux::bit_output< Output >::put_word (word_t w) inline
Definition at line 86 of file bitwise_io.hpp.
    {
        if (num_)
        {
            *cur_ |= w << num_;
            flush_full();
            *cur_ = w >> (bits_in_word - num_);
        }
        else
        {
            *cur_ = w;
            flush_full();
        }
    }
References bits_in_word, uxn::patl::aux::bit_output< Output >::cur_, uxn::patl::aux::bit_output< Output >::flush_full(), and uxn::patl::aux::bit_output< Output >::num_.
Referenced by uxn::patl::aux::bit_output< Output >::put_bytes().
Member Data Documentation
beg_
template<typename Output > word_t* const uxn::patl::aux::bit_output< Output >::beg_ private
Definition at line 139 of file bitwise_io.hpp.
Referenced by uxn::patl::aux::bit_output< Output >::bit_output(), uxn::patl::aux::bit_output< Output >::flush(), uxn::patl::aux::bit_output< Output >::flush_full(), and uxn::patl::aux::bit_output< Output >::~bit_output().
cur_
template<typename Output > word_t* const * const * uxn::patl::aux::bit_output< Output >::cur_ private
Definition at line 141 of file bitwise_io.hpp.
Referenced by uxn::patl::aux::bit_output< Output >::flush(), uxn::patl::aux::bit_output< Output >::flush_full(), uxn::patl::aux::bit_output< Output >::put_bit(), uxn::patl::aux::bit_output< Output >::put_bits(), and uxn::patl::aux::bit_output< Output >::put_word().
dst_
template<typename Output > Output& uxn::patl::aux::bit_output< Output >::dst_ private
Definition at line 137 of file bitwise_io.hpp.
Referenced by uxn::patl::aux::bit_output< Output >::flush(), and uxn::patl::aux::bit_output< Output >::flush_full().
end_
template<typename Output > word_t* const * const uxn::patl::aux::bit_output< Output >::end_ private
Definition at line 140 of file bitwise_io.hpp.
Referenced by uxn::patl::aux::bit_output< Output >::flush_full().
num_
template<typename Output > word_t uxn::patl::aux::bit_output< Output >::num_ private
Definition at line 142 of file bitwise_io.hpp.
Referenced by uxn::patl::aux::bit_output< Output >::flush(), uxn::patl::aux::bit_output< Output >::put_bit(), uxn::patl::aux::bit_output< Output >::put_bits(), and uxn::patl::aux::bit_output< Output >::put_word().
The documentation for this class was generated from the following file:
uxn/patl/aux_/bitwise_io.hpp