PATL: uxn::patl::aux::buffered_input Class Reference
uxn::patl::aux::buffered_input Class Reference
#include <buffered_io.hpp>
Public Member Functions
buffered_input (const char *fname)
buffered_input (HANDLE fh)
bool is_data () const
unsigned char read_byte ()
word_t read_word ()
word_t read_bytes (unsigned char *ptr, word_t len)
void drop_back (word_t offs)
void skip_data (word_t offs)
Public Member Functions inherited from uxn::patl::aux::buffered_base
long long get_file_length ()
Private Member Functions
void fill_buffer ()
word_t fill_buffer (unsigned char *ptr, word_t len)
Private Attributes
unsigned char * cur_
Additional Inherited Members
Protected Types inherited from uxn::patl::aux::buffered_base
enum { BufferSize = 1<<12 }
Protected Member Functions inherited from uxn::patl::aux::buffered_base
buffered_base (const char *fname, bool isWrite)
buffered_base (HANDLE fh)
~buffered_base ()
void set_file_ptr (word_t offs)
word_t get_file_ptr ()
Protected Attributes inherited from uxn::patl::aux::buffered_base
const HANDLE fh_
unsigned char *const buf_
unsigned char * end_
Detailed Description
Definition at line 101 of file buffered_io.hpp.
Constructor & Destructor Documentation
buffered_input() [1/2]
uxn::patl::aux::buffered_input::buffered_input (const char * fname) inline explicit
Definition at line 105 of file buffered_io.hpp.
        : buffered_base(fname, false)
        , cur_(buf_)
    {
        fill_buffer();
    }
References fill_buffer().
buffered_input() [2/2]
uxn::patl::aux::buffered_input::buffered_input (HANDLE fh) inline explicit
Definition at line 112 of file buffered_io.hpp.
        : buffered_base(fh)
        , cur_(buf_)
    {
        fill_buffer();
    }
References fill_buffer().
Member Function Documentation
drop_back()
void uxn::patl::aux::buffered_input::drop_back (word_t offs) inline
Definition at line 162 of file buffered_io.hpp.
    {
        if (static_cast<word_t>(cur_ - buf_) < offs)
        {
            set_file_ptr(get_file_ptr() - (end_ - cur_) - offs);
            fill_buffer();
        }
        else
            cur_ -= offs;
    }
References uxn::patl::aux::buffered_base::buf_, cur_, uxn::patl::aux::buffered_base::end_, fill_buffer(), uxn::patl::aux::buffered_base::get_file_ptr(), and uxn::patl::aux::buffered_base::set_file_ptr().
fill_buffer() [1/2]
void uxn::patl::aux::buffered_input::fill_buffer () inline private
Definition at line 185 of file buffered_io.hpp.
    {
        end_ = (cur_ = buf_) + fill_buffer(buf_, BufferSize);
    }
References uxn::patl::aux::buffered_base::buf_, uxn::patl::aux::buffered_base::BufferSize, cur_, uxn::patl::aux::buffered_base::end_, and fill_buffer().
Referenced by buffered_input(), drop_back(), fill_buffer(), read_byte(), read_bytes(), and skip_data().
fill_buffer() [2/2]
word_t uxn::patl::aux::buffered_input::fill_buffer (unsigned char * ptr, word_t len) inline private
Definition at line 190 of file buffered_io.hpp.
    {
        DWORD realSize;
        const BOOL ret = ::ReadFile(fh_, ptr, len, &realSize, 0);
        if (!ret)
            throw std::exception();
        return realSize;
    }
References uxn::patl::aux::buffered_base::fh_.
is_data()
bool uxn::patl::aux::buffered_input::is_data () const inline
Definition at line 119 of file buffered_io.hpp.
    {
        return cur_ != end_;
    }
References cur_, and uxn::patl::aux::buffered_base::end_.
read_byte()
unsigned char uxn::patl::aux::buffered_input::read_byte () inline
Definition at line 124 of file buffered_io.hpp.
    {
        const unsigned char byte = *cur_++;
        if (cur_ == end_)
            fill_buffer();
        return byte;
    }
References cur_, uxn::patl::aux::buffered_base::end_, and fill_buffer().
Referenced by read_word().
read_bytes()
word_t uxn::patl::aux::buffered_input::read_bytes (unsigned char * ptr, word_t len) inline
Definition at line 147 of file buffered_io.hpp.
    {
        const word_t
            avail = static_cast<word_t>(end_ - cur_),
            chunk = avail < len ? avail : len;
        std::copy(cur_, cur_ + chunk, ptr);
        cur_ += chunk;
        len -= chunk;
        if (len)
            len = fill_buffer(ptr + chunk, len);
        if (cur_ == end_)
            fill_buffer();
        return chunk + len;
    }
References cur_, uxn::patl::aux::buffered_base::end_, and fill_buffer().
read_word()
word_t uxn::patl::aux::buffered_input::read_word () inline
Definition at line 132 of file buffered_io.hpp.
    {
        word_t w = static_cast<word_t>(read_byte());
        w |= static_cast<word_t>(read_byte()) << 8;
        w |= static_cast<word_t>(read_byte()) << 16;
        w |= static_cast<word_t>(read_byte()) << 24;
#ifdef PATL_64
        w |= static_cast<word_t>(read_byte()) << 32;
        w |= static_cast<word_t>(read_byte()) << 40;
        w |= static_cast<word_t>(read_byte()) << 48;
        w |= static_cast<word_t>(read_byte()) << 56;
#endif
        return w;
    }
References read_byte().
skip_data()
void uxn::patl::aux::buffered_input::skip_data (word_t offs) inline
Definition at line 173 of file buffered_io.hpp.
    {
        if (static_cast<word_t>(end_ - cur_) < offs)
        {
            set_file_ptr(get_file_ptr() - (end_ - cur_) + offs);
            fill_buffer();
        }
        else
            cur_ += offs;
    }
References cur_, uxn::patl::aux::buffered_base::end_, fill_buffer(), uxn::patl::aux::buffered_base::get_file_ptr(), and uxn::patl::aux::buffered_base::set_file_ptr().
Member Data Documentation
cur_
unsigned char* uxn::patl::aux::buffered_input::cur_ private
Definition at line 199 of file buffered_io.hpp.
Referenced by drop_back(), fill_buffer(), is_data(), read_byte(), read_bytes(), and skip_data().
The documentation for this class was generated from the following file:
uxn/patl/aux_/buffered_io.hpp