PATL: uxn::patl::suffix_set< Type, N, Delta, BitComp, Allocator > Class Template Reference
uxn::patl::suffix_set< Type, N, Delta, BitComp, Allocator > Class Template Reference
#include <suffix_set.hpp>
Public Types
typedef super::key_type key_type
Public Types inherited from uxn::patl::impl::suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >
typedef super::key_type key_type
typedef super::value_type value_type
typedef super::bit_compare bit_compare
typedef super::allocator_type allocator_type
typedef super::size_type size_type
typedef super::const_iterator const_iterator
typedef super::iterator iterator
typedef super::prefix prefix
typedef super::const_vertex const_vertex
typedef super::vertex vertex
typedef super::const_preorder_iterator const_preorder_iterator
typedef super::const_postorder_iterator const_postorder_iterator
typedef super::preorder_iterator preorder_iterator
typedef super::postorder_iterator postorder_iterator
typedef algorithm::const_key_reference const_key_reference
Public Types inherited from uxn::patl::impl::assoc_generic< suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >, suffix_generic_traits< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > >, algorithm_gen_suffix, core_prefix_generic, suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > > >, T::N_ >
typedef T::prefix prefix
typedef vertex_generic< algorithm > vertex
typedef preorder_iterator_generic< vertex > preorder_iterator
typedef postorder_iterator_generic< vertex > postorder_iterator
typedef T::key_type key_type
typedef T::value_type value_type
typedef T::bit_compare bit_compare
typedef T::allocator_type allocator_type
typedef const value_type * const_pointer
typedef const value_type & const_reference
typedef value_type * pointer
typedef value_type & reference
typedef allocator_type::difference_type difference_type
typedef word_t size_type
typedef const_iterator_generic< vertex > const_iterator
typedef iterator_generic< vertex > iterator
Public Member Functions
suffix_set (Type keys, typename super::size_type size=0x100, const BitComp &bit_comp=BitComp(), const Allocator &alloc=Allocator())
super::vertex push_back ()
word_t count_reindex (const key_type from) const
void pop_reindex (word_t i)
void push_reindex (word_t i)
Public Member Functions inherited from uxn::patl::impl::suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >
const_key_reference get_key (const node_type *node) const
suffix_generic (key_type keys, size_type size, const bit_compare &bit_comp, const allocator_type &alloc)
size_type size () const
size_type capacity () const
const key_type keys () const
void rebind (const key_type keys)
word_t vertex_index_of (const const_vertex &vtx) const
word_t index_of (const const_vertex &vtx) const
word_t index_of (const prefix &pref) const
prefix prefix_by (word_t id) const
const_vertex vertex_by (word_t id, word_t qid) const
vertex vertex_by (word_t id, word_t qid)
bool endpoint () const
return true if suffix_cont is empty OR full
void pop_front ()
erase front suffix
void pop_back ()
erase back suffix
void clear ()
void reserve (size_type new_size)
Public Member Functions inherited from uxn::patl::impl::assoc_generic< suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >, suffix_generic_traits< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > >, algorithm_gen_suffix, core_prefix_generic, suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > > >, T::N_ >
assoc_generic ()
assoc_generic (const bit_compare &bit_comp)
Private Types
typedef suffix_set< Type, N, Delta, BitComp, Allocator > this_t
typedef impl::suffix_generic< impl::suffix_set_traits< Type, N, Delta, BitComp, Allocator > > super
Additional Inherited Members
Static Public Attributes inherited from uxn::patl::impl::suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >
static const word_t N_
static const word_t delta
static const word_t bit_size
Static Public Attributes inherited from uxn::patl::impl::assoc_generic< suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >, suffix_generic_traits< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > >, algorithm_gen_suffix, core_prefix_generic, suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > > >, T::N_ >
static const word_t N_
Protected Types inherited from uxn::patl::impl::suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >
typedef traits::node_type node_type
typedef traits::algorithm algorithm
Protected Types inherited from uxn::patl::impl::assoc_generic< suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >, suffix_generic_traits< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > >, algorithm_gen_suffix, core_prefix_generic, suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > > >, T::N_ >
typedef T::algorithm algorithm
typedef T::node_type node_type
Protected Member Functions inherited from uxn::patl::impl::suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >
vertex push_back_generic (const node_type &init_node)
vertex push_back_root (const node_type &init_node)
void erase_node (algorithm &pal)
Protected Member Functions inherited from uxn::patl::impl::assoc_generic< suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >, suffix_generic_traits< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > >, algorithm_gen_suffix, core_prefix_generic, suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > > >, T::N_ >
word_t * get_shortcut (word_t a) const
word_t * create_shortcut (word_t a)
Protected Attributes inherited from uxn::patl::impl::suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >
key_type keys_
ring_buffer< node_type, typename allocator_type::template rebind< node_type >::other > trie_
Detailed Description
template<typename Type, word_t N = 0, word_t Delta = 1, typename BitComp = bit_comparator<Type, N>, typename Allocator = std::allocator<Type>>
class uxn::patl::suffix_set< Type, N, Delta, BitComp, Allocator >
Definition at line 76 of file suffix_set.hpp.
Member Typedef Documentation
key_type
template<typename Type , word_t N = 0, word_t Delta = 1, typename BitComp = bit_comparator<Type, N>, typename Allocator = std::allocator<Type>> typedef super::key_type uxn::patl::suffix_set< Type, N, Delta, BitComp, Allocator >::key_type
Definition at line 85 of file suffix_set.hpp.
super
template<typename Type , word_t N = 0, word_t Delta = 1, typename BitComp = bit_comparator<Type, N>, typename Allocator = std::allocator<Type>> typedef impl::suffix_generic< impl::suffix_set_traits<Type, N, Delta, BitComp, Allocator> > uxn::patl::suffix_set< Type, N, Delta, BitComp, Allocator >::super private
Definition at line 82 of file suffix_set.hpp.
this_t
template<typename Type , word_t N = 0, word_t Delta = 1, typename BitComp = bit_comparator<Type, N>, typename Allocator = std::allocator<Type>> typedef suffix_set<Type, N, Delta, BitComp, Allocator> uxn::patl::suffix_set< Type, N, Delta, BitComp, Allocator >::this_t private
Definition at line 80 of file suffix_set.hpp.
Constructor & Destructor Documentation
suffix_set()
template<typename Type , word_t N = 0, word_t Delta = 1, typename BitComp = bit_comparator<Type, N>, typename Allocator = std::allocator<Type>> uxn::patl::suffix_set< Type, N, Delta, BitComp, Allocator >::suffix_set (Type keys, typename super::size_type size = 0x100, const BitComp & bit_comp = BitComp(), const Allocator & alloc = Allocator()) inline
Definition at line 88 of file suffix_set.hpp.
        : super(keys, size, bit_comp, alloc)
    {
    }
Member Function Documentation
count_reindex()
template<typename Type , word_t N = 0, word_t Delta = 1, typename BitComp = bit_comparator<Type, N>, typename Allocator = std::allocator<Type>> word_t uxn::patl::suffix_set< Type, N, Delta, BitComp, Allocator >::count_reindex (const key_type from) const inline
Definition at line 120 of file suffix_set.hpp.
    {
        key_type last = this->keys_ + this->size() * this->delta;
        word_t i = this->size() - 1;
        for (
            ; last + this->trie_[i]->get_skip() / this->bit_size >= from
            ; --i, last -= this->delta) ;
        return this->size() - 1 - i;
    }
References uxn::patl::impl::suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >::bit_size, uxn::patl::impl::suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >::delta, uxn::patl::impl::suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >::keys_, uxn::patl::impl::suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >::size(), and uxn::patl::impl::suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >::trie_.
Referenced by lz_compress().
pop_reindex()
template<typename Type , word_t N = 0, word_t Delta = 1, typename BitComp = bit_comparator<Type, N>, typename Allocator = std::allocator<Type>> void uxn::patl::suffix_set< Type, N, Delta, BitComp, Allocator >::pop_reindex (word_t i) inline
Definition at line 130 of file suffix_set.hpp.
    {
        while (i--)
            this->pop_back();
    }
References uxn::patl::impl::suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >::pop_back().
Referenced by lz_compress().
push_back()
template<typename Type , word_t N = 0, word_t Delta = 1, typename BitComp = bit_comparator<Type, N>, typename Allocator = std::allocator<Type>> super::vertex uxn::patl::suffix_set< Type, N, Delta, BitComp, Allocator >::push_back () inline
Definition at line 97 of file suffix_set.hpp.
    {
        if (this->endpoint()) //
        {
            if (this->empty()) //    ( )
                return this->push_back_root(typename super::node_type(
#ifdef PATL_DEBUG
                this->size()
#endif
                ));
            else //  -
                this->reserve(2 * this->capacity());
        }
        return this->push_back_generic(
#ifdef PATL_DEBUG
            typename super::node_type(this->size())
#else
            // ,
            *this->root_
#endif
            );
    }
References uxn::patl::impl::suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >::capacity(), uxn::patl::impl::suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >::endpoint(), uxn::patl::impl::suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >::push_back_generic(), uxn::patl::impl::suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >::push_back_root(), uxn::patl::impl::suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >::reserve(), and uxn::patl::impl::suffix_generic< impl::suffix_set_traits< Type, 0, 1, bit_comparator< Type, 0 >, std::allocator< Type > > >::size().
Referenced by lz_compress(), main(), multiple_common_substring(), and uxn::patl::suffix_set< Type, N, Delta, BitComp, Allocator >::push_reindex().
push_reindex()
template<typename Type , word_t N = 0, word_t Delta = 1, typename BitComp = bit_comparator<Type, N>, typename Allocator = std::allocator<Type>> void uxn::patl::suffix_set< Type, N, Delta, BitComp, Allocator >::push_reindex (word_t i) inline
Definition at line 136 of file suffix_set.hpp.
    {
        while (i--)
            this->push_back();
    }
References uxn::patl::suffix_set< Type, N, Delta, BitComp, Allocator >::push_back().
Referenced by lz_compress().
The documentation for this class was generated from the following file:
uxn/patl/suffix_set.hpp