PATL: uxn::patl::impl::const_preorder_iterator_generic< Vertex > Class Template Reference
uxn::patl::impl::const_preorder_iterator_generic< Vertex > Class Template Reference
#include <preorder_iterator.hpp>
Public Types
typedef Vertex vertex
typedef const vertex * const_pointer
typedef const vertex & const_reference
typedef const_pointer pointer
typedef const_reference reference
Public Member Functions
const_preorder_iterator_generic (const vertex &vtx=vertex())
bool operator== (const this_t &it) const
bool operator!= (const this_t &it) const
const_pointer operator-> () const
const_reference operator* () const
this_t & operator++ ()
this_t operator++ (int)
this_t & operator-- ()
this_t operator-- (int)
void next_subtree ()
template<typename Callback >
void next_subtree (Callback &cb)
void increment (word_t limit)
template<typename Callback >
void increment (Callback &cb)
template<typename Callback >
void increment (word_t limit, Callback &cb)
void decrement (word_t limit)
template<typename Callback >
void decrement (Callback &cb)
template<typename Callback >
void decrement (word_t limit, Callback &cb)
Protected Attributes
vertex vtx_
Private Types
typedef const_preorder_iterator_generic< Vertex > this_t
Detailed Description
template<typename Vertex>
class uxn::patl::impl::const_preorder_iterator_generic< Vertex >
Definition at line 20 of file preorder_iterator.hpp.
Member Typedef Documentation
const_pointer
template<typename Vertex > typedef const vertex* uxn::patl::impl::const_preorder_iterator_generic< Vertex >::const_pointer
Definition at line 29 of file preorder_iterator.hpp.
const_reference
template<typename Vertex > typedef const vertex& uxn::patl::impl::const_preorder_iterator_generic< Vertex >::const_reference
Definition at line 30 of file preorder_iterator.hpp.
pointer
template<typename Vertex > typedef const_pointer uxn::patl::impl::const_preorder_iterator_generic< Vertex >::pointer
Definition at line 31 of file preorder_iterator.hpp.
reference
template<typename Vertex > typedef const_reference uxn::patl::impl::const_preorder_iterator_generic< Vertex >::reference
Definition at line 32 of file preorder_iterator.hpp.
this_t
template<typename Vertex > typedef const_preorder_iterator_generic<Vertex> uxn::patl::impl::const_preorder_iterator_generic< Vertex >::this_t private
Definition at line 25 of file preorder_iterator.hpp.
vertex
template<typename Vertex > typedef Vertex uxn::patl::impl::const_preorder_iterator_generic< Vertex >::vertex
Definition at line 28 of file preorder_iterator.hpp.
Constructor & Destructor Documentation
const_preorder_iterator_generic()
template<typename Vertex > uxn::patl::impl::const_preorder_iterator_generic< Vertex >::const_preorder_iterator_generic (const vertex & vtx = vertex()) inline explicit
Definition at line 34 of file preorder_iterator.hpp.
        : vtx_(vtx)
    {
    }
Member Function Documentation
decrement() [1/3]
template<typename Vertex > template<typename Callback > void uxn::patl::impl::const_preorder_iterator_generic< Vertex >::decrement (Callback & cb) inline
Definition at line 135 of file preorder_iterator.hpp.
    {
        if (vtx_.get_qid())
        {
            vtx_.toggle();
            vtx_.template descend<1>(cb);
        }
        else
            vtx_.ascend();
    }
References uxn::patl::impl::const_preorder_iterator_generic< Vertex >::vtx_.
decrement() [2/3]
template<typename Vertex > void uxn::patl::impl::const_preorder_iterator_generic< Vertex >::decrement (word_t limit) inline
Definition at line 124 of file preorder_iterator.hpp.
    {
        if (vtx_.get_qid())
        {
            vtx_.toggle();
            vtx_.template descend<1>(limit);
        }
        else
            vtx_.ascend();
    }
References uxn::patl::impl::const_preorder_iterator_generic< Vertex >::vtx_.
decrement() [3/3]
template<typename Vertex > template<typename Callback > void uxn::patl::impl::const_preorder_iterator_generic< Vertex >::decrement (word_t limit, Callback & cb) inline
Definition at line 146 of file preorder_iterator.hpp.
    {
        if (vtx_.get_qid())
        {
            vtx_.toggle();
            vtx_.template descend<1>(limit, cb);
        }
        else
            vtx_.ascend();
    }
References uxn::patl::impl::const_preorder_iterator_generic< Vertex >::vtx_.
increment() [1/3]
template<typename Vertex > template<typename Callback > void uxn::patl::impl::const_preorder_iterator_generic< Vertex >::increment (Callback & cb) inline
Definition at line 108 of file preorder_iterator.hpp.
    {
        if (vtx_.get_qtag())
            next_subtree(cb);
        else
            vtx_.iterate(0);
    }
References uxn::patl::impl::const_preorder_iterator_generic< Vertex >::next_subtree(), and uxn::patl::impl::const_preorder_iterator_generic< Vertex >::vtx_.
increment() [2/3]
template<typename Vertex > void uxn::patl::impl::const_preorder_iterator_generic< Vertex >::increment (word_t limit) inline
Definition at line 100 of file preorder_iterator.hpp.
    {
        if (vtx_.limited(limit))
            next_subtree();
        else
            vtx_.iterate(0);
    }
References uxn::patl::impl::const_preorder_iterator_generic< Vertex >::next_subtree(), and uxn::patl::impl::const_preorder_iterator_generic< Vertex >::vtx_.
increment() [3/3]
template<typename Vertex > template<typename Callback > void uxn::patl::impl::const_preorder_iterator_generic< Vertex >::increment (word_t limit, Callback & cb) inline
Definition at line 116 of file preorder_iterator.hpp.
    {
        if (vtx_.limited(limit))
            next_subtree(cb);
        else
            vtx_.iterate(0);
    }
References uxn::patl::impl::const_preorder_iterator_generic< Vertex >::next_subtree(), and uxn::patl::impl::const_preorder_iterator_generic< Vertex >::vtx_.
next_subtree() [1/2]
template<typename Vertex > void uxn::patl::impl::const_preorder_iterator_generic< Vertex >::next_subtree () inline
Definition at line 90 of file preorder_iterator.hpp.
    {
        vtx_.template move_subtree<1>();
    }
References uxn::patl::impl::const_preorder_iterator_generic< Vertex >::vtx_.
Referenced by uxn::patl::impl::const_preorder_iterator_generic< Vertex >::increment(), and uxn::patl::impl::const_preorder_iterator_generic< Vertex >::operator++().
next_subtree() [2/2]
template<typename Vertex > template<typename Callback > void uxn::patl::impl::const_preorder_iterator_generic< Vertex >::next_subtree (Callback & cb) inline
Definition at line 95 of file preorder_iterator.hpp.
    {
        vtx_.template move_subtree<1>(cb);
    }
References uxn::patl::impl::const_preorder_iterator_generic< Vertex >::vtx_.
operator!=()
template<typename Vertex > bool uxn::patl::impl::const_preorder_iterator_generic< Vertex >::operator!= (const this_t & it) const inline
Definition at line 43 of file preorder_iterator.hpp.
    {
        return !(*this == it);
    }
operator*()
template<typename Vertex > const_reference uxn::patl::impl::const_preorder_iterator_generic< Vertex >::operator* () const inline
Definition at line 52 of file preorder_iterator.hpp.
    {
        return vtx_;
    }
References uxn::patl::impl::const_preorder_iterator_generic< Vertex >::vtx_.
operator++() [1/2]
template<typename Vertex > this_t & uxn::patl::impl::const_preorder_iterator_generic< Vertex >::operator++ () inline
Definition at line 57 of file preorder_iterator.hpp.
    {
        if (vtx_.get_qtag())
            next_subtree();
        else
            vtx_.iterate(0);
        return *this;
    }
References uxn::patl::impl::const_preorder_iterator_generic< Vertex >::next_subtree(), and uxn::patl::impl::const_preorder_iterator_generic< Vertex >::vtx_.
operator++() [2/2]
template<typename Vertex > this_t uxn::patl::impl::const_preorder_iterator_generic< Vertex >::operator++ (int) inline
Definition at line 65 of file preorder_iterator.hpp.
    {
        this_t it(*this);
        ++*this;
        return it;
    }
operator--() [1/2]
template<typename Vertex > this_t & uxn::patl::impl::const_preorder_iterator_generic< Vertex >::operator-- () inline
Definition at line 72 of file preorder_iterator.hpp.
    {
        if (vtx_.get_qid())
        {
            vtx_.toggle();
            vtx_.template descend<1>();
        }
        else
            vtx_.ascend();
        return *this;
    }
References uxn::patl::impl::const_preorder_iterator_generic< Vertex >::vtx_.
operator--() [2/2]
template<typename Vertex > this_t uxn::patl::impl::const_preorder_iterator_generic< Vertex >::operator-- (int) inline
Definition at line 83 of file preorder_iterator.hpp.
    {
        this_t it(*this);
        --*this;
        return it;
    }
operator->()
template<typename Vertex > const_pointer uxn::patl::impl::const_preorder_iterator_generic< Vertex >::operator-> () const inline
Definition at line 48 of file preorder_iterator.hpp.
    {
        return &**this;
    }
operator==()
template<typename Vertex > bool uxn::patl::impl::const_preorder_iterator_generic< Vertex >::operator== (const this_t & it) const inline
Definition at line 39 of file preorder_iterator.hpp.
    {
        return vtx_ == it.vtx_;
    }
References uxn::patl::impl::const_preorder_iterator_generic< Vertex >::vtx_.
Member Data Documentation
vtx_
template<typename Vertex > vertex uxn::patl::impl::const_preorder_iterator_generic< Vertex >::vtx_ protected
Definition at line 158 of file preorder_iterator.hpp.
Referenced by uxn::patl::impl::const_preorder_iterator_generic< Vertex >::decrement(), uxn::patl::impl::const_preorder_iterator_generic< Vertex >::increment(), uxn::patl::impl::const_preorder_iterator_generic< Vertex >::next_subtree(), uxn::patl::impl::preorder_iterator_generic< Vertex >::operator const_preorder_iterator(), uxn::patl::impl::const_preorder_iterator_generic< Vertex >::operator*(), uxn::patl::impl::preorder_iterator_generic< Vertex >::operator*(), uxn::patl::impl::const_preorder_iterator_generic< Vertex >::operator++(), uxn::patl::impl::const_preorder_iterator_generic< Vertex >::operator--(), and uxn::patl::impl::const_preorder_iterator_generic< Vertex >::operator==().
The documentation for this class was generated from the following file:
uxn/patl/impl/preorder_iterator.hpp