PATL: uxn::patl::impl::node_generic< Node > Class Template Reference
uxn::patl::impl::node_generic< Node > Class Template Reference
Base class of PATRICIA node.
#include <node.hpp>
Public Member Functions
const node_type * get_parent () const
return parent node
node_type * get_parent ()
word_t get_parent_id () const
return node id relate to parent
const node_type * get_xlink (word_t id) const
return child node by id
node_type * get_xlink (word_t id)
word_t get_xtag (word_t id) const
return tag of child node by id
word_t get_skip () const
return the number of distinction bit
void set_parentid (node_type *parent, word_t id)
set parent info
void set_xlinktag (word_t id, const node_type *link, word_t tag)
set child info by id
void set_skip (word_t skip)
set the number of distinction bit
void init_root ()
root special initialization
bool integrity () const
for debug only
const char * visualize (const node_type *id0) const
for debug only
void make_root (node_type *old_root)
change the root
void set_all_but_value (const node_type *right)
copy data members from right except value_
template<typename Functor >
void realloc (const Functor &new_ptr)
Private Types
typedef Node node_type
Private Attributes
word_t skip_
the number of distinction bit
word_t parentid_
compact representation of parent node with parent-id
word_t linktag_ [2]
compact representation of child nodes with their tags
Detailed Description
template<typename Node>
class uxn::patl::impl::node_generic< Node >
Base class of PATRICIA node.
Definition at line 21 of file node.hpp.
Member Typedef Documentation
node_type
template<typename Node > typedef Node uxn::patl::impl::node_generic< Node >::node_type private
Definition at line 23 of file node.hpp.
Member Function Documentation
get_parent() [1/2]
template<typename Node > node_type * uxn::patl::impl::node_generic< Node >::get_parent () inline
Definition at line 35 of file node.hpp.
    {
#ifdef PATL_ALIGNHACK
        return reinterpret_cast<node_type*>(parentid_ & ~word_t(1));
#else
        return parent_;
#endif
    }
References uxn::patl::impl::node_generic< Node >::parentid_.
get_parent() [2/2]
template<typename Node > const node_type * uxn::patl::impl::node_generic< Node >::get_parent () const inline
return parent node
Definition at line 27 of file node.hpp.
    {
#ifdef PATL_ALIGNHACK
        return reinterpret_cast<const node_type*>(parentid_ & ~word_t(1));
#else
        return parent_;
#endif
    }
References uxn::patl::impl::node_generic< Node >::parentid_.
Referenced by uxn::patl::impl::node_generic< Node >::integrity(), uxn::patl::impl::node_generic< Node >::realloc(), and uxn::patl::impl::node_generic< Node >::visualize().
get_parent_id()
template<typename Node > word_t uxn::patl::impl::node_generic< Node >::get_parent_id () const inline
return node id relate to parent
Definition at line 45 of file node.hpp.
    {
#ifdef PATL_ALIGNHACK
        return parentid_ & word_t(1);
#else
        return tagsid_ >> 2 & word_t(1);
#endif
    }
References uxn::patl::impl::node_generic< Node >::parentid_.
Referenced by uxn::patl::impl::node_generic< Node >::integrity(), uxn::patl::impl::node_generic< Node >::realloc(), and uxn::patl::impl::node_generic< Node >::visualize().
get_skip()
template<typename Node > word_t uxn::patl::impl::node_generic< Node >::get_skip () const inline
return the number of distinction bit
Definition at line 83 of file node.hpp.
    {
        return skip_;
    }
References uxn::patl::impl::node_generic< Node >::skip_.
Referenced by uxn::patl::impl::node_generic< Node >::integrity(), and uxn::patl::impl::node_generic< Node >::visualize().
get_xlink() [1/2]
template<typename Node > node_type * uxn::patl::impl::node_generic< Node >::get_xlink (word_t id) inline
Definition at line 63 of file node.hpp.
    {
#ifdef PATL_ALIGNHACK
        return reinterpret_cast<node_type*>(linktag_[id] & ~word_t(1));
#else
        return link_[id];
#endif
    }
References uxn::patl::impl::node_generic< Node >::linktag_.
get_xlink() [2/2]
template<typename Node > const node_type * uxn::patl::impl::node_generic< Node >::get_xlink (word_t id) const inline
return child node by id
Definition at line 55 of file node.hpp.
    {
#ifdef PATL_ALIGNHACK
        return reinterpret_cast<const node_type*>(linktag_[id] & ~word_t(1));
#else
        return link_[id];
#endif
    }
References uxn::patl::impl::node_generic< Node >::linktag_.
Referenced by uxn::patl::impl::node_generic< Node >::integrity(), uxn::patl::impl::node_generic< Node >::make_root(), uxn::patl::impl::node_generic< Node >::realloc(), and uxn::patl::impl::node_generic< Node >::visualize().
get_xtag()
template<typename Node > word_t uxn::patl::impl::node_generic< Node >::get_xtag (word_t id) const inline
return tag of child node by id
Definition at line 73 of file node.hpp.
    {
#ifdef PATL_ALIGNHACK
        return linktag_[id] & word_t(1);
#else
        return tagsid_ >> id & word_t(1);
#endif
    }
References uxn::patl::impl::node_generic< Node >::linktag_.
Referenced by uxn::patl::impl::node_generic< Node >::integrity(), uxn::patl::impl::node_generic< Node >::realloc(), and uxn::patl::impl::node_generic< Node >::visualize().
init_root()
template<typename Node > void uxn::patl::impl::node_generic< Node >::init_root () inline
root special initialization
Definition at line 119 of file node.hpp.
    {
        set_parentid(0, 0);
        // skip = -1
        set_skip(~word_t(0));
        // left link self-pointed (root)
        set_xlinktag(0, static_cast<node_type*>(this), 1);
        // right link null-pointed (end)
        set_xlinktag(1, 0, 1);
    }
References uxn::patl::impl::node_generic< Node >::set_parentid(), uxn::patl::impl::node_generic< Node >::set_skip(), and uxn::patl::impl::node_generic< Node >::set_xlinktag().
integrity()
template<typename Node > bool uxn::patl::impl::node_generic< Node >::integrity () const inline
for debug only
Definition at line 131 of file node.hpp.
    {
        const word_t
            skip = get_skip(),
            tag0 = get_xtag(0),
            tag1 = get_xtag(1);
        const node_type
            *p0 = get_xlink(0),
            *p1 = get_xlink(1);
        return
            skip == ~word_t(0) && p1 == 0 && get_parent() == 0 && get_parent_id() == 0 ||
            !tag0 && p0->get_parent() == this && !p0->get_parent_id() && skip < p0->get_skip() ||
            !tag1 && p1->get_parent() == this && p1->get_parent_id() && skip < p1->get_skip() ||
            tag0 && tag1;
    }
References uxn::patl::impl::node_generic< Node >::get_parent(), uxn::patl::impl::node_generic< Node >::get_parent_id(), uxn::patl::impl::node_generic< Node >::get_skip(), uxn::patl::impl::node_generic< Node >::get_xlink(), and uxn::patl::impl::node_generic< Node >::get_xtag().
make_root()
template<typename Node > void uxn::patl::impl::node_generic< Node >::make_root (node_type * old_root) inline
change the root
Definition at line 164 of file node.hpp.
    {
        std::swap(skip_, old_root->skip_);
#ifdef PATL_ALIGNHACK
        std::swap(parentid_, old_root->parentid_);
        std::swap(linktag_[0], old_root->linktag_[0]);
        std::swap(linktag_[1], old_root->linktag_[1]);
#else
        std::swap(parent_, old_root->parent_);
        std::swap(link_[0], old_root->link_[0]);
        std::swap(link_[1], old_root->link_[1]);
        std::swap(tagsid_, old_root->tagsid_);
#endif
        old_root->get_parent()->set_xlinktag(old_root->get_parent_id(), old_root, 0);
        if (!old_root->get_xtag(0))
            old_root->get_xlink(0)->set_parentid(old_root, 0);
        if (!old_root->get_xtag(1))
            old_root->get_xlink(1)->set_parentid(old_root, 1);
        get_xlink(0)->set_parentid(reinterpret_cast<node_type*>(this), 0);
    }
References uxn::patl::impl::node_generic< Node >::get_xlink(), uxn::patl::impl::node_generic< Node >::linktag_, uxn::patl::impl::node_generic< Node >::parentid_, uxn::patl::impl::node_generic< Node >::skip_, and uxn::patl::swap().
realloc()
template<typename Node > template<typename Functor > void uxn::patl::impl::node_generic< Node >::realloc (const Functor & new_ptr) inline
Definition at line 202 of file node.hpp.
    {
        if (get_parent())
        {
            set_parentid(new_ptr(get_parent()), get_parent_id());
            set_xlinktag(0, new_ptr(get_xlink(0)), get_xtag(0));
            set_xlinktag(1, new_ptr(get_xlink(1)), get_xtag(1));
        }
        else // if root
            set_xlinktag(0, new_ptr(get_xlink(0)), get_xtag(0));
    }
References uxn::patl::impl::node_generic< Node >::get_parent(), uxn::patl::impl::node_generic< Node >::get_parent_id(), uxn::patl::impl::node_generic< Node >::get_xlink(), uxn::patl::impl::node_generic< Node >::get_xtag(), uxn::patl::impl::node_generic< Node >::set_parentid(), and uxn::patl::impl::node_generic< Node >::set_xlinktag().
set_all_but_value()
template<typename Node > void uxn::patl::impl::node_generic< Node >::set_all_but_value (const node_type * right) inline
copy data members from right except value_
Definition at line 186 of file node.hpp.
    {
        skip_ = right->skip_;
#ifdef PATL_ALIGNHACK
        parentid_ = right->parentid_;
        linktag_[0] = right->linktag_[0];
        linktag_[1] = right->linktag_[1];
#else
        parent_ = right->parent_;
        link_[0] = right->link_[0];
        link_[1] = right->link_[1];
        tagsid_ = right->tagsid_;
#endif
    }
References uxn::patl::impl::node_generic< Node >::linktag_, uxn::patl::impl::node_generic< Node >::parentid_, and uxn::patl::impl::node_generic< Node >::skip_.
set_parentid()
template<typename Node > void uxn::patl::impl::node_generic< Node >::set_parentid (node_type * parent, word_t id) inline
set parent info
Definition at line 89 of file node.hpp.
    {
#ifdef PATL_ALIGNHACK
        parentid_ = reinterpret_cast<word_t>(parent) | id;
#else
        parent_ = parent;
        tagsid_ &= 3;
        tagsid_ |= id << 2;
#endif
    }
References uxn::patl::impl::node_generic< Node >::parentid_.
Referenced by uxn::patl::impl::node_generic< Node >::init_root(), and uxn::patl::impl::node_generic< Node >::realloc().
set_skip()
template<typename Node > void uxn::patl::impl::node_generic< Node >::set_skip (word_t skip) inline
set the number of distinction bit
Definition at line 113 of file node.hpp.
    {
        skip_ = skip;
    }
References uxn::patl::impl::node_generic< Node >::skip_.
Referenced by uxn::patl::impl::node_generic< Node >::init_root().
set_xlinktag()
template<typename Node > void uxn::patl::impl::node_generic< Node >::set_xlinktag (word_t id, const node_type * link, word_t tag) inline
set child info by id
Definition at line 101 of file node.hpp.
    {
#ifdef PATL_ALIGNHACK
        linktag_[id] = reinterpret_cast<word_t>(link) | tag;
#else
        link_[id] = const_cast<node_type*>(link);
        tagsid_ &= ~(1 << id);
        tagsid_ |= tag << id;
#endif
    }
References uxn::patl::impl::node_generic< Node >::linktag_.
Referenced by uxn::patl::impl::node_generic< Node >::init_root(), and uxn::patl::impl::node_generic< Node >::realloc().
visualize()
template<typename Node > const char * uxn::patl::impl::node_generic< Node >::visualize (const node_type * id0) const inline
for debug only
Definition at line 148 of file node.hpp.
    {
        static char buf[256];
        sprintf(buf, "%d skip: %d pt: %d ptId: %d lnk0: %d tag0: %d lnk1: %d tag1: %d\n",
            this - id0,
            get_skip(),
            get_parent() - id0,
            get_parent_id(),
            get_xlink(0) - id0,
            get_xtag(0),
            get_xlink(1) - id0,
            get_xtag(1));
        return buf;
    }
References uxn::patl::impl::node_generic< Node >::get_parent(), uxn::patl::impl::node_generic< Node >::get_parent_id(), uxn::patl::impl::node_generic< Node >::get_skip(), uxn::patl::impl::node_generic< Node >::get_xlink(), and uxn::patl::impl::node_generic< Node >::get_xtag().
Member Data Documentation
linktag_
template<typename Node > word_t uxn::patl::impl::node_generic< Node >::linktag_[2] private
compact representation of child nodes with their tags
Definition at line 221 of file node.hpp.
Referenced by uxn::patl::impl::node_generic< Node >::get_xlink(), uxn::patl::impl::node_generic< Node >::get_xtag(), uxn::patl::impl::node_generic< Node >::make_root(), uxn::patl::impl::node_generic< Node >::set_all_but_value(), and uxn::patl::impl::node_generic< Node >::set_xlinktag().
parentid_
template<typename Node > word_t uxn::patl::impl::node_generic< Node >::parentid_ private
compact representation of parent node with parent-id
Definition at line 219 of file node.hpp.
Referenced by uxn::patl::impl::node_generic< Node >::get_parent(), uxn::patl::impl::node_generic< Node >::get_parent_id(), uxn::patl::impl::node_generic< Node >::make_root(), uxn::patl::impl::node_generic< Node >::set_all_but_value(), and uxn::patl::impl::node_generic< Node >::set_parentid().
skip_
template<typename Node > word_t uxn::patl::impl::node_generic< Node >::skip_ private
the number of distinction bit
Definition at line 216 of file node.hpp.
Referenced by uxn::patl::impl::node_generic< Node >::get_skip(), uxn::patl::impl::node_generic< Node >::make_root(), uxn::patl::impl::node_generic< Node >::set_all_but_value(), and uxn::patl::impl::node_generic< Node >::set_skip().
The documentation for this class was generated from the following file:
uxn/patl/impl/node.hpp