PATL: uxn::patl::aux::file_mapping_input Class Reference
uxn::patl::aux::file_mapping_input Class Reference
#include <file_mapping_io.hpp>
Public Member Functions
file_mapping_input (const char *fname)
~file_mapping_input ()
long long get_file_length () const
long long residue_length () const
std::auto_ptr< file_mapping_view > create_view (word_t size)
word_t drop_back (word_t dropped)
Private Attributes
HANDLE fh_
HANDLE fmh_
long long length_
long long offset_
Detailed Description
Definition at line 58 of file file_mapping_io.hpp.
Constructor & Destructor Documentation
file_mapping_input()
uxn::patl::aux::file_mapping_input::file_mapping_input (const char * fname) inline
Definition at line 61 of file file_mapping_io.hpp.
        : fh_(::CreateFile(
            fname, GENERIC_READ, FILE_SHARE_READ, 0,
            OPEN_EXISTING, FILE_FLAG_SEQUENTIAL_SCAN, 0))
        , fmh_(fh_ != INVALID_HANDLE_VALUE
            ? ::CreateFileMapping(fh_, 0, PAGE_READONLY, 0, 0, 0)
            : 0)
        , length_(fh_ != INVALID_HANDLE_VALUE
            ? patl::aux::get_long_file_length(fh_)
            : -1)
        , offset_(0)
    {
        if (fh_ == INVALID_HANDLE_VALUE)
            PATL_WIN32_EXCEPTION(CreateFile);
        if (!fmh_)
            PATL_WIN32_EXCEPTION(CreateFileMapping);
    }
References fh_, fmh_, and PATL_WIN32_EXCEPTION.
~file_mapping_input()
uxn::patl::aux::file_mapping_input::~file_mapping_input () inline
Definition at line 79 of file file_mapping_io.hpp.
    {
        if (fmh_)
            ::CloseHandle(fmh_);
        ::CloseHandle(fh_);
    }
References fh_, and fmh_.
Member Function Documentation
create_view()
std::auto_ptr< file_mapping_view > uxn::patl::aux::file_mapping_input::create_view (word_t size) inline
Definition at line 96 of file file_mapping_io.hpp.
    {
        size = static_cast<word_t>(patl::impl::get_min(
                static_cast<long long>(patl::impl::align_up<1 << 16>(size)),
                residue_length()));
        std::auto_ptr<file_mapping_view> v(
            new file_mapping_view(fmh_, offset_, size));
        offset_ += size;
        return v;
    }
References uxn::patl::impl::align_up(), fmh_, uxn::patl::impl::get_min(), offset_, and residue_length().
drop_back()
word_t uxn::patl::aux::file_mapping_input::drop_back (word_t dropped) inline
Definition at line 107 of file file_mapping_io.hpp.
    {
        dropped = static_cast<word_t>(offset_ - patl::impl::align_down<1 << 16>(
            static_cast<word_t>(offset_ - dropped)));
        offset_ = dropped < offset_ ? offset_ - dropped : 0;
        return dropped;
    }
References offset_.
get_file_length()
long long uxn::patl::aux::file_mapping_input::get_file_length () const inline
Definition at line 86 of file file_mapping_io.hpp.
    {
        return get_long_file_length(fh_);
    }
References fh_, and uxn::patl::aux::get_long_file_length().
residue_length()
long long uxn::patl::aux::file_mapping_input::residue_length () const inline
Definition at line 91 of file file_mapping_io.hpp.
    {
        return length_ - offset_;
    }
References length_, and offset_.
Referenced by create_view().
Member Data Documentation
fh_
HANDLE uxn::patl::aux::file_mapping_input::fh_ private
Definition at line 116 of file file_mapping_io.hpp.
Referenced by file_mapping_input(), get_file_length(), and ~file_mapping_input().
fmh_
HANDLE uxn::patl::aux::file_mapping_input::fmh_ private
Definition at line 116 of file file_mapping_io.hpp.
Referenced by create_view(), file_mapping_input(), and ~file_mapping_input().
length_
long long uxn::patl::aux::file_mapping_input::length_ private
Definition at line 117 of file file_mapping_io.hpp.
Referenced by residue_length().
offset_
long long uxn::patl::aux::file_mapping_input::offset_ private
Definition at line 118 of file file_mapping_io.hpp.
Referenced by create_view(), drop_back(), and residue_length().
The documentation for this class was generated from the following file:
uxn/patl/aux_/file_mapping_io.hpp