PATL: uxn::patl Namespace Reference
uxn::patl Namespace Reference
Namespaces
namespace aux
namespace impl
Classes
class bit_comparator
class bit_comparator< char, 8 >
class bit_comparator< piece< T > >
bit-comparator for piece<T>
class bit_comparator< std::basic_string< T >, 0 >
standard finite std::basic_string
class bit_comparator< std::basic_string< T >, 8 >
class bit_comparator< std::vector< T >, 0 >
standard finite std::vector
class bit_comparator< std::vector< T >, 8 >
class bit_comparator< T **, 0 >
simple infinite (T**) string (treat (T*) as word_t)
class bit_comparator< T **, 16 >
class bit_comparator< T **, 8 >
class bit_comparator< T *, 0 >
simple infinite (T*) string
class bit_comparator< T *, 8 >
class bit_comparator< T, 0 >
restriction: NO key CAN BE a prefix of any other key
class bit_comparator< T, 8 >
class bit_comparator< unsigned char, 8 >
class bit_comparator< word_t, 16 >
class bit_comparator_0
simple zero-terminated (T*) string
class bit_comparator_0< T, 0 >
class bounded_bit_comparator
statically Q-bounded bit-comparator
class bounded_bit_comparator< T, Q, 0, Delta >
class hamming_distance
Hamming distance decision functor.
struct hash
struct hash< word_t >
class lca_oracle
class leaf_oracle
class levenshtein_distance
class levenshtein_ms_distance
Levenshtein distance with merges and splits decision functor.
class levenshtein_tp_distance
Levenshtein distance with transpositions decision functor.
class maxrep_iterator
class ngram_stat
class partial_match
class patricia_dot_creator
class ptr_bit_comparator
keys dereferenced from pointers
class range_decoder
class range_encoder
class reverse_bit_comparator
bit-comparator for reversed lexicographical ordering
class suffix_map
class suffix_set
class super_maxrep_iterator
class trie_map
class trie_set
class unique_priority_queue
class unordered_map
Functions
template<bool Huge, typename Suffix >
void build_ms (const Suffix &suffix, const typename Suffix::key_type &begin, word_t size, word_t *ms)
template<bool Huge, typename Suffix >
void build_ms_ps (const Suffix &suffix, const typename Suffix::key_type &begin, word_t size, word_t *ms, word_t *ps)
template<typename Suffix >
word_t get_lce (const Suffix &suffix, word_t mi, word_t pi const typename Suffix::algorithm &j)
template<typename Key , typename Datum , word_t N, typename BitComp , typename Allocator >
void swap (trie_map< Key, Datum, N, BitComp, Allocator > &a, trie_map< Key, Datum, N, BitComp, Allocator > &b)
template<typename Key , word_t N, typename BitComp , typename Allocator >
void swap (trie_set< Key, N, BitComp, Allocator > &a, trie_set< Key, N, BitComp, Allocator > &b)
Function Documentation
build_ms()
template<bool Huge, typename Suffix > void uxn::patl::build_ms (const Suffix & suffix, const typename Suffix::key_type & begin, word_t size, word_t * ms) inline
Definition at line 17 of file suffix_utils.hpp.
{
    Suffix::match_iterator<Huge> mit(&suffix, begin);
    for (const word_t *msEnd = ms + size; ms != msEnd; ++ms, ++mit)
        *ms = mit.length();
}
build_ms_ps()
template<bool Huge, typename Suffix > void uxn::patl::build_ms_ps (const Suffix & suffix, const typename Suffix::key_type & begin, word_t size, word_t * ms, word_t * ps) inline
Definition at line 29 of file suffix_utils.hpp.
{
    Suffix::match_iterator<Huge> mit(&suffix, begin);
    for (const word_t *msEnd = ms + size; ms != msEnd; ++ms, ++ps, ++mit)
    {
        *ms = mit.length();
        *ps = mit->compact();
    }
}
get_lce()
template<typename Suffix > word_t uxn::patl::get_lce (const Suffix & suffix, word_t mi, word_t pi const typename Suffix::algorithm & j) inline
Definition at line 46 of file suffix_utils.hpp.
{
    return impl::get_min(
        mi,
        suffix.get_lca(pi, j)->getPrefixLen / Suffix::bit_size);
}
References uxn::patl::impl::get_min().
swap() [1/2]
template<typename Key , typename Datum , word_t N, typename BitComp , typename Allocator > void uxn::patl::swap (trie_map< Key, Datum, N, BitComp, Allocator > & a, trie_map< Key, Datum, N, BitComp, Allocator > & b) inline
Definition at line 90 of file trie_map.hpp.
{
    a.swap(b);
}
Referenced by uxn::patl::impl::node_generic< Node >::make_root(), uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::resize(), and uxn::patl::impl::trie_generic< T, 0 >::swap().
swap() [2/2]
template<typename Key , word_t N, typename BitComp , typename Allocator > void uxn::patl::swap (trie_set< Key, N, BitComp, Allocator > & a, trie_set< Key, N, BitComp, Allocator > & b) inline
Definition at line 72 of file trie_set.hpp.
{
    a.swap(b);
}