PATL: uxn::patl::aux Namespace Reference
uxn::patl::aux Namespace Reference
Classes
class bit_input
class bit_output
class buffered_base
class buffered_input
class buffered_output
class file_mapping_input
class file_mapping_view
class performance_timer
class static_alloc
class static_alloc_state
class win32_exception
Functions
bool is_blank_char (unsigned char c)
bool is_latin_letter (unsigned char c)
bool is_cyrillic_letter (unsigned char c)
bool is_proper_char (unsigned char c)
bool is_letter (unsigned char c)
bool is_hyphen (unsigned char c)
bool is_punctuation (unsigned char c)
bool is_numeric (unsigned char c)
bool is_dot_symbol (unsigned char c)
unsigned char to_lower (unsigned char c)
unsigned char to_upper (unsigned char c)
void delete_file (const char *fname)
void move_file (const char *from_path, const char *to_path)
std::string get_temp_file_name (const char *prefix="TMP", const char *path=".")
word_t get_file_length (HANDLE fh)
long long get_long_file_length (HANDLE fh)
long long get_long_file_length (const char *fname)
std::string take_file_folder (const std::string &str)
std::string take_file_name_ext (const std::string &str)
bool is_dots_folder (const char *ref)
Variables
const word_t fibs []
Function Documentation
delete_file()
void uxn::patl::aux::delete_file (const char * fname) inline
Definition at line 62 of file file_utils.hpp.
{
    if (!::DeleteFile(fname))
        PATL_WIN32_EXCEPTION(DeleteFile);
}
References PATL_WIN32_EXCEPTION.
Referenced by strings_from_merged_files_generator::delete_src(), and sort_huge_text_file().
get_file_length()
word_t uxn::patl::aux::get_file_length (HANDLE fh) inline
Definition at line 85 of file file_utils.hpp.
{
    const word_t cur = ::SetFilePointer(fh, 0, 0, FILE_CURRENT);
    const word_t len = ::SetFilePointer(fh, 0, 0, FILE_END);
    if (cur == INVALID_SET_FILE_POINTER || len == INVALID_SET_FILE_POINTER ||
        ::SetFilePointer(fh, cur, 0, FILE_BEGIN) == INVALID_SET_FILE_POINTER)
        PATL_WIN32_EXCEPTION(SetFilePointer);
    return len;
}
References PATL_WIN32_EXCEPTION.
get_long_file_length() [1/2]
long long uxn::patl::aux::get_long_file_length (const char * fname) inline
Definition at line 108 of file file_utils.hpp.
{
    WIN32_FIND_DATA data;
    const HANDLE ffh = ::FindFirstFile(fname, &data);
    if (ffh == INVALID_HANDLE_VALUE)
        PATL_WIN32_EXCEPTION(FindFirstFile);
    ::FindClose(ffh);
    return
        static_cast<long long>(data.nFileSizeLow) |
        (static_cast<long long>(data.nFileSizeHigh) << (8 * sizeof(long)));
}
References PATL_WIN32_EXCEPTION.
get_long_file_length() [2/2]
long long uxn::patl::aux::get_long_file_length (HANDLE fh) inline
Definition at line 95 of file file_utils.hpp.
{
    LONG cur_h = 0, len_h = 0;
    const DWORD cur = ::SetFilePointer(fh, 0, &cur_h, FILE_CURRENT);
    const DWORD len = ::SetFilePointer(fh, 0, &len_h, FILE_END);
    if (cur == INVALID_SET_FILE_POINTER || len == INVALID_SET_FILE_POINTER ||
        ::SetFilePointer(fh, cur, &cur_h, FILE_BEGIN) == INVALID_SET_FILE_POINTER)
        PATL_WIN32_EXCEPTION(SetFilePointer);
    return
        static_cast<long long>(len) |
        (static_cast<long long>(len_h) << (8 * sizeof(long)));
}
References PATL_WIN32_EXCEPTION.
Referenced by uxn::patl::aux::buffered_base::get_file_length(), uxn::patl::aux::file_mapping_input::get_file_length(), and strings_from_merged_files_generator::while().
get_temp_file_name()
std::string uxn::patl::aux::get_temp_file_name (const char * prefix = "TMP", const char * path = ".") inline
Definition at line 75 of file file_utils.hpp.
{
    char buf[MAX_PATH];
    if (!::GetTempFileName(path, prefix, 0, buf))
        PATL_WIN32_EXCEPTION(GetTempFileName);
    return std::string(buf);
}
References PATL_WIN32_EXCEPTION.
Referenced by sort_huge_text_file().
is_blank_char()
bool uxn::patl::aux::is_blank_char (unsigned char c) inline
Definition at line 16 of file char.hpp.
{
    return c <= 0x20;
}
is_cyrillic_letter()
bool uxn::patl::aux::is_cyrillic_letter (unsigned char c) inline
Definition at line 26 of file char.hpp.
{
    return 0xC0 <= c || c == 0xA8 || c == 0xB8;
}
Referenced by is_letter(), and is_proper_char().
is_dot_symbol()
bool uxn::patl::aux::is_dot_symbol (unsigned char c) inline
Definition at line 57 of file char.hpp.
{
    return c == '!' || c == '.' || c == '?';
}
Referenced by parse_fiction().
is_dots_folder()
bool uxn::patl::aux::is_dots_folder (const char * ref) inline
Definition at line 146 of file file_utils.hpp.
{
    return ref[0] == '.' && (ref[1] == 0 || ref[1] == '.' && ref[2] == 0);
}
is_hyphen()
bool uxn::patl::aux::is_hyphen (unsigned char c) inline
Definition at line 42 of file char.hpp.
{
    return c == '-';
}
Referenced by parse_fiction().
is_latin_letter()
bool uxn::patl::aux::is_latin_letter (unsigned char c) inline
Definition at line 21 of file char.hpp.
{
    return 0x41 <= c && c <= 0x5A || 0x61 <= c && c <= 0x7A;
}
Referenced by is_letter().
is_letter()
bool uxn::patl::aux::is_letter (unsigned char c) inline
Definition at line 36 of file char.hpp.
{
    return is_cyrillic_letter(c) || is_latin_letter(c);
}
References is_cyrillic_letter(), and is_latin_letter().
Referenced by parse_fiction().
is_numeric()
bool uxn::patl::aux::is_numeric (unsigned char c) inline
Definition at line 52 of file char.hpp.
{
    return 0x30 <= c && c <= 0x39;
}
is_proper_char()
bool uxn::patl::aux::is_proper_char (unsigned char c) inline
Definition at line 31 of file char.hpp.
{
    return 0x21 <= c && c <= 0x7E || is_cyrillic_letter(c);
}
References is_cyrillic_letter().
Referenced by parse_text().
is_punctuation()
bool uxn::patl::aux::is_punctuation (unsigned char c) inline
Definition at line 47 of file char.hpp.
{
    return 0x21 <= c && c <= 0x2F || 0x3A <= c && c <= 0x3F;
}
Referenced by parse_fiction().
move_file()
void uxn::patl::aux::move_file (const char * from_path, const char * to_path) inline
Definition at line 68 of file file_utils.hpp.
{
    if (!::MoveFileEx(from_path, to_path,
        MOVEFILE_COPY_ALLOWED | MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH))
        PATL_WIN32_EXCEPTION(MoveFileEx);
}
References PATL_WIN32_EXCEPTION.
Referenced by sort_huge_text_file().
take_file_folder()
std::string uxn::patl::aux::take_file_folder (const std::string & str) inline
Definition at line 120 of file file_utils.hpp.
{
    const std::string::size_type n = str.find_last_of("\\/:");
    if (n == std::string::npos)
        return ".";
    switch (str[n])
    {
    case ':':
        return str.substr(0, n + 1);
    case '\\':
    case '/':
        if (str[n - 1] == ':')
            return str.substr(0, n + 1);
        else
            return str.substr(0, n);
    default:
        return "error";
    }
}
take_file_name_ext()
std::string uxn::patl::aux::take_file_name_ext (const std::string & str) inline
Definition at line 140 of file file_utils.hpp.
{
    const std::string::size_type n = str.find_last_of("\\/:");
    return str.substr(0, n);
}
to_lower()
unsigned char uxn::patl::aux::to_lower (unsigned char c) inline
Definition at line 62 of file char.hpp.
{
    return c + (0x41 <= c && c <= 0x5A || 0xC0 <= c && c <= 0xDF ? 0x20 : 0);
}
Referenced by parse_fiction().
to_upper()
unsigned char uxn::patl::aux::to_upper (unsigned char c) inline
Definition at line 67 of file char.hpp.
{
    return c - (0x61 <= c && c <= 0x7A || 0xE0 <= c ? 0x20 : 0);
}
Variable Documentation
fibs
const word_t uxn::patl::aux::fibs[]
Initial value:
=
{ 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987
, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368
}
Definition at line 20 of file bitwise_io.hpp.
Referenced by uxn::patl::aux::bit_input< Input >::get_fib_code(), and uxn::patl::aux::bit_output< Output >::put_fib_code().