PATL: uxn::patl::impl::prefix_generic< This, Container, Node > Class Template Reference
uxn::patl::impl::prefix_generic< This, Container, Node > Class Template Reference
#include <prefix.hpp>
Public Types
typedef Container cont_type
typedef cont_type::key_type key_type
typedef cont_type::const_key_reference const_key_reference
typedef cont_type::bit_compare bit_compare
typedef cont_type::vertex vertex
Public Member Functions
prefix_generic (const cont_type *cont, const node_type *q)
bool operator== (const this_t &b) const
bool operator!= (const this_t &b) const
operator const node_type * () const
word_t node_uid () const
word_t get_xtag (word_t id) const
word_t get_parent_id () const
void go_xlink (word_t id)
void go_parent ()
vertex get_vertex () const
const cont_type * cont () const
bool is_root () const
word_t skip () const
word_t skip (word_t id) const
bool symbol_limit (word_t id) const
word_t length () const
const_key_reference key () const
const_key_reference key (word_t id) const
bool leaf (word_t id) const
template<typename Callback >
void postorder_init (Callback &cb)
template<typename Callback >
void postorder_incr (Callback &cb)
Protected Types
typedef Node node_type
Private Types
typedef This this_t
Private Member Functions
template<typename Callback >
void postorder_descend (Callback &cb)
template<typename Callback >
void postorder_ascend (Callback &cb)
Private Attributes
const cont_type * cont_
const node_type * q_
Detailed Description
template<typename This, typename Container, typename Node>
class uxn::patl::impl::prefix_generic< This, Container, Node >
Definition at line 19 of file prefix.hpp.
Member Typedef Documentation
bit_compare
template<typename This , typename Container , typename Node > typedef cont_type::bit_compare uxn::patl::impl::prefix_generic< This, Container, Node >::bit_compare
Definition at line 30 of file prefix.hpp.
const_key_reference
template<typename This , typename Container , typename Node > typedef cont_type::const_key_reference uxn::patl::impl::prefix_generic< This, Container, Node >::const_key_reference
Definition at line 29 of file prefix.hpp.
cont_type
template<typename This , typename Container , typename Node > typedef Container uxn::patl::impl::prefix_generic< This, Container, Node >::cont_type
Definition at line 27 of file prefix.hpp.
key_type
template<typename This , typename Container , typename Node > typedef cont_type::key_type uxn::patl::impl::prefix_generic< This, Container, Node >::key_type
Definition at line 28 of file prefix.hpp.
node_type
template<typename This , typename Container , typename Node > typedef Node uxn::patl::impl::prefix_generic< This, Container, Node >::node_type protected
Definition at line 24 of file prefix.hpp.
this_t
template<typename This , typename Container , typename Node > typedef This uxn::patl::impl::prefix_generic< This, Container, Node >::this_t private
Definition at line 21 of file prefix.hpp.
vertex
template<typename This , typename Container , typename Node > typedef cont_type::vertex uxn::patl::impl::prefix_generic< This, Container, Node >::vertex
Definition at line 31 of file prefix.hpp.
Constructor & Destructor Documentation
prefix_generic()
template<typename This , typename Container , typename Node > uxn::patl::impl::prefix_generic< This, Container, Node >::prefix_generic (const cont_type * cont, const node_type * q) inline
Definition at line 33 of file prefix.hpp.
        : cont_(cont)
        , q_(q)
    {
    }
Member Function Documentation
cont()
template<typename This , typename Container , typename Node > const cont_type * uxn::patl::impl::prefix_generic< This, Container, Node >::cont () const inline
Definition at line 83 of file prefix.hpp.
    {
        return cont_;
    }
References uxn::patl::impl::prefix_generic< This, Container, Node >::cont_.
get_parent_id()
template<typename This , typename Container , typename Node > word_t uxn::patl::impl::prefix_generic< This, Container, Node >::get_parent_id () const inline
Definition at line 63 of file prefix.hpp.
    {
        return q_->get_parent_id();
    }
References uxn::patl::impl::prefix_generic< This, Container, Node >::q_.
get_vertex()
template<typename This , typename Container , typename Node > vertex uxn::patl::impl::prefix_generic< This, Container, Node >::get_vertex () const inline
Definition at line 78 of file prefix.hpp.
    {
        return vertex(cont_, CSELF->get_parent(q_), q_->get_parent_id());
    }
References uxn::patl::impl::prefix_generic< This, Container, Node >::cont_, CSELF, and uxn::patl::impl::prefix_generic< This, Container, Node >::q_.
get_xtag()
template<typename This , typename Container , typename Node > word_t uxn::patl::impl::prefix_generic< This, Container, Node >::get_xtag (word_t id) const inline
Definition at line 58 of file prefix.hpp.
    {
        return q_->get_xtag(id);
    }
References uxn::patl::impl::prefix_generic< This, Container, Node >::q_.
go_parent()
template<typename This , typename Container , typename Node > void uxn::patl::impl::prefix_generic< This, Container, Node >::go_parent () inline
Definition at line 73 of file prefix.hpp.
    {
        q_ = CSELF->get_parent(q_);
    }
References CSELF, and uxn::patl::impl::prefix_generic< This, Container, Node >::q_.
go_xlink()
template<typename This , typename Container , typename Node > void uxn::patl::impl::prefix_generic< This, Container, Node >::go_xlink (word_t id) inline
Definition at line 68 of file prefix.hpp.
    {
        q_ = CSELF->get_xlink(q_, id);
    }
References CSELF, and uxn::patl::impl::prefix_generic< This, Container, Node >::q_.
is_root()
template<typename This , typename Container , typename Node > bool uxn::patl::impl::prefix_generic< This, Container, Node >::is_root () const inline
Definition at line 88 of file prefix.hpp.
    {
        return CSELF->get_parent(q_) == 0;
    }
References CSELF, and uxn::patl::impl::prefix_generic< This, Container, Node >::q_.
key() [1/2]
template<typename This , typename Container , typename Node > const_key_reference uxn::patl::impl::prefix_generic< This, Container, Node >::key () const inline
Definition at line 112 of file prefix.hpp.
    {
        return cont_->get_key(q_);
    }
References uxn::patl::impl::prefix_generic< This, Container, Node >::cont_, and uxn::patl::impl::prefix_generic< This, Container, Node >::q_.
key() [2/2]
template<typename This , typename Container , typename Node > const_key_reference uxn::patl::impl::prefix_generic< This, Container, Node >::key (word_t id) const inline
Definition at line 117 of file prefix.hpp.
    {
        return cont_->get_key(CSELF->get_xlink(q_, id));
    }
References uxn::patl::impl::prefix_generic< This, Container, Node >::cont_, CSELF, and uxn::patl::impl::prefix_generic< This, Container, Node >::q_.
leaf()
template<typename This , typename Container , typename Node > bool uxn::patl::impl::prefix_generic< This, Container, Node >::leaf (word_t id) const inline
Definition at line 122 of file prefix.hpp.
    {
        return q_->get_xtag(id) != 0;
    }
References uxn::patl::impl::prefix_generic< This, Container, Node >::q_.
length()
template<typename This , typename Container , typename Node > word_t uxn::patl::impl::prefix_generic< This, Container, Node >::length () const inline
Definition at line 107 of file prefix.hpp.
    {
        return skip() / bit_compare::bit_size;
    }
References uxn::patl::impl::prefix_generic< This, Container, Node >::skip().
node_uid()
template<typename This , typename Container , typename Node > word_t uxn::patl::impl::prefix_generic< This, Container, Node >::node_uid () const inline
Definition at line 53 of file prefix.hpp.
    {
        return reinterpret_cast<word_t>(q_);
    }
References uxn::patl::impl::prefix_generic< This, Container, Node >::q_.
operator const node_type *()
template<typename This , typename Container , typename Node > uxn::patl::impl::prefix_generic< This, Container, Node >::operator const node_type * () const inline
Definition at line 48 of file prefix.hpp.
    {
        return q_;
    }
References uxn::patl::impl::prefix_generic< This, Container, Node >::q_.
operator!=()
template<typename This , typename Container , typename Node > bool uxn::patl::impl::prefix_generic< This, Container, Node >::operator!= (const this_t & b) const inline
Definition at line 43 of file prefix.hpp.
    {
        return !operator==(b);
    }
References uxn::patl::impl::prefix_generic< This, Container, Node >::operator==().
operator==()
template<typename This , typename Container , typename Node > bool uxn::patl::impl::prefix_generic< This, Container, Node >::operator== (const this_t & b) const inline
Definition at line 39 of file prefix.hpp.
    {
        return q_ == b.q_;
    }
References uxn::patl::impl::prefix_generic< This, Container, Node >::q_.
Referenced by uxn::patl::impl::prefix_generic< This, Container, Node >::operator!=().
postorder_ascend()
template<typename This , typename Container , typename Node > template<typename Callback > void uxn::patl::impl::prefix_generic< This, Container, Node >::postorder_ascend (Callback & cb) inline private
Definition at line 173 of file prefix.hpp.
    {
        if (q_->get_parent_id())
        {
            cb.merge();
            q_ = CSELF->get_parent(q_);
            cb.update();
        }
        else
        {
            q_ = CSELF->get_parent(q_);
            if (q_->get_xtag(1))
                cb.incr();
            else
            {
                cb.push();
                q_ = CSELF->get_xlink(q_, 1);
                postorder_descend(cb);
            }
        }
    }
References CSELF, uxn::patl::impl::prefix_generic< This, Container, Node >::postorder_descend(), and uxn::patl::impl::prefix_generic< This, Container, Node >::q_.
Referenced by uxn::patl::impl::prefix_generic< This, Container, Node >::postorder_incr(), and uxn::patl::impl::prefix_generic< This, Container, Node >::postorder_init().
postorder_descend()
template<typename This , typename Container , typename Node > template<typename Callback > void uxn::patl::impl::prefix_generic< This, Container, Node >::postorder_descend (Callback & cb) inline private
Definition at line 156 of file prefix.hpp.
    {
        for (; ; q_ = CSELF->get_xlink(q_, 1))
        {
            while (!q_->get_xtag(0))
                q_ = CSELF->get_xlink(q_, 0);
            if (q_->get_xtag(1))
            {
                cb.incr();
                break;
            }
            else
                cb.push();
        }
    }
References CSELF, and uxn::patl::impl::prefix_generic< This, Container, Node >::q_.
Referenced by uxn::patl::impl::prefix_generic< This, Container, Node >::postorder_ascend(), and uxn::patl::impl::prefix_generic< This, Container, Node >::postorder_init().
postorder_incr()
template<typename This , typename Container , typename Node > template<typename Callback > void uxn::patl::impl::prefix_generic< This, Container, Node >::postorder_incr (Callback & cb) inline
Definition at line 142 of file prefix.hpp.
    {
        do postorder_ascend(cb);
        while (
            CSELF->get_parent(q_) &&
            (q_->get_skip() / bit_compare::bit_size ==
            CSELF->get_parent(q_)->get_skip() / bit_compare::bit_size ||
            cb.cond()));
        if (q_->get_skip() / bit_compare::bit_size == 0)
            *this = cont_->root_prefix();
    }
References uxn::patl::impl::prefix_generic< This, Container, Node >::cont_, CSELF, uxn::patl::impl::prefix_generic< This, Container, Node >::postorder_ascend(), and uxn::patl::impl::prefix_generic< This, Container, Node >::q_.
postorder_init()
template<typename This , typename Container , typename Node > template<typename Callback > void uxn::patl::impl::prefix_generic< This, Container, Node >::postorder_init (Callback & cb) inline
Definition at line 128 of file prefix.hpp.
    {
        postorder_descend(cb);
        while (
            CSELF->get_parent(q_) &&
            (q_->get_skip() / bit_compare::bit_size ==
            CSELF->get_parent(q_)->get_skip() / bit_compare::bit_size ||
            cb.cond()))
                postorder_ascend(cb);
        if (q_->get_skip() / bit_compare::bit_size == 0)
            *this = cont_->root_prefix();
    }
References uxn::patl::impl::prefix_generic< This, Container, Node >::cont_, CSELF, uxn::patl::impl::prefix_generic< This, Container, Node >::postorder_ascend(), uxn::patl::impl::prefix_generic< This, Container, Node >::postorder_descend(), and uxn::patl::impl::prefix_generic< This, Container, Node >::q_.
skip() [1/2]
template<typename This , typename Container , typename Node > word_t uxn::patl::impl::prefix_generic< This, Container, Node >::skip () const inline
Definition at line 93 of file prefix.hpp.
    {
        return q_->get_skip();
    }
References uxn::patl::impl::prefix_generic< This, Container, Node >::q_.
Referenced by uxn::patl::impl::prefix_generic< This, Container, Node >::length(), and uxn::patl::impl::prefix_generic< This, Container, Node >::symbol_limit().
skip() [2/2]
template<typename This , typename Container , typename Node > word_t uxn::patl::impl::prefix_generic< This, Container, Node >::skip (word_t id) const inline
Definition at line 97 of file prefix.hpp.
    {
        return CSELF->get_xlink(q_, id)->get_skip();
    }
References CSELF, and uxn::patl::impl::prefix_generic< This, Container, Node >::q_.
symbol_limit()
template<typename This , typename Container , typename Node > bool uxn::patl::impl::prefix_generic< This, Container, Node >::symbol_limit (word_t id) const inline
Definition at line 102 of file prefix.hpp.
    {
        return skip() / bit_compare::bit_size != skip(id) / bit_compare::bit_size;
    }
References uxn::patl::impl::prefix_generic< This, Container, Node >::skip().
Member Data Documentation
cont_
template<typename This , typename Container , typename Node > const cont_type* uxn::patl::impl::prefix_generic< This, Container, Node >::cont_ private
Definition at line 195 of file prefix.hpp.
Referenced by uxn::patl::impl::prefix_generic< This, Container, Node >::cont(), uxn::patl::impl::prefix_generic< This, Container, Node >::get_vertex(), uxn::patl::impl::prefix_generic< This, Container, Node >::key(), uxn::patl::impl::prefix_generic< This, Container, Node >::postorder_incr(), and uxn::patl::impl::prefix_generic< This, Container, Node >::postorder_init().
q_
template<typename This , typename Container , typename Node > const node_type* uxn::patl::impl::prefix_generic< This, Container, Node >::q_ private
Definition at line 196 of file prefix.hpp.
Referenced by uxn::patl::impl::prefix_generic< This, Container, Node >::get_parent_id(), uxn::patl::impl::prefix_generic< This, Container, Node >::get_vertex(), uxn::patl::impl::prefix_generic< This, Container, Node >::get_xtag(), uxn::patl::impl::prefix_generic< This, Container, Node >::go_parent(), uxn::patl::impl::prefix_generic< This, Container, Node >::go_xlink(), uxn::patl::impl::prefix_generic< This, Container, Node >::is_root(), uxn::patl::impl::prefix_generic< This, Container, Node >::key(), uxn::patl::impl::prefix_generic< This, Container, Node >::leaf(), uxn::patl::impl::prefix_generic< This, Container, Node >::node_uid(), uxn::patl::impl::prefix_generic< This, Container, Node >::operator const node_type *(), uxn::patl::impl::prefix_generic< This, Container, Node >::operator==(), uxn::patl::impl::prefix_generic< This, Container, Node >::postorder_ascend(), uxn::patl::impl::prefix_generic< This, Container, Node >::postorder_descend(), uxn::patl::impl::prefix_generic< This, Container, Node >::postorder_incr(), uxn::patl::impl::prefix_generic< This, Container, Node >::postorder_init(), and uxn::patl::impl::prefix_generic< This, Container, Node >::skip().
The documentation for this class was generated from the following file:
uxn/patl/impl/prefix.hpp