PATL: uxn::patl::impl::vertex_generic< Algorithm > Class Template Reference
uxn::patl::impl::vertex_generic< Algorithm > Class Template Reference
#include <vertex.hpp>
Public Types
typedef super const_vertex
typedef algorithm::cont_type cont_type
typedef algorithm::key_type key_type
typedef algorithm::value_type value_type
Public Types inherited from uxn::patl::impl::const_vertex_generic< Algorithm >
typedef this_t const_vertex
typedef algorithm::cont_type cont_type
typedef algorithm::key_type key_type
typedef algorithm::const_key_reference const_key_reference
typedef algorithm::value_type value_type
Public Member Functions
vertex_generic (const algorithm &pal=algorithm())
vertex_generic (const cont_type *cont, const node_type *q, word_t qid)
vertex_generic (const cont_type *cont, word_t qq)
vertex_generic (const super &vtx)
operator const const_vertex & () const
operator const_vertex & ()
operator algorithm & ()
iterator begin ()
iterator end ()
reverse_iterator rbegin ()
reverse_iterator rend ()
postorder_iterator postorder_begin ()
postorder_iterator postorder_end ()
preorder_iterator preorder_begin ()
preorder_iterator preorder_begin (word_t limit)
preorder_iterator preorder_end ()
value_type & value ()
value_type & parent_value ()
this_t sibling ()
Public Member Functions inherited from uxn::patl::impl::const_vertex_generic< Algorithm >
const_vertex_generic (const algorithm &pal=algorithm())
const_vertex_generic (const cont_type *cont, const node_type *q, word_t qid)
const_vertex_generic (const cont_type *cont, word_t qq)
bool operator== (const this_t &r) const
bool operator!= (const this_t &r) const
bool operator< (const this_t &r) const
operator const algorithm & () const
prefix get_prefix () const
word_t compact () const
word_t node_q_uid () const
word_t node_p_uid () const
const_iterator begin () const
const_iterator end () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
const_postorder_iterator postorder_begin () const
const_postorder_iterator postorder_end () const
const_preorder_iterator preorder_begin () const
const_preorder_iterator preorder_begin (word_t limit) const
const_preorder_iterator preorder_end () const
bool the_end () const
const_key_reference key () const
const_key_reference parent_key () const
word_t prefix_length () const
const value_type & value () const
const value_type & parent_value () const
word_t skip () const
word_t next_skip () const
only for !leaf()
this_t sibling () const
bool limited (word_t limit) const
template<word_t Side>
void descend ()
trie descend to the leaves
template<word_t Side, typename Callback >
void descend (Callback &cb)
template<word_t Side>
void descend (word_t limit)
trie descend to the leaves limited by
template<word_t Side, typename Callback >
void descend (word_t limit, Callback &cb)
template<word_t Side>
void move_subtree ()
generic part of all move functions
template<word_t Side, typename Callback >
void move_subtree (Callback &cb)
template<word_t Side>
void move ()
move to the next leaf
word_t mismatch (const key_type &key, word_t prefixLen=~word_t(0))
word_t get_qid () const
word_t get_qtag () const
word_t get_parent_id () const
void toggle ()
void iterate (word_t id)
void ascend ()
void ascend (sword_t prefixLen)
void ascend_less (sword_t prefixLen)
const cont_type * cont () const
bit_compare bit_comp () const
Protected Types
typedef const_vertex_generic< Algorithm > super
typedef vertex_generic< Algorithm > this_t
typedef Algorithm algorithm
typedef algorithm::node_type node_type
typedef cont_type::bit_compare bit_compare
typedef cont_type::prefix prefix
typedef cont_type::preorder_iterator preorder_iterator
typedef cont_type::postorder_iterator postorder_iterator
typedef cont_type::iterator iterator
typedef cont_type::reverse_iterator reverse_iterator
Protected Types inherited from uxn::patl::impl::const_vertex_generic< Algorithm >
typedef const_vertex_generic< Algorithm > this_t
typedef Algorithm algorithm
typedef algorithm::node_type node_type
typedef cont_type::bit_compare bit_compare
typedef cont_type::prefix prefix
typedef cont_type::const_preorder_iterator const_preorder_iterator
typedef cont_type::const_postorder_iterator const_postorder_iterator
typedef cont_type::preorder_iterator preorder_iterator
typedef cont_type::postorder_iterator postorder_iterator
typedef cont_type::const_iterator const_iterator
typedef cont_type::iterator iterator
typedef cont_type::const_reverse_iterator const_reverse_iterator
typedef cont_type::reverse_iterator reverse_iterator
Additional Inherited Members
Protected Attributes inherited from uxn::patl::impl::const_vertex_generic< Algorithm >
algorithm pal_
Detailed Description
template<typename Algorithm>
class uxn::patl::impl::vertex_generic< Algorithm >
Definition at line 346 of file vertex.hpp.
Member Typedef Documentation
algorithm
template<typename Algorithm > typedef Algorithm uxn::patl::impl::vertex_generic< Algorithm >::algorithm protected
Definition at line 352 of file vertex.hpp.
bit_compare
template<typename Algorithm > typedef cont_type::bit_compare uxn::patl::impl::vertex_generic< Algorithm >::bit_compare protected
Definition at line 360 of file vertex.hpp.
const_vertex
template<typename Algorithm > typedef super uxn::patl::impl::vertex_generic< Algorithm >::const_vertex
Definition at line 355 of file vertex.hpp.
cont_type
template<typename Algorithm > typedef algorithm::cont_type uxn::patl::impl::vertex_generic< Algorithm >::cont_type
Definition at line 356 of file vertex.hpp.
iterator
template<typename Algorithm > typedef cont_type::iterator uxn::patl::impl::vertex_generic< Algorithm >::iterator protected
Definition at line 364 of file vertex.hpp.
key_type
template<typename Algorithm > typedef algorithm::key_type uxn::patl::impl::vertex_generic< Algorithm >::key_type
Definition at line 368 of file vertex.hpp.
node_type
template<typename Algorithm > typedef algorithm::node_type uxn::patl::impl::vertex_generic< Algorithm >::node_type protected
Definition at line 359 of file vertex.hpp.
postorder_iterator
template<typename Algorithm > typedef cont_type::postorder_iterator uxn::patl::impl::vertex_generic< Algorithm >::postorder_iterator protected
Definition at line 363 of file vertex.hpp.
prefix
template<typename Algorithm > typedef cont_type::prefix uxn::patl::impl::vertex_generic< Algorithm >::prefix protected
Definition at line 361 of file vertex.hpp.
preorder_iterator
template<typename Algorithm > typedef cont_type::preorder_iterator uxn::patl::impl::vertex_generic< Algorithm >::preorder_iterator protected
Definition at line 362 of file vertex.hpp.
reverse_iterator
template<typename Algorithm > typedef cont_type::reverse_iterator uxn::patl::impl::vertex_generic< Algorithm >::reverse_iterator protected
Definition at line 365 of file vertex.hpp.
super
template<typename Algorithm > typedef const_vertex_generic<Algorithm> uxn::patl::impl::vertex_generic< Algorithm >::super protected
Definition at line 350 of file vertex.hpp.
this_t
template<typename Algorithm > typedef vertex_generic<Algorithm> uxn::patl::impl::vertex_generic< Algorithm >::this_t protected
Definition at line 351 of file vertex.hpp.
value_type
template<typename Algorithm > typedef algorithm::value_type uxn::patl::impl::vertex_generic< Algorithm >::value_type
Definition at line 369 of file vertex.hpp.
Constructor & Destructor Documentation
vertex_generic() [1/4]
template<typename Algorithm > uxn::patl::impl::vertex_generic< Algorithm >::vertex_generic (const algorithm & pal = algorithm()) inline explicit
Definition at line 371 of file vertex.hpp.
        : super(pal)
    {
    }
vertex_generic() [2/4]
template<typename Algorithm > uxn::patl::impl::vertex_generic< Algorithm >::vertex_generic (const cont_type * cont, const node_type * q, word_t qid) inline
Definition at line 376 of file vertex.hpp.
        : super(cont, q, qid)
    {
    }
vertex_generic() [3/4]
template<typename Algorithm > uxn::patl::impl::vertex_generic< Algorithm >::vertex_generic (const cont_type * cont, word_t qq) inline
Definition at line 381 of file vertex.hpp.
        : super(cont, qq)
    {
    }
vertex_generic() [4/4]
template<typename Algorithm > uxn::patl::impl::vertex_generic< Algorithm >::vertex_generic (const super & vtx) inline
Definition at line 386 of file vertex.hpp.
        : super(vtx)
    {
    }
Member Function Documentation
begin()
template<typename Algorithm > iterator uxn::patl::impl::vertex_generic< Algorithm >::begin () inline
Definition at line 405 of file vertex.hpp.
    {
        return iterator(*postorder_begin());
    }
References uxn::patl::impl::vertex_generic< Algorithm >::postorder_begin().
Referenced by uxn::patl::impl::vertex_generic< Algorithm >::rend().
end()
template<typename Algorithm > iterator uxn::patl::impl::vertex_generic< Algorithm >::end () inline
Definition at line 410 of file vertex.hpp.
    {
        return iterator(*postorder_end());
    }
References uxn::patl::impl::vertex_generic< Algorithm >::postorder_end().
Referenced by uxn::patl::impl::vertex_generic< Algorithm >::rbegin().
operator algorithm &()
template<typename Algorithm > uxn::patl::impl::vertex_generic< Algorithm >::operator algorithm & () inline
Definition at line 400 of file vertex.hpp.
    {
        return this->pal_;
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
operator const const_vertex &()
template<typename Algorithm > uxn::patl::impl::vertex_generic< Algorithm >::operator const const_vertex & () const inline
Definition at line 391 of file vertex.hpp.
    {
        return *this;
    }
operator const_vertex &()
template<typename Algorithm > uxn::patl::impl::vertex_generic< Algorithm >::operator const_vertex & () inline
Definition at line 395 of file vertex.hpp.
    {
        return *this;
    }
parent_value()
template<typename Algorithm > value_type & uxn::patl::impl::vertex_generic< Algorithm >::parent_value () inline
Definition at line 481 of file vertex.hpp.
    {
        return this->pal_.get_value(this->pal_.get_q());
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
postorder_begin()
template<typename Algorithm > postorder_iterator uxn::patl::impl::vertex_generic< Algorithm >::postorder_begin () inline
Definition at line 425 of file vertex.hpp.
    {
        this_t vtx(*this);
        if (this->compact())
            vtx.template descend<0>();
        else
            vtx.toggle();
        return postorder_iterator(vtx);
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::compact(), and uxn::patl::impl::const_vertex_generic< Algorithm >::toggle().
Referenced by uxn::patl::impl::vertex_generic< Algorithm >::begin(), and uxn::patl::impl::trie_generic< T, 0 >::del_tree().
postorder_end()
template<typename Algorithm > postorder_iterator uxn::patl::impl::vertex_generic< Algorithm >::postorder_end () inline
Definition at line 435 of file vertex.hpp.
    {
        this_t vtx(*this);
        if (this->pal_.get_q())
            vtx.template move<1>();
        else
            vtx.toggle();
        return postorder_iterator(vtx);
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_, and uxn::patl::impl::const_vertex_generic< Algorithm >::toggle().
Referenced by uxn::patl::impl::trie_generic< T, 0 >::del_tree(), and uxn::patl::impl::vertex_generic< Algorithm >::end().
preorder_begin() [1/2]
template<typename Algorithm > preorder_iterator uxn::patl::impl::vertex_generic< Algorithm >::preorder_begin () inline
Definition at line 445 of file vertex.hpp.
    {
        const node_type *q = this->pal_.get_q();
        return preorder_iterator(this_t(this->cont(), q, q ? this->get_qid() : 1));
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::cont(), uxn::patl::impl::const_vertex_generic< Algorithm >::get_qid(), and uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
preorder_begin() [2/2]
template<typename Algorithm > preorder_iterator uxn::patl::impl::vertex_generic< Algorithm >::preorder_begin (word_t limit) inline
Definition at line 450 of file vertex.hpp.
    {
        this_t vtx(*this);
        if (this->compact())
            vtx.template descend<0>(limit);
        else
            vtx.toggle();
        return preorder_iterator(vtx);
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::compact(), and uxn::patl::impl::const_vertex_generic< Algorithm >::toggle().
preorder_end()
template<typename Algorithm > preorder_iterator uxn::patl::impl::vertex_generic< Algorithm >::preorder_end () inline
Definition at line 460 of file vertex.hpp.
    {
        if (this->pal_.get_q())
        {
            preorder_iterator pit(*this);
            pit.next_subtree();
            return pit;
        }
        else
        {
            this_t vtx(*this);
            vtx.toggle();
            return preorder_iterator(vtx);
        }
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_, and uxn::patl::impl::const_vertex_generic< Algorithm >::toggle().
rbegin()
template<typename Algorithm > reverse_iterator uxn::patl::impl::vertex_generic< Algorithm >::rbegin () inline
Definition at line 415 of file vertex.hpp.
    {
        return reverse_iterator(end());
    }
References uxn::patl::impl::vertex_generic< Algorithm >::end().
rend()
template<typename Algorithm > reverse_iterator uxn::patl::impl::vertex_generic< Algorithm >::rend () inline
Definition at line 420 of file vertex.hpp.
    {
        return reverse_iterator(begin());
    }
References uxn::patl::impl::vertex_generic< Algorithm >::begin().
sibling()
template<typename Algorithm > this_t uxn::patl::impl::vertex_generic< Algorithm >::sibling () inline
Definition at line 486 of file vertex.hpp.
    {
        return this_t(this->pal_.sibling());
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
Referenced by lz_compress().
value()
template<typename Algorithm > value_type & uxn::patl::impl::vertex_generic< Algorithm >::value () inline
Definition at line 476 of file vertex.hpp.
    {
        return this->pal_.get_value();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::pal_.
The documentation for this class was generated from the following file:
uxn/patl/impl/vertex.hpp