PATL: uxn::patl::impl::generator_base< Derived, Elem > Class Template Reference
uxn::patl::impl::generator_base< Derived, Elem > Class Template Reference
#include <generator.hpp>
Public Types
typedef Derived this_t
typedef Elem elem_t
Public Member Functions
generator_base ()
this_t replica () const
void init ()
bool next ()
const elem_t & value ()
Protected Attributes
int generator_line
elem_t generator_value
Detailed Description
template<typename Derived, typename Elem>
class uxn::patl::impl::generator_base< Derived, Elem >
Definition at line 25 of file generator.hpp.
Member Typedef Documentation
elem_t
template<typename Derived , typename Elem > typedef Elem uxn::patl::impl::generator_base< Derived, Elem >::elem_t
Definition at line 29 of file generator.hpp.
this_t
template<typename Derived , typename Elem > typedef Derived uxn::patl::impl::generator_base< Derived, Elem >::this_t
Definition at line 28 of file generator.hpp.
Constructor & Destructor Documentation
generator_base()
template<typename Derived , typename Elem > uxn::patl::impl::generator_base< Derived, Elem >::generator_base () inline
Definition at line 31 of file generator.hpp.
        : generator_line(0)
    {
    }
Member Function Documentation
init()
template<typename Derived , typename Elem > void uxn::patl::impl::generator_base< Derived, Elem >::init () inline
Definition at line 41 of file generator.hpp.
    {
        generator_line = 0;
    }
References uxn::patl::impl::generator_base< Derived, Elem >::generator_line.
next()
template<typename Derived , typename Elem > bool uxn::patl::impl::generator_base< Derived, Elem >::next () inline
Definition at line 46 of file generator.hpp.
    {
        int generator_cur_line = generator_line;
        generator_line = 0;
        static_cast<this_t*>(this)->generate_value(generator_cur_line);
        return 0 != generator_line;
    }
References uxn::patl::impl::generator_base< Derived, Elem >::generator_line.
Referenced by uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::init(), and uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::resize().
replica()
template<typename Derived , typename Elem > this_t uxn::patl::impl::generator_base< Derived, Elem >::replica () const inline
Definition at line 36 of file generator.hpp.
    {
        return *static_cast<const this_t*>(this);
    }
value()
template<typename Derived , typename Elem > const elem_t & uxn::patl::impl::generator_base< Derived, Elem >::value () inline
Definition at line 54 of file generator.hpp.
    {
        return generator_value;
    }
References uxn::patl::impl::generator_base< Derived, Elem >::generator_value.
Referenced by uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::init(), and uxn::patl::unordered_map< Key, Datum, HashFun, Pred, Alloc >::resize().
Member Data Documentation
generator_line
template<typename Derived , typename Elem > int uxn::patl::impl::generator_base< Derived, Elem >::generator_line protected
Definition at line 60 of file generator.hpp.
Referenced by uxn::patl::impl::generator_base< Derived, Elem >::init(), and uxn::patl::impl::generator_base< Derived, Elem >::next().
generator_value
template<typename Derived , typename Elem > elem_t uxn::patl::impl::generator_base< Derived, Elem >::generator_value protected
Definition at line 61 of file generator.hpp.
Referenced by uxn::patl::impl::generator_base< Derived, Elem >::value().
The documentation for this class was generated from the following file:
uxn/patl/impl/generator.hpp