PATL: uxn::patl::impl::assoc_generic< This, T, 0 > Class Template Reference
uxn::patl::impl::assoc_generic< This, T, 0 > Class Template Reference
#include <assoc_generic.hpp>
Classes
class const_partimator
class const_reverse_iterator
class partimator
class reverse_iterator
Public Types
typedef T::prefix prefix
typedef const_vertex_generic< algorithm > const_vertex
typedef vertex_generic< algorithm > vertex
typedef const_preorder_iterator_generic< const_vertex > const_preorder_iterator
typedef const_postorder_iterator_generic< const_vertex > const_postorder_iterator
typedef preorder_iterator_generic< vertex > preorder_iterator
typedef postorder_iterator_generic< vertex > postorder_iterator
typedef T::key_type key_type
typedef T::value_type value_type
typedef T::bit_compare bit_compare
typedef T::allocator_type allocator_type
typedef const value_type * const_pointer
typedef const value_type & const_reference
typedef value_type * pointer
typedef value_type & reference
typedef allocator_type::difference_type difference_type
typedef word_t size_type
typedef const_iterator_generic< const_postorder_iterator > const_iterator
typedef iterator_generic< postorder_iterator > iterator
Public Member Functions
assoc_generic ()
assoc_generic (const bit_compare &bit_comp)
const_iterator begin () const
iterator begin ()
const_iterator end () const
iterator end ()
const_reverse_iterator rbegin () const
reverse_iterator rbegin ()
const_reverse_iterator rend () const
reverse_iterator rend ()
template<typename Decision >
const_partimator< Decision > begin (const Decision &decis) const
template<typename Decision >
partimator< Decision > begin (const Decision &decis)
template<typename Decision >
const_partimator< Decision > end (const Decision &decis) const
template<typename Decision >
partimator< Decision > end (const Decision &decis)
const_iterator find (const key_type &key) const
iterator find (const key_type &key)
const_iterator lower_bound (const key_type &key, word_t prefixLen=~word_t(0)) const
iterator lower_bound (const key_type &key, word_t prefixLen=~word_t(0))
const_iterator upper_bound (const key_type &key, word_t prefixLen=~word_t(0)) const
iterator upper_bound (const key_type &key, word_t prefixLen=~word_t(0))
const_iter_range equal_range (const key_type &key, word_t prefix_len=~word_t(0)) const
iter_range equal_range (const key_type &key, word_t prefix_len=~word_t(0))
size_type count (const key_type &key, word_t prefixLen=~word_t(0)) const
void change_root (vertex &vtx)
bool empty () const
const_vertex root () const
vertex root ()
prefix root_prefix () const
bit_compare bit_comp () const
Static Public Attributes
static const word_t N_ = 0
Protected Types
typedef T::algorithm algorithm
typedef T::node_type node_type
Protected Attributes
node_type * root_
bit_compare bit_comp_
Private Types
typedef This this_t
typedef std::pair< const_iterator, const_iterator > const_iter_range
typedef std::pair< iterator, iterator > iter_range
Detailed Description
template<typename This, typename T>
class uxn::patl::impl::assoc_generic< This, T, 0 >
Definition at line 96 of file assoc_generic.hpp.
Member Typedef Documentation
algorithm
template<typename This , typename T > typedef T::algorithm uxn::patl::impl::assoc_generic< This, T, 0 >::algorithm protected
Definition at line 101 of file assoc_generic.hpp.
allocator_type
template<typename This , typename T > typedef T::allocator_type uxn::patl::impl::assoc_generic< This, T, 0 >::allocator_type
Definition at line 115 of file assoc_generic.hpp.
bit_compare
template<typename This , typename T > typedef T::bit_compare uxn::patl::impl::assoc_generic< This, T, 0 >::bit_compare
Definition at line 114 of file assoc_generic.hpp.
const_iter_range
template<typename This , typename T > typedef std::pair<const_iterator, const_iterator> uxn::patl::impl::assoc_generic< This, T, 0 >::const_iter_range private
Definition at line 357 of file assoc_generic.hpp.
const_iterator
template<typename This , typename T > typedef const_iterator_generic<const_postorder_iterator> uxn::patl::impl::assoc_generic< This, T, 0 >::const_iterator
Definition at line 136 of file assoc_generic.hpp.
const_pointer
template<typename This , typename T > typedef const value_type* uxn::patl::impl::assoc_generic< This, T, 0 >::const_pointer
Definition at line 116 of file assoc_generic.hpp.
const_postorder_iterator
template<typename This , typename T > typedef const_postorder_iterator_generic<const_vertex> uxn::patl::impl::assoc_generic< This, T, 0 >::const_postorder_iterator
Definition at line 109 of file assoc_generic.hpp.
const_preorder_iterator
template<typename This , typename T > typedef const_preorder_iterator_generic<const_vertex> uxn::patl::impl::assoc_generic< This, T, 0 >::const_preorder_iterator
Definition at line 108 of file assoc_generic.hpp.
const_reference
template<typename This , typename T > typedef const value_type& uxn::patl::impl::assoc_generic< This, T, 0 >::const_reference
Definition at line 117 of file assoc_generic.hpp.
const_vertex
template<typename This , typename T > typedef const_vertex_generic<algorithm> uxn::patl::impl::assoc_generic< This, T, 0 >::const_vertex
Definition at line 106 of file assoc_generic.hpp.
difference_type
template<typename This , typename T > typedef allocator_type::difference_type uxn::patl::impl::assoc_generic< This, T, 0 >::difference_type
Definition at line 120 of file assoc_generic.hpp.
iter_range
template<typename This , typename T > typedef std::pair<iterator, iterator> uxn::patl::impl::assoc_generic< This, T, 0 >::iter_range private
Definition at line 358 of file assoc_generic.hpp.
iterator
template<typename This , typename T > typedef iterator_generic<postorder_iterator> uxn::patl::impl::assoc_generic< This, T, 0 >::iterator
Definition at line 137 of file assoc_generic.hpp.
key_type
template<typename This , typename T > typedef T::key_type uxn::patl::impl::assoc_generic< This, T, 0 >::key_type
Definition at line 112 of file assoc_generic.hpp.
node_type
template<typename This , typename T > typedef T::node_type uxn::patl::impl::assoc_generic< This, T, 0 >::node_type protected
Definition at line 102 of file assoc_generic.hpp.
pointer
template<typename This , typename T > typedef value_type* uxn::patl::impl::assoc_generic< This, T, 0 >::pointer
Definition at line 118 of file assoc_generic.hpp.
postorder_iterator
template<typename This , typename T > typedef postorder_iterator_generic<vertex> uxn::patl::impl::assoc_generic< This, T, 0 >::postorder_iterator
Definition at line 111 of file assoc_generic.hpp.
prefix
template<typename This , typename T > typedef T::prefix uxn::patl::impl::assoc_generic< This, T, 0 >::prefix
Definition at line 105 of file assoc_generic.hpp.
preorder_iterator
template<typename This , typename T > typedef preorder_iterator_generic<vertex> uxn::patl::impl::assoc_generic< This, T, 0 >::preorder_iterator
Definition at line 110 of file assoc_generic.hpp.
reference
template<typename This , typename T > typedef value_type& uxn::patl::impl::assoc_generic< This, T, 0 >::reference
Definition at line 119 of file assoc_generic.hpp.
size_type
template<typename This , typename T > typedef word_t uxn::patl::impl::assoc_generic< This, T, 0 >::size_type
Definition at line 121 of file assoc_generic.hpp.
this_t
template<typename This , typename T > typedef This uxn::patl::impl::assoc_generic< This, T, 0 >::this_t private
Definition at line 98 of file assoc_generic.hpp.
value_type
template<typename This , typename T > typedef T::value_type uxn::patl::impl::assoc_generic< This, T, 0 >::value_type
Definition at line 113 of file assoc_generic.hpp.
vertex
template<typename This , typename T > typedef vertex_generic<algorithm> uxn::patl::impl::assoc_generic< This, T, 0 >::vertex
Definition at line 107 of file assoc_generic.hpp.
Constructor & Destructor Documentation
assoc_generic() [1/2]
template<typename This , typename T > uxn::patl::impl::assoc_generic< This, T, 0 >::assoc_generic () inline
Definition at line 125 of file assoc_generic.hpp.
        : root_(0)
    {
    }
assoc_generic() [2/2]
template<typename This , typename T > uxn::patl::impl::assoc_generic< This, T, 0 >::assoc_generic (const bit_compare & bit_comp) inline explicit
Definition at line 130 of file assoc_generic.hpp.
        : root_(0)
        , bit_comp_(bit_comp)
    {
    }
Member Function Documentation
begin() [1/4]
template<typename This , typename T > iterator uxn::patl::impl::assoc_generic< This, T, 0 >::begin () inline
Definition at line 143 of file assoc_generic.hpp.
    {
        return root().begin();
    }
begin() [2/4]
template<typename This , typename T > const_iterator uxn::patl::impl::assoc_generic< This, T, 0 >::begin () const inline
Definition at line 139 of file assoc_generic.hpp.
    {
        return root().begin();
    }
begin() [3/4]
template<typename This , typename T > template<typename Decision > partimator< Decision > uxn::patl::impl::assoc_generic< This, T, 0 >::begin (const Decision & decis) inline
Definition at line 257 of file assoc_generic.hpp.
    {
        vertex vtx(root());
        if (!root_)
            vtx.toggle();
        return partimator<Decision>(decis, vtx);
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::toggle().
begin() [4/4]
template<typename This , typename T > template<typename Decision > const_partimator< Decision > uxn::patl::impl::assoc_generic< This, T, 0 >::begin (const Decision & decis) const inline
Definition at line 249 of file assoc_generic.hpp.
    {
        const_vertex vtx(root());
        if (!root_)
            vtx.toggle();
        return const_partimator<Decision>(decis, vtx);
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::toggle().
bit_comp()
template<typename This , typename T > bit_compare uxn::patl::impl::assoc_generic< This, T, 0 >::bit_comp () const inline
Definition at line 443 of file assoc_generic.hpp.
    {
        return bit_comp_;
    }
change_root()
template<typename This , typename T > void uxn::patl::impl::assoc_generic< This, T, 0 >::change_root (vertex & vtx) inline
Definition at line 413 of file assoc_generic.hpp.
    {
        node_type *p = static_cast<algorithm&>(vtx).get_p();
        if (p != root_)
        {
            p->make_root(root_);
            root_ = p;
        }
    }
count()
template<typename This , typename T > size_type uxn::patl::impl::assoc_generic< This, T, 0 >::count (const key_type & key, word_t prefixLen = ~word_t(0)) const inline
Definition at line 406 of file assoc_generic.hpp.
    {
        const_iter_range pcc(equal_range(key, prefixLen));
        return std::distance(pcc.first, pcc.second);
    }
empty()
template<typename This , typename T > bool uxn::patl::impl::assoc_generic< This, T, 0 >::empty () const inline
Definition at line 423 of file assoc_generic.hpp.
    {
        return !root_;
    }
end() [1/4]
template<typename This , typename T > iterator uxn::patl::impl::assoc_generic< This, T, 0 >::end () inline
Definition at line 152 of file assoc_generic.hpp.
    {
        return root().end();
    }
end() [2/4]
template<typename This , typename T > const_iterator uxn::patl::impl::assoc_generic< This, T, 0 >::end () const inline
Definition at line 148 of file assoc_generic.hpp.
    {
        return root().end();
    }
end() [3/4]
template<typename This , typename T > template<typename Decision > partimator< Decision > uxn::patl::impl::assoc_generic< This, T, 0 >::end (const Decision & decis) inline
Definition at line 273 of file assoc_generic.hpp.
    {
        vertex vtx(root());
        vtx.toggle();
        return partimator<Decision>(decis, vtx);
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::toggle().
end() [4/4]
template<typename This , typename T > template<typename Decision > const_partimator< Decision > uxn::patl::impl::assoc_generic< This, T, 0 >::end (const Decision & decis) const inline
Definition at line 266 of file assoc_generic.hpp.
    {
        const_vertex vtx(root());
        vtx.toggle();
        return const_partimator<Decision>(decis, vtx);
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::toggle().
equal_range() [1/2]
template<typename This , typename T > iter_range uxn::patl::impl::assoc_generic< This, T, 0 >::equal_range (const key_type & key, word_t prefix_len = ~word_t(0)) inline
Definition at line 383 of file assoc_generic.hpp.
    {
        vertex vtx(root());
        if (root_)
        {
            const word_t len = vtx.mismatch(key, prefix_len);
            vertex lower(vtx);
            lower.template descend<0>();
            if (len < prefix_len)
                return iter_range(
                    iterator(lower),
                    iterator(lower));
            vtx.template move<1>();
            vtx.template descend<0>();
            return iter_range(
                iterator(lower),
                iterator(vtx));
        }
        return iter_range(end(), end());
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::mismatch().
equal_range() [2/2]
template<typename This , typename T > const_iter_range uxn::patl::impl::assoc_generic< This, T, 0 >::equal_range (const key_type & key, word_t prefix_len = ~word_t(0)) const inline
Definition at line 361 of file assoc_generic.hpp.
    {
        const_vertex vtx(root());
        if (root_)
        {
            const word_t len = vtx.mismatch(key, prefix_len);
            vertex lower(vtx);
            lower.template descend<0>();
            if (len < prefix_len)
                return const_iter_range(
                    const_iterator(lower),
                    const_iterator(lower));
            vtx.template move<1>();
            vtx.template descend<0>();
            return const_iter_range(
                const_iterator(lower),
                const_iterator(vtx));
        }
        return const_iter_range(end(), end());
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::mismatch().
find() [1/2]
template<typename This , typename T > iterator uxn::patl::impl::assoc_generic< This, T, 0 >::find (const key_type & key) inline
Definition at line 290 of file assoc_generic.hpp.
    {
        vertex vtx(root());
        if (root_ && ~word_t(0) == vtx.mismatch(key))
            return iterator(vtx);
        return end();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::mismatch().
find() [2/2]
template<typename This , typename T > const_iterator uxn::patl::impl::assoc_generic< This, T, 0 >::find (const key_type & key) const inline
Definition at line 281 of file assoc_generic.hpp.
    {
        const_vertex vtx(root());
        // if number of first mismatching bit end at infinity
        if (root_ && ~word_t(0) == vtx.mismatch(key))
            // then return iterator on finding
            return const_iterator(vtx);
        return end();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::mismatch().
lower_bound() [1/2]
template<typename This , typename T > iterator uxn::patl::impl::assoc_generic< This, T, 0 >::lower_bound (const key_type & key, word_t prefixLen = ~word_t(0)) inline
Definition at line 312 of file assoc_generic.hpp.
    {
        vertex vtx(root());
        // find a nearest match
        if (root_)
        {
            vtx.mismatch(key, prefixLen);
            vtx.template descend<0>();
            return iterator(vtx);
        }
        return end();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::mismatch().
lower_bound() [2/2]
template<typename This , typename T > const_iterator uxn::patl::impl::assoc_generic< This, T, 0 >::lower_bound (const key_type & key, word_t prefixLen = ~word_t(0)) const inline
Definition at line 298 of file assoc_generic.hpp.
    {
        const_vertex vtx(root());
        // find a nearest match
        if (root_)
        {
            vtx.mismatch(key, prefixLen);
            vtx.template descend<0>();
            return const_iterator(vtx);
        }
        return end();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::mismatch().
rbegin() [1/2]
template<typename This , typename T > reverse_iterator uxn::patl::impl::assoc_generic< This, T, 0 >::rbegin () inline
Definition at line 181 of file assoc_generic.hpp.
    {
        return root().rbegin();
    }
rbegin() [2/2]
template<typename This , typename T > const_reverse_iterator uxn::patl::impl::assoc_generic< This, T, 0 >::rbegin () const inline
Definition at line 177 of file assoc_generic.hpp.
    {
        return root().rbegin();
    }
rend() [1/2]
template<typename This , typename T > reverse_iterator uxn::patl::impl::assoc_generic< This, T, 0 >::rend () inline
Definition at line 190 of file assoc_generic.hpp.
    {
        return root().rend();
    }
rend() [2/2]
template<typename This , typename T > const_reverse_iterator uxn::patl::impl::assoc_generic< This, T, 0 >::rend () const inline
Definition at line 186 of file assoc_generic.hpp.
    {
        return root().rend();
    }
root() [1/2]
template<typename This , typename T > vertex uxn::patl::impl::assoc_generic< This, T, 0 >::root () inline
Definition at line 432 of file assoc_generic.hpp.
    {
        return vertex(CSELF, root_, 0);
    }
References CSELF.
root() [2/2]
template<typename This , typename T > const_vertex uxn::patl::impl::assoc_generic< This, T, 0 >::root () const inline
Definition at line 428 of file assoc_generic.hpp.
    {
        return const_vertex(CSELF, root_, 0);
    }
References CSELF.
root_prefix()
template<typename This , typename T > prefix uxn::patl::impl::assoc_generic< This, T, 0 >::root_prefix () const inline
Definition at line 437 of file assoc_generic.hpp.
    {
        return prefix(CSELF, root_);
    }
References CSELF.
upper_bound() [1/2]
template<typename This , typename T > iterator uxn::patl::impl::assoc_generic< This, T, 0 >::upper_bound (const key_type & key, word_t prefixLen = ~word_t(0)) inline
Definition at line 341 of file assoc_generic.hpp.
    {
        vertex vtx(root());
        if (root_)
        {
            if (vtx.mismatch(key, prefixLen) >= prefixLen)
                vtx.template move<1>();
            vtx.template descend<0>();
            return iterator(vtx);
        }
        return end();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::mismatch().
upper_bound() [2/2]
template<typename This , typename T > const_iterator uxn::patl::impl::assoc_generic< This, T, 0 >::upper_bound (const key_type & key, word_t prefixLen = ~word_t(0)) const inline
Definition at line 327 of file assoc_generic.hpp.
    {
        const_vertex vtx(root());
        if (root_)
        {
            if (vtx.mismatch(key, prefixLen) >= prefixLen)
                vtx.template move<1>();
            vtx.template descend<0>();
            return const_iterator(vtx);
        }
        return end();
    }
References uxn::patl::impl::const_vertex_generic< Algorithm >::mismatch().
Member Data Documentation
bit_comp_
template<typename This , typename T > bit_compare uxn::patl::impl::assoc_generic< This, T, 0 >::bit_comp_ protected
Definition at line 450 of file assoc_generic.hpp.
N_
template<typename This , typename T > const word_t uxn::patl::impl::assoc_generic< This, T, 0 >::N_ = 0 static
Definition at line 123 of file assoc_generic.hpp.
root_
template<typename This , typename T > node_type* uxn::patl::impl::assoc_generic< This, T, 0 >::root_ protected
Definition at line 449 of file assoc_generic.hpp.
The documentation for this class was generated from the following file:
uxn/patl/impl/assoc_generic.hpp