PATL: uxn/demos/word_suffix/word_suffix.cpp File Reference
word_suffix.cpp File Reference
#include <vector>
#include <functional>
#include <uxn/patl/aux_/buffered_io.hpp>
#include <uxn/patl/aux_/char.hpp>
#include <uxn/patl/trie_set.hpp>
#include <uxn/patl/maxrep_iterator.hpp>
#include <uxn/patl/super_maxrep_iterator.hpp>
#include <uxn/patl/suffix_set.hpp>
Classes
struct ptr_less< T >
class PtrGreaterPred< T >
Typedefs
typedef std::string WordType
typedef std::vector< WordType > Words
typedef patl::trie_set< WordType *, 0, patl::ptr_bit_comparator< WordType > > WordSet
typedef std::vector< WordType * > Text
typedef patl::suffix_set< WordType ** > SuffixType
typedef std::set< WordType *, ptr_less< WordType > > WordStdSet
Functions
template<typename T >
void parse_text (patl::aux::buffered_input &inp, T insertIt)
template<typename T >
void parse_fiction (patl::aux::buffered_input &inp, T insertIt)
void insertIt (const WordType &word)
void insertItNoise (const WordType &word)
void loadNoiseWords (const char *fname)
int main (int argc, char *argv[])
Typedef Documentation
SuffixType
typedef patl::suffix_set<WordType**> SuffixType
Definition at line 33 of file word_suffix.cpp.
Text
typedef std::vector<WordType*> Text
Definition at line 32 of file word_suffix.cpp.
Words
typedef std::vector<WordType> Words
Definition at line 30 of file word_suffix.cpp.
WordSet
typedef patl::trie_set<WordType*, 0, patl::ptr_bit_comparator<WordType> > WordSet
Definition at line 31 of file word_suffix.cpp.
WordStdSet
typedef std::set<WordType*, ptr_less<WordType> > WordStdSet
Definition at line 34 of file word_suffix.cpp.
WordType
typedef std::string WordType
Definition at line 29 of file word_suffix.cpp.
Function Documentation
insertIt()
void insertIt (const WordType & word) inline
Definition at line 151 of file word_suffix.cpp.
{
    unsigned i = words.size();
    words.push_back(word);
    WordSet::const_iterator cit = noiseWordset.find(&words[i]);
    if (cit != noiseWordset.end())
    {
        words.pop_back();
        return;
    }
    //wordStdSet.insert(&words[i]); // для проверки правильности
    std::pair<WordSet::iterator, bool> itIns = wordset.insert(&words[i]);
    if (!itIns.second)
        words.pop_back();
    /*else
    {
        log2.write_string(word.c_str());
        log2.write_byte('\n');
    }*/
    text.push_back(*itIns.first);
    /*log1.write_string(word.c_str());
    log1.write_byte(' ');*/
}
Referenced by parse_fiction().
insertItNoise()
void insertItNoise (const WordType & word) inline
Definition at line 175 of file word_suffix.cpp.
{
    unsigned i = words.size();
    words.push_back(word);
    std::pair<WordSet::iterator, bool> itIns = noiseWordset.insert(&words[i]);
    if (!itIns.second)
        words.pop_back();
}
Referenced by loadNoiseWords().
loadNoiseWords()
void loadNoiseWords (const char * fname)
Definition at line 184 of file word_suffix.cpp.
{
    patl::aux::buffered_input bufIn(fname);
    parse_text(bufIn, insertItNoise);
}
References insertItNoise(), and parse_text().
main()
int main (int argc, char * argv[])
Definition at line 201 of file word_suffix.cpp.
{
    if (argc < 2)
        return 0;
    //
    words.reserve(1 << 20);
    //loadNoiseWords("noiseRUS.txt");
    patl::aux::buffered_input inp(argv[1]);
    parse_text(inp, insertIt);
    insertIt("***EOF***");
    //
    printf("Words count: %d (trie: %d, std: %d)\n",
        words.size(),
        wordset.size(),
        wordStdSet.size());
    printf("Words in text: %d\n", text.size());
    //
    SuffixType suffix(&text[0], text.size());
    for (unsigned i = 0; i != text.size(); ++i)
        suffix.push_back();
    //
    /*printf("Checking integrity... ");
    const unsigned failedId = suffix.integrity();
    if (failedId == ~word(0))
    printf("successfully!\n");
    else
    {
    printf("failed on %d\n", failedId);
    const SuffixType::node_type *id0 = suffix.node_by(0);
    printf(suffix.node_by(failedId)->get_parent()->visualize(id0));
    printf(suffix.node_by(failedId)->visualize(id0));
    printf(suffix.node_by(failedId)->get_xlink(0)->visualize(id0));
    printf(suffix.node_by(failedId)->get_xlink(1)->visualize(id0));
    }*/
    //
    typedef std::vector<unsigned> CntVector;
    CntVector counts(suffix.size());
    patl::super_maxrep_iterator<SuffixType> mrit(&suffix);
    for (; !mrit->is_root(); ++mrit)
        counts[mrit->key() - suffix.keys()] = mrit.freq();
    for (unsigned i = 0; i != counts.size(); ++i)
    {
        const unsigned cnt = counts[i];
        if (cnt)
        {
            SuffixType::prefix pref = suffix.prefix_by(i);
            const unsigned num = pref.skip() / SuffixType::bit_size;
            //counts[i] *= num;
            counts[i] = (cnt + cnt * num) / 2 * num;
        }
    }
    typedef std::vector<unsigned*> PtrVector;
    PtrVector cptrs;
    for (CntVector::iterator cit = counts.begin(); cit != counts.end(); ++cit)
    {
        if (*cit)
            cptrs.push_back(&*cit);
    }
    std::sort(cptrs.begin(), cptrs.end(), PtrGreaterPred<unsigned>());
    //
    patl::aux::buffered_output log3("maxreps.txt");
    for (PtrVector::const_iterator cit = cptrs.begin(); cit != cptrs.end(); ++cit)
    {
        const unsigned id = *cit - &counts[0];
        SuffixType::prefix pref = suffix.prefix_by(id);
        const unsigned
            num = pref.skip() / SuffixType::bit_size,
            //cnt = **cit / num;
            cnt = 2 * **cit / (num + num * num);
        if (cnt < 3 || num < 2)
            continue;
        char buf[32];
        sprintf(buf, "% 8d ", cnt);
        log3.write_string(buf);
        for (unsigned i = 0; i != num; ++i)
        {
            log3.write_string(text[id + i]->c_str());
            log3.write_byte(' ');
        }
        log3.write_byte('\n');
    }
}
parse_fiction()
template<typename T > void parse_fiction (patl::aux::buffered_input & inp, T insertIt)
Definition at line 77 of file word_suffix.cpp.
{
    bool
        inword = false,
        inpunct = false,
        isdots = false;
    WordType curword;
    while (inp.is_data())
    {
        const unsigned char c = patl::aux::to_lower(inp.read_byte());
        if (patl::aux::is_hyphen(c))
        {
            if (inword || inpunct)
                curword.push_back(c);
            else
            {
                curword.clear();
                curword.push_back(c);
                inpunct = true;
            }
        }
        else if (patl::aux::is_letter(c))
        {
            if (inword)
                curword.push_back(c);
            else
            {
                if (inpunct)
                {
                    if (isdots)
                        insertIt(".");
                    isdots = inpunct = false;
                }
                curword.clear();
                curword.push_back(c);
                inword = true;
            }
        }
        else if (patl::aux::is_punctuation(c))
        {
            if (inpunct)
                curword.push_back(c);
            else
            {
                if (inword)
                {
                    insertIt(curword);
                    inword = false;
                }
                curword.clear();
                curword.push_back(c);
                inpunct = true;
            }
            isdots = isdots || patl::aux::is_dot_symbol(c);
        }
        else // is_blank_char or else
        {
            if (inword)
            {
                insertIt(curword);
                inword = false;
            }
            else if (inpunct)
            {
                if (isdots)
                    insertIt(".");
                isdots = inpunct = false;
            }
        }
    }
    if (inword || inpunct)
        insertIt(curword);
}
References insertIt(), uxn::patl::aux::is_dot_symbol(), uxn::patl::aux::is_hyphen(), uxn::patl::aux::is_letter(), uxn::patl::aux::is_punctuation(), and uxn::patl::aux::to_lower().
parse_text()
template<typename T > void parse_text (patl::aux::buffered_input & inp, T insertIt)
Definition at line 47 of file word_suffix.cpp.
{
    bool intoken = false;
    WordType token;
    while (inp.is_data())
    {
        const unsigned char c = inp.read_byte();
        if (patl::aux::is_proper_char(c))
        {
            if (!intoken)
            {
                if (text.size() >= (16 << 20))
                    return;
                token.clear();
                intoken = true;
            }
            token.push_back(c);
        }
        // space between tokens
        else if (intoken)
        {
            insertIt(token);
            intoken = false;
        }
    }
    if (intoken)
        insertIt(token);
}
References uxn::patl::aux::is_proper_char().
Referenced by loadNoiseWords().