PATL: uxn::patl::aux::buffered_output Class Reference
uxn::patl::aux::buffered_output Class Reference
#include <buffered_io.hpp>
Public Member Functions
buffered_output (const char *fname)
buffered_output (HANDLE fh)
~buffered_output ()
void write_byte (unsigned char byte)
void write_word (word_t dw)
void write_string (const char *str)
void write_bytes (const unsigned char *ptr, word_t len)
void move_offset (sword_t offs)
void flush_buffer ()
Public Member Functions inherited from uxn::patl::aux::buffered_base
long long get_file_length ()
Private Member Functions
void flush_buffer (const unsigned char *ptr, word_t len)
Additional Inherited Members
Protected Types inherited from uxn::patl::aux::buffered_base
enum { BufferSize = 1<<12 }
Protected Member Functions inherited from uxn::patl::aux::buffered_base
buffered_base (const char *fname, bool isWrite)
buffered_base (HANDLE fh)
~buffered_base ()
void set_file_ptr (word_t offs)
word_t get_file_ptr ()
Protected Attributes inherited from uxn::patl::aux::buffered_base
const HANDLE fh_
unsigned char *const buf_
unsigned char * end_
Detailed Description
Definition at line 202 of file buffered_io.hpp.
Constructor & Destructor Documentation
buffered_output() [1/2]
uxn::patl::aux::buffered_output::buffered_output (const char * fname) inline explicit
Definition at line 206 of file buffered_io.hpp.
        : buffered_base(fname, true)
    {
    }
buffered_output() [2/2]
uxn::patl::aux::buffered_output::buffered_output (HANDLE fh) inline explicit
Definition at line 211 of file buffered_io.hpp.
        : buffered_base(fh)
    {
    }
~buffered_output()
uxn::patl::aux::buffered_output::~buffered_output () inline
Definition at line 216 of file buffered_io.hpp.
    {
        flush_buffer();
    }
References flush_buffer().
Member Function Documentation
flush_buffer() [1/2]
void uxn::patl::aux::buffered_output::flush_buffer () inline
Definition at line 270 of file buffered_io.hpp.
    {
        flush_buffer(buf_, end_ - buf_);
        end_ = buf_;
    }
References uxn::patl::aux::buffered_base::buf_, uxn::patl::aux::buffered_base::end_, and flush_buffer().
Referenced by flush_buffer(), move_offset(), write_byte(), write_bytes(), and ~buffered_output().
flush_buffer() [2/2]
void uxn::patl::aux::buffered_output::flush_buffer (const unsigned char * ptr, word_t len) inline private
Definition at line 277 of file buffered_io.hpp.
    {
        DWORD realSize;
        const BOOL ret = ::WriteFile(fh_, ptr, len, &realSize, 0);
        if (!ret || realSize != len)
            throw std::exception();
    }
References uxn::patl::aux::buffered_base::fh_.
move_offset()
void uxn::patl::aux::buffered_output::move_offset (sword_t offs) inline
Definition at line 264 of file buffered_io.hpp.
    {
        flush_buffer();
        set_file_ptr(get_file_ptr() + offs);
    }
References flush_buffer(), uxn::patl::aux::buffered_base::get_file_ptr(), and uxn::patl::aux::buffered_base::set_file_ptr().
write_byte()
void uxn::patl::aux::buffered_output::write_byte (unsigned char byte) inline
Definition at line 221 of file buffered_io.hpp.
    {
        *end_++ = byte;
        if (end_ == buf_ + BufferSize)
            flush_buffer();
    }
References uxn::patl::aux::buffered_base::buf_, uxn::patl::aux::buffered_base::BufferSize, uxn::patl::aux::buffered_base::end_, and flush_buffer().
Referenced by write_string(), and write_word().
write_bytes()
void uxn::patl::aux::buffered_output::write_bytes (const unsigned char * ptr, word_t len) inline
Definition at line 250 of file buffered_io.hpp.
    {
        const word_t
            avail = static_cast<word_t>(buf_ + BufferSize - end_),
            chunk = avail < len ? avail : len;
        std::copy(ptr, ptr + chunk, end_);
        end_ += chunk;
        len -= chunk;
        if (end_ == buf_ + BufferSize)
            flush_buffer();
        if (len)
            flush_buffer(ptr + chunk, len);
    }
References uxn::patl::aux::buffered_base::buf_, uxn::patl::aux::buffered_base::BufferSize, uxn::patl::aux::buffered_base::end_, and flush_buffer().
write_string()
void uxn::patl::aux::buffered_output::write_string (const char * str) inline
Definition at line 244 of file buffered_io.hpp.
    {
        for (; *str != 0; ++str)
            write_byte(*str);
    }
References write_byte().
write_word()
void uxn::patl::aux::buffered_output::write_word (word_t dw) inline
Definition at line 228 of file buffered_io.hpp.
    {
        const unsigned char *b =
            reinterpret_cast<unsigned char*>(&dw);
        write_byte(b[0]);
        write_byte(b[1]);
        write_byte(b[2]);
        write_byte(b[3]);
#ifdef PATL_64
        write_byte(b[4]);
        write_byte(b[5]);
        write_byte(b[6]);
        write_byte(b[7]);
#endif
    }
References write_byte().
The documentation for this class was generated from the following file:
uxn/patl/aux_/buffered_io.hpp