PATL: uxn::patl::aux::performance_timer Class Reference
uxn::patl::aux::performance_timer Class Reference
#include <perf_timer.hpp>
Public Member Functions
performance_timer ()
void start ()
void finish ()
double get_seconds () const
Static Private Member Functions
static void query_frequency ()
Private Attributes
__int64 start_
__int64 finish_
Static Private Attributes
static __int64 frequency_ = 0
Detailed Description
Definition at line 23 of file perf_timer.hpp.
Constructor & Destructor Documentation
performance_timer()
uxn::patl::aux::performance_timer::performance_timer () inline
Definition at line 26 of file perf_timer.hpp.
        : start_(0)
        , finish_(0)
    {
        query_frequency();
        start();
    }
References query_frequency(), and start().
Member Function Documentation
finish()
void uxn::patl::aux::performance_timer::finish () inline
Definition at line 43 of file perf_timer.hpp.
    {
#if _WIN32
        LARGE_INTEGER large;
        QueryPerformanceCounter(&large);
        finish_ = large.QuadPart;
#endif
    }
References finish_.
Referenced by main().
get_seconds()
double uxn::patl::aux::performance_timer::get_seconds () const inline
Definition at line 52 of file perf_timer.hpp.
    {
        return
            static_cast<double>(finish_ - start_) /
            static_cast<double>(frequency_);
    }
References finish_, frequency_, and start_.
query_frequency()
static void uxn::patl::aux::performance_timer::query_frequency () inline static private
Definition at line 60 of file perf_timer.hpp.
    {
#if _WIN32
        if (frequency_ == 0)
        {
            LARGE_INTEGER large;
            QueryPerformanceFrequency(&large);
            frequency_ = large.QuadPart;
        }
#endif
    }
References frequency_.
Referenced by performance_timer().
start()
void uxn::patl::aux::performance_timer::start () inline
Definition at line 34 of file perf_timer.hpp.
    {
#if _WIN32
        LARGE_INTEGER large;
        QueryPerformanceCounter(&large);
        start_ = large.QuadPart;
#endif
    }
References start_.
Referenced by performance_timer().
Member Data Documentation
finish_
__int64 uxn::patl::aux::performance_timer::finish_ private
Definition at line 74 of file perf_timer.hpp.
Referenced by finish(), and get_seconds().
frequency_
__int64 uxn::patl::aux::performance_timer::frequency_ = 0 static private
Definition at line 72 of file perf_timer.hpp.
Referenced by get_seconds(), and query_frequency().
start_
__int64 uxn::patl::aux::performance_timer::start_ private
Definition at line 73 of file perf_timer.hpp.
Referenced by get_seconds(), and start().
The documentation for this class was generated from the following file:
uxn/patl/aux_/perf_timer.hpp