PATL: uxn::patl::impl::primes< Natural > Class Template Reference
uxn::patl::impl::primes< Natural > Class Template Reference
#include <primes.hpp>
Public Types
enum { B = 12 << 10 }
typedef Natural nat_type
Public Types inherited from uxn::patl::impl::generator_base< primes< Natural >, Natural >
typedef primes< Natural > this_t
typedef Natural elem_t
Public Member Functions
primes (const nat_type &n=2, const nat_type &m=~nat_type(0))
if (n_<=3) PATL_YIELD(3)
if (n_<=5) PATL_YIELD(5)
if (n_<=7) PATL_YIELD(7)
for (n_=get_max< nat_type >(9, n_ &1 ? n_ :n_ - 1);n_< m_;)
Public Member Functions inherited from uxn::patl::impl::generator_base< primes< Natural >, Natural >
generator_base ()
this_t replica () const
void init ()
bool next ()
const elem_t & value ()
Public Attributes
PATL_EMIT
Static Private Member Functions
static word_t corr0 (word_t n, word_t i)
static word_t correct (word_t n, word_t i)
Private Attributes
nat_type n_
nat_type m_
word_t arr_ [B+1]
word_t bound_
word_t i_
Static Private Attributes
static const word_t offs_ [bits_in_word]
static const word_t bm357_ [105]
Additional Inherited Members
Protected Attributes inherited from uxn::patl::impl::generator_base< primes< Natural >, Natural >
int generator_line
elem_t generator_value
Detailed Description
template<typename Natural>
class uxn::patl::impl::primes< Natural >
Definition at line 26 of file primes.hpp.
Member Typedef Documentation
nat_type
template<typename Natural > typedef Natural uxn::patl::impl::primes< Natural >::nat_type
Definition at line 30 of file primes.hpp.
Member Enumeration Documentation
anonymous enum
template<typename Natural > anonymous enum
Enumerator
B
Definition at line 32 of file primes.hpp.
{ B = 12 << 10 };
Constructor & Destructor Documentation
primes()
template<typename Natural > uxn::patl::impl::primes< Natural >::primes (const nat_type & n = 2, const nat_type & m = ~nat_type(0)) inline
Definition at line 34 of file primes.hpp.
        : n_(n)
        , m_(get_max<nat_type>(9, m & 1 ? m : m + 1))
    { }
Referenced by uxn::patl::impl::primes< Natural >::for().
Member Function Documentation
corr0()
template<typename Natural > static word_t uxn::patl::impl::primes< Natural >::corr0 (word_t n, word_t i) inline static private
Definition at line 105 of file primes.hpp.
    { return n ? i - n : n; }
Referenced by uxn::patl::impl::primes< Natural >::for().
correct()
template<typename Natural > static word_t uxn::patl::impl::primes< Natural >::correct (word_t n, word_t i) inline static private
Definition at line 108 of file primes.hpp.
    { return n & 1 ? n + i : n; }
Referenced by uxn::patl::impl::primes< Natural >::for().
for()
template<typename Natural > uxn::patl::impl::primes< Natural >::for () inline
Definition at line 45 of file primes.hpp.
                                                   : n_ - 1); n_ < m_; )
        {
            bound_ = get_min(static_cast<word_t>((m_ - n_) / 2), B * bits_in_word);
            if (n_ < B)
                bound_ = get_min(static_cast<word_t>((n_ * n_ - n_) / 2), bound_);
            //
            {
                {
                    const word_t j = static_cast<word_t>((n_ - 3) / 2 % 105);
                    for (word_t i = 0, bmi = offs_[j % bits_in_word] + j / bits_in_word
                        ; i != bound_ / bits_in_word + 1
                        ; ++i, bmi = (bmi + 1) % 105)
                        arr_[i] = bm357_[bmi];
                    arr_[bound_ / bits_in_word] &=
                        ~word_t(0) >> (bits_in_word - bound_ % bits_in_word);
                }
                const nat_type sq_m(sqrt_int(n_ + bound_ * 2) + 1);
                if (sq_m >= 11)
                {
                    std::auto_ptr<primes> ps(new primes(9, sq_m));
                    if (ps->next())
                    {
                        do
{
                            const word_t i = static_cast<word_t>(ps->value());
                            for (word_t j = correct(corr0(static_cast<word_t>(n_ % i), i), i) / 2
                                ; j < bound_
                                ; j += i)
                                arr_[j / bits_in_word] |= 1 << (j % bits_in_word);
                        } while (ps->next());
                    }
                }
            }
            //
            for (i_ = 0; ; ++i_, n_ += 2)
            {
                {
                    word_t
                        sh = i_ % bits_in_word,
                        a = ~arr_[i_ / bits_in_word] >> sh;
                    while (!a)
                    {
                        i_ += bits_in_word - sh;
                        n_ += 2 * (bits_in_word - sh);
                        sh = 0;
                        a = ~arr_[i_ / bits_in_word];
                    }
                    const word_t id = get_lowest_bit_id(a);
                    i_ += id;
                    n_ += 2 * id;
                }
                if (i_ >= bound_)
                    break;
                PATL_YIELD(n_);
            }
        }
References uxn::patl::impl::primes< Natural >::arr_, uxn::patl::impl::primes< Natural >::B, bits_in_word, uxn::patl::impl::primes< Natural >::bm357_, uxn::patl::impl::primes< Natural >::bound_, uxn::patl::impl::primes< Natural >::corr0(), uxn::patl::impl::primes< Natural >::correct(), uxn::patl::impl::get_lowest_bit_id(), uxn::patl::impl::get_min(), uxn::patl::impl::primes< Natural >::i_, uxn::patl::impl::primes< Natural >::m_, uxn::patl::impl::primes< Natural >::n_, uxn::patl::impl::primes< Natural >::offs_, PATL_YIELD, uxn::patl::impl::primes< Natural >::primes(), and uxn::patl::impl::sqrt_int().
if() [1/3]
template<typename Natural > uxn::patl::impl::primes< Natural >::if (n_<= 3)
if() [2/3]
template<typename Natural > uxn::patl::impl::primes< Natural >::if (n_<= 5)
if() [3/3]
template<typename Natural > uxn::patl::impl::primes< Natural >::if (n_<= 7)
Member Data Documentation
arr_
template<typename Natural > word_t uxn::patl::impl::primes< Natural >::arr_[B+1] private
Definition at line 112 of file primes.hpp.
Referenced by uxn::patl::impl::primes< Natural >::for().
bm357_
template<typename Natural > const word_t uxn::patl::impl::primes< Natural >::bm357_[105] static private
Definition at line 116 of file primes.hpp.
Referenced by uxn::patl::impl::primes< Natural >::for().
bound_
template<typename Natural > word_t uxn::patl::impl::primes< Natural >::bound_ private
Definition at line 113 of file primes.hpp.
Referenced by uxn::patl::impl::primes< Natural >::for().
i_
template<typename Natural > word_t uxn::patl::impl::primes< Natural >::i_ private
Definition at line 113 of file primes.hpp.
Referenced by uxn::patl::impl::primes< Natural >::for().
m_
template<typename Natural > nat_type uxn::patl::impl::primes< Natural >::m_ private
Definition at line 111 of file primes.hpp.
Referenced by uxn::patl::impl::primes< Natural >::for().
n_
template<typename Natural > nat_type uxn::patl::impl::primes< Natural >::n_ private
Definition at line 111 of file primes.hpp.
Referenced by uxn::patl::impl::primes< Natural >::for().
offs_
template<typename Natural > const word_t uxn::patl::impl::primes< Natural >::offs_[bits_in_word] static private
Definition at line 115 of file primes.hpp.
Referenced by uxn::patl::impl::primes< Natural >::for().
PATL_EMIT
template<typename Natural > uxn::patl::impl::primes< Natural >::PATL_EMIT
Initial value:
{
        if (n_ <= 2) PATL_YIELD(2)
Definition at line 39 of file primes.hpp.
The documentation for this class was generated from the following file:
uxn/patl/impl/primes.hpp