PATL: uxn::patl::impl::trie_generic< T, N > Class Template Reference
uxn::patl::impl::trie_generic< T, N > Class Template Reference
#include <trie_generic.hpp>
Public Types
typedef super::key_type key_type
typedef super::value_type value_type
typedef super::bit_compare bit_compare
typedef super::allocator_type allocator_type
typedef super::size_type size_type
typedef super::const_iterator const_iterator
typedef super::iterator iterator
typedef super::vertex vertex
typedef super::preorder_iterator preorder_iterator
typedef super::postorder_iterator postorder_iterator
typedef algorithm::const_key_reference const_key_reference
Public Member Functions
trie_generic (const bit_compare &bit_comp, const allocator_type &alloc)
trie_generic (const this_t &b)
trie_generic (const value_type *first, const value_type *last, const bit_compare &bit_comp, const allocator_type &alloc)
iter_bool_pair insert (const value_type &val)
iterator insert (iterator, const value_type &val)
just for backward compatibility with std assoc containers
template<typename Iter >
void insert (Iter first, Iter last)
template of insert range
Static Public Attributes
static const word_t N_ = N
Protected Types
typedef traits::node_type node_type
typedef traits::algorithm algorithm
Private Types
typedef trie_generic< T, N > this_t
typedef trie_generic_traits< T, node_gen, algorithm_gen, core_prefix_generic, this_t > traits
typedef assoc_generic< trie_generic< T, N >, traits, N > super
typedef std::pair< iterator, bool > iter_bool_pair
Detailed Description
template<typename T, word_t N = 0>
class uxn::patl::impl::trie_generic< T, N >
Definition at line 146 of file trie_generic.hpp.
Member Typedef Documentation
algorithm
template<typename T , word_t N = 0> typedef traits::algorithm uxn::patl::impl::trie_generic< T, N >::algorithm protected
Definition at line 155 of file trie_generic.hpp.
allocator_type
template<typename T , word_t N = 0> typedef super::allocator_type uxn::patl::impl::trie_generic< T, N >::allocator_type
Definition at line 161 of file trie_generic.hpp.
bit_compare
template<typename T , word_t N = 0> typedef super::bit_compare uxn::patl::impl::trie_generic< T, N >::bit_compare
Definition at line 160 of file trie_generic.hpp.
const_iterator
template<typename T , word_t N = 0> typedef super::const_iterator uxn::patl::impl::trie_generic< T, N >::const_iterator
Definition at line 163 of file trie_generic.hpp.
const_key_reference
template<typename T , word_t N = 0> typedef algorithm::const_key_reference uxn::patl::impl::trie_generic< T, N >::const_key_reference
Definition at line 169 of file trie_generic.hpp.
iter_bool_pair
template<typename T , word_t N = 0> typedef std::pair<iterator, bool> uxn::patl::impl::trie_generic< T, N >::iter_bool_pair private
Definition at line 193 of file trie_generic.hpp.
iterator
template<typename T , word_t N = 0> typedef super::iterator uxn::patl::impl::trie_generic< T, N >::iterator
Definition at line 164 of file trie_generic.hpp.
key_type
template<typename T , word_t N = 0> typedef super::key_type uxn::patl::impl::trie_generic< T, N >::key_type
Definition at line 158 of file trie_generic.hpp.
node_type
template<typename T , word_t N = 0> typedef traits::node_type uxn::patl::impl::trie_generic< T, N >::node_type protected
Definition at line 154 of file trie_generic.hpp.
postorder_iterator
template<typename T , word_t N = 0> typedef super::postorder_iterator uxn::patl::impl::trie_generic< T, N >::postorder_iterator
Definition at line 167 of file trie_generic.hpp.
preorder_iterator
template<typename T , word_t N = 0> typedef super::preorder_iterator uxn::patl::impl::trie_generic< T, N >::preorder_iterator
Definition at line 166 of file trie_generic.hpp.
size_type
template<typename T , word_t N = 0> typedef super::size_type uxn::patl::impl::trie_generic< T, N >::size_type
Definition at line 162 of file trie_generic.hpp.
super
template<typename T , word_t N = 0> typedef assoc_generic<trie_generic<T, N>, traits, N> uxn::patl::impl::trie_generic< T, N >::super private
Definition at line 151 of file trie_generic.hpp.
this_t
template<typename T , word_t N = 0> typedef trie_generic<T, N> uxn::patl::impl::trie_generic< T, N >::this_t private
Definition at line 149 of file trie_generic.hpp.
traits
template<typename T , word_t N = 0> typedef trie_generic_traits<T, node_gen, algorithm_gen, core_prefix_generic, this_t> uxn::patl::impl::trie_generic< T, N >::traits private
Definition at line 150 of file trie_generic.hpp.
value_type
template<typename T , word_t N = 0> typedef super::value_type uxn::patl::impl::trie_generic< T, N >::value_type
Definition at line 159 of file trie_generic.hpp.
vertex
template<typename T , word_t N = 0> typedef super::vertex uxn::patl::impl::trie_generic< T, N >::vertex
Definition at line 165 of file trie_generic.hpp.
Constructor & Destructor Documentation
trie_generic() [1/3]
template<typename T , word_t N = 0> uxn::patl::impl::trie_generic< T, N >::trie_generic (const bit_compare & bit_comp, const allocator_type & alloc) inline
Definition at line 173 of file trie_generic.hpp.
        : super(bit_comp, alloc)
    {
    }
trie_generic() [2/3]
template<typename T , word_t N = 0> uxn::patl::impl::trie_generic< T, N >::trie_generic (const this_t & b) inline
Definition at line 178 of file trie_generic.hpp.
        : super(b)
    {
    }
trie_generic() [3/3]
template<typename T , word_t N = 0> uxn::patl::impl::trie_generic< T, N >::trie_generic (const value_type * first, const value_type * last, const bit_compare & bit_comp, const allocator_type & alloc) inline
Definition at line 183 of file trie_generic.hpp.
        : super(first, last, bit_comp, alloc)
    {
    }
Member Function Documentation
insert() [1/3]
template<typename T , word_t N = 0> iter_bool_pair uxn::patl::impl::trie_generic< T, N >::insert (const value_type & val) inline
Definition at line 196 of file trie_generic.hpp.
    {
        if (this->root_)
        {
            algorithm pal(CSELF, this->root_, 0);
            // find a number of first mismatching bit
            const word_t l = pal.mismatch(T::ref_key(val));
            // if this number end at infinity
            if (~word_t(0) == l)
                // then this key already in trie
                return iter_bool_pair(iterator(vertex(pal)), false);
            //      N
            algorithm pal2(pal);
            word_t diff = 0;
            while (pal2.get_p()->get_skip() == pal2.get_q()->get_skip())
            {
                pal2.ascend();
                ++diff;
            }
            word_t *sh = get_shortcut(pal2.compact());
            if (sh)
            {
                //
            }
            else if (diff >= N / 2)
            {
                //
                create_shortcut(pal2.compact());
                //    levelorder_iterator'
                vertex vtx(pal2);
                const word_t next = max0(vtx.skip()) + N;
                /*levelorder_iterator
                    lit(vtx.levelorder_begin(next)),
                    lit_end(vtx.levelorder_end(next));*/
                //for (; lit != lit_end; ++lit)
            }
            // add new node for value with unique key
            return iter_bool_pair(iterator(vertex(add(val, pal, l))), true);
        }
        // if trie is empty then add root
        return iter_bool_pair(iterator(vertex(add_root(val))), true);
    }
References CSELF, uxn::patl::impl::max0(), N, and uxn::patl::impl::const_vertex_generic< Algorithm >::skip().
Referenced by uxn::patl::impl::trie_generic< T, 0 >::insert(), uxn::patl::impl::trie_generic< T, N >::insert(), main(), uxn::patl::impl::trie_generic< T, 0 >::merge(), uxn::patl::impl::trie_generic< T, 0 >::operator=(), search_work(), uxn::patl::impl::trie_generic< T, 0 >::trie_generic(), and strings_from_merged_files_generator::while().
insert() [2/3]
template<typename T , word_t N = 0> template<typename Iter > void uxn::patl::impl::trie_generic< T, N >::insert (Iter first, Iter last) inline
template of insert range
Definition at line 247 of file trie_generic.hpp.
    {
        for (; first != last; ++first)
            insert(*first);
    }
References uxn::patl::impl::trie_generic< T, N >::insert().
insert() [3/3]
template<typename T , word_t N = 0> iterator uxn::patl::impl::trie_generic< T, N >::insert (iterator , const value_type & val) inline
just for backward compatibility with std assoc containers
Definition at line 240 of file trie_generic.hpp.
    {
        return insert(val).first;
    }
References uxn::patl::impl::trie_generic< T, N >::insert().
Member Data Documentation
N_
template<typename T , word_t N = 0> const word_t uxn::patl::impl::trie_generic< T, N >::N_ = N static
Definition at line 171 of file trie_generic.hpp.
The documentation for this class was generated from the following file:
uxn/patl/impl/trie_generic.hpp