PATL: uxn::patl::impl::lca_base< Oracle > Class Template Reference
uxn::patl::impl::lca_base< Oracle > Class Template Reference
#include <lca_base.hpp>
Public Member Functions
word_t number () const
word_t height () const
bool is_inode () const
const this_t * get_i () const
this_t * get_i ()
const this_t * get_l_i () const
this_t * get_l_i ()
word_t get_a () const
void numerate (word_t num)
void set_inode ()
void setup_i (Oracle *oracl)
void set_root_a ()
void setup_a (const Oracle *oracl)
Private Types
typedef lca_base< Oracle > this_t
typedef Oracle::vertex vertex
Private Member Functions
void set_i (const this_t *pI)
void set_l (const this_t *pL)
Private Attributes
word_t num_
word_t il_
word_t a_
Detailed Description
template<typename Oracle>
class uxn::patl::impl::lca_base< Oracle >
Definition at line 19 of file lca_base.hpp.
Member Typedef Documentation
this_t
template<typename Oracle > typedef lca_base<Oracle> uxn::patl::impl::lca_base< Oracle >::this_t private
Definition at line 21 of file lca_base.hpp.
vertex
template<typename Oracle > typedef Oracle::vertex uxn::patl::impl::lca_base< Oracle >::vertex private
Definition at line 22 of file lca_base.hpp.
Member Function Documentation
get_a()
template<typename Oracle > word_t uxn::patl::impl::lca_base< Oracle >::get_a () const inline
Definition at line 66 of file lca_base.hpp.
    {
        return a_;
    }
References uxn::patl::impl::lca_base< Oracle >::a_.
Referenced by uxn::patl::lca_oracle< SuffixCont >::operator()().
get_i() [1/2]
template<typename Oracle > this_t * uxn::patl::impl::lca_base< Oracle >::get_i () inline
Definition at line 45 of file lca_base.hpp.
    {
        return is_inode() ? this : reinterpret_cast<this_t*>(il_);
    }
References uxn::patl::impl::lca_base< Oracle >::il_, and uxn::patl::impl::lca_base< Oracle >::is_inode().
get_i() [2/2]
template<typename Oracle > const this_t * uxn::patl::impl::lca_base< Oracle >::get_i () const inline
Definition at line 40 of file lca_base.hpp.
    {
        return is_inode() ? this : reinterpret_cast<const this_t*>(il_);
    }
References uxn::patl::impl::lca_base< Oracle >::il_, and uxn::patl::impl::lca_base< Oracle >::is_inode().
Referenced by uxn::patl::lca_oracle< SuffixCont >::operator()(), uxn::patl::impl::lca_base< Oracle >::set_root_a(), uxn::patl::impl::lca_base< Oracle >::setup_a(), and uxn::patl::impl::lca_base< Oracle >::setup_i().
get_l_i() [1/2]
template<typename Oracle > this_t * uxn::patl::impl::lca_base< Oracle >::get_l_i () inline
Definition at line 58 of file lca_base.hpp.
    {
        return is_inode()
            ? reinterpret_cast<this_t*>(il_ & ~word_t(1))
            : reinterpret_cast<this_t*>(
                reinterpret_cast<this_t*>(il_)->il_ & ~word_t(1));
    }
References uxn::patl::impl::lca_base< Oracle >::il_, and uxn::patl::impl::lca_base< Oracle >::is_inode().
get_l_i() [2/2]
template<typename Oracle > const this_t * uxn::patl::impl::lca_base< Oracle >::get_l_i () const inline
Definition at line 50 of file lca_base.hpp.
    {
        return is_inode()
            ? reinterpret_cast<const this_t*>(il_ & ~word_t(1))
            : reinterpret_cast<const this_t*>(
                reinterpret_cast<const this_t*>(il_)->il_ & ~word_t(1));
    }
References uxn::patl::impl::lca_base< Oracle >::il_, and uxn::patl::impl::lca_base< Oracle >::is_inode().
Referenced by uxn::patl::lca_oracle< SuffixCont >::operator()().
height()
template<typename Oracle > word_t uxn::patl::impl::lca_base< Oracle >::height () const inline
Definition at line 30 of file lca_base.hpp.
    {
        return get_lowest_bit_id(num_);
    }
References uxn::patl::impl::get_lowest_bit_id(), and uxn::patl::impl::lca_base< Oracle >::num_.
Referenced by uxn::patl::impl::lca_base< Oracle >::set_root_a(), uxn::patl::impl::lca_base< Oracle >::setup_a(), and uxn::patl::impl::lca_base< Oracle >::setup_i().
is_inode()
template<typename Oracle > bool uxn::patl::impl::lca_base< Oracle >::is_inode () const inline
Definition at line 35 of file lca_base.hpp.
    {
        return il_ & word_t(1);
    }
References uxn::patl::impl::lca_base< Oracle >::il_.
Referenced by uxn::patl::impl::lca_base< Oracle >::get_i(), and uxn::patl::impl::lca_base< Oracle >::get_l_i().
number()
template<typename Oracle > word_t uxn::patl::impl::lca_base< Oracle >::number () const inline
Definition at line 25 of file lca_base.hpp.
    {
        return num_;
    }
References uxn::patl::impl::lca_base< Oracle >::num_.
Referenced by uxn::patl::lca_oracle< SuffixCont >::operator()().
numerate()
template<typename Oracle > void uxn::patl::impl::lca_base< Oracle >::numerate (word_t num) inline
Definition at line 71 of file lca_base.hpp.
    {
        num_ = num;
    }
References uxn::patl::impl::lca_base< Oracle >::num_.
Referenced by uxn::patl::lca_oracle< SuffixCont >::init().
set_i()
template<typename Oracle > void uxn::patl::impl::lca_base< Oracle >::set_i (const this_t * pI) inline private
Definition at line 120 of file lca_base.hpp.
    {
        il_ = reinterpret_cast<word_t>(pI);
    }
References uxn::patl::impl::lca_base< Oracle >::il_.
Referenced by uxn::patl::impl::lca_base< Oracle >::setup_i().
set_inode()
template<typename Oracle > void uxn::patl::impl::lca_base< Oracle >::set_inode () inline
Definition at line 76 of file lca_base.hpp.
    {
        il_ = reinterpret_cast<word_t>(this) | word_t(1);
    }
References uxn::patl::impl::lca_base< Oracle >::il_.
Referenced by uxn::patl::lca_oracle< SuffixCont >::init(), and uxn::patl::impl::lca_base< Oracle >::setup_i().
set_l()
template<typename Oracle > void uxn::patl::impl::lca_base< Oracle >::set_l (const this_t * pL) inline private
Definition at line 125 of file lca_base.hpp.
    {
        il_ = reinterpret_cast<word_t>(pL) | word_t(1);
    }
References uxn::patl::impl::lca_base< Oracle >::il_.
Referenced by uxn::patl::impl::lca_base< Oracle >::setup_i().
set_root_a()
template<typename Oracle > void uxn::patl::impl::lca_base< Oracle >::set_root_a () inline
Definition at line 106 of file lca_base.hpp.
    {
        a_ = word_t(1) << get_i()->height();
    }
References uxn::patl::impl::lca_base< Oracle >::a_, uxn::patl::impl::lca_base< Oracle >::get_i(), and uxn::patl::impl::lca_base< Oracle >::height().
Referenced by uxn::patl::lca_oracle< SuffixCont >::init().
setup_a()
template<typename Oracle > void uxn::patl::impl::lca_base< Oracle >::setup_a (const Oracle * oracl) inline
Definition at line 111 of file lca_base.hpp.
    {
        vertex vtx(oracl->new_algo(this));
        vtx.ascend();
        a_ = oracl->get_by(vtx)->a_ |
            (word_t(1) << get_i()->height());
    }
References uxn::patl::impl::lca_base< Oracle >::a_, uxn::patl::impl::lca_base< Oracle >::get_i(), and uxn::patl::impl::lca_base< Oracle >::height().
Referenced by uxn::patl::lca_oracle< SuffixCont >::init().
setup_i()
template<typename Oracle > void uxn::patl::impl::lca_base< Oracle >::setup_i (Oracle * oracl) inline
Definition at line 81 of file lca_base.hpp.
    {
        vertex vtx(oracl->new_algo(this));
        vtx.iterate(0);
        this_t
            *ltI = oracl->get_by(vtx)->get_i(),
            *rtI = (oracl->get_by(vtx) + 1)->get_i();
        const word_t
            idH = height(),
            ltH = ltI->height(),
            rtH = rtI->height();
        if (idH > ltH && idH > rtH)
            set_inode();
        else if (ltH < rtH)
        {
            set_i(rtI);
            rtI->set_l(this);
        }
        else
        {
            set_i(ltI);
            ltI->set_l(this);
        }
    }
References uxn::patl::impl::lca_base< Oracle >::get_i(), uxn::patl::impl::lca_base< Oracle >::height(), uxn::patl::impl::lca_base< Oracle >::set_i(), uxn::patl::impl::lca_base< Oracle >::set_inode(), and uxn::patl::impl::lca_base< Oracle >::set_l().
Referenced by uxn::patl::lca_oracle< SuffixCont >::init().
Member Data Documentation
a_
template<typename Oracle > word_t uxn::patl::impl::lca_base< Oracle >::a_ private
Definition at line 130 of file lca_base.hpp.
Referenced by uxn::patl::impl::lca_base< Oracle >::get_a(), uxn::patl::impl::lca_base< Oracle >::set_root_a(), and uxn::patl::impl::lca_base< Oracle >::setup_a().
il_
template<typename Oracle > word_t uxn::patl::impl::lca_base< Oracle >::il_ private
Definition at line 130 of file lca_base.hpp.
Referenced by uxn::patl::impl::lca_base< Oracle >::get_i(), uxn::patl::impl::lca_base< Oracle >::get_l_i(), uxn::patl::impl::lca_base< Oracle >::is_inode(), uxn::patl::impl::lca_base< Oracle >::set_i(), uxn::patl::impl::lca_base< Oracle >::set_inode(), and uxn::patl::impl::lca_base< Oracle >::set_l().
num_
template<typename Oracle > word_t uxn::patl::impl::lca_base< Oracle >::num_ private
Definition at line 130 of file lca_base.hpp.
Referenced by uxn::patl::impl::lca_base< Oracle >::height(), uxn::patl::impl::lca_base< Oracle >::number(), and uxn::patl::impl::lca_base< Oracle >::numerate().
The documentation for this class was generated from the following file:
uxn/patl/impl/lca_base.hpp