PATL: uxn::patl::impl::ring_buffer< Type, Allocator > Class Template Reference
uxn::patl::impl::ring_buffer< Type, Allocator > Class Template Reference
#include <ring_buffer.hpp>
Classes
struct reserve_functor
Public Types
typedef Type value_type
typedef Allocator::const_pointer const_pointer
typedef Allocator::const_reference const_reference
typedef Allocator::pointer pointer
typedef Allocator::reference reference
typedef Allocator allocator_type
typedef word_t size_type
Public Member Functions
ring_buffer (size_type initSize, const allocator_type &alloc=allocator_type())
~ring_buffer ()
void clear ()
bool empty () const
bool endpoint () const
size_type size () const
size_type capacity () const
void push_back (const_reference value)
void pop_front ()
void push_front (const_reference value)
void pop_back ()
const_pointer back () const
pointer back ()
const_pointer front () const
pointer front ()
const_pointer operator[] (size_type id) const
pointer operator[] (size_type id)
size_type index_of (const_pointer elem) const
const_pointer following (const_pointer elem) const
pointer following (pointer elem)
const_pointer preceding (const_pointer elem) const
pointer preceding (pointer elem)
void reserve (sword_t new_size, void(Type::*mem_fun)(const reserve_functor &)=&Type::realloc)
Private Types
typedef ring_buffer< Type, Allocator > cont_type
Private Attributes
allocator_type alloc_
pointer head_
pointer tail_
pointer begin_
pointer end_
size_type size_
Detailed Description
template<typename Type, typename Allocator = std::allocator<Type>>
class uxn::patl::impl::ring_buffer< Type, Allocator >
Definition at line 19 of file ring_buffer.hpp.
Member Typedef Documentation
allocator_type
template<typename Type , typename Allocator = std::allocator<Type>> typedef Allocator uxn::patl::impl::ring_buffer< Type, Allocator >::allocator_type
Definition at line 29 of file ring_buffer.hpp.
const_pointer
template<typename Type , typename Allocator = std::allocator<Type>> typedef Allocator::const_pointer uxn::patl::impl::ring_buffer< Type, Allocator >::const_pointer
Definition at line 25 of file ring_buffer.hpp.
const_reference
template<typename Type , typename Allocator = std::allocator<Type>> typedef Allocator::const_reference uxn::patl::impl::ring_buffer< Type, Allocator >::const_reference
Definition at line 26 of file ring_buffer.hpp.
cont_type
template<typename Type , typename Allocator = std::allocator<Type>> typedef ring_buffer<Type, Allocator> uxn::patl::impl::ring_buffer< Type, Allocator >::cont_type private
Definition at line 21 of file ring_buffer.hpp.
pointer
template<typename Type , typename Allocator = std::allocator<Type>> typedef Allocator::pointer uxn::patl::impl::ring_buffer< Type, Allocator >::pointer
Definition at line 27 of file ring_buffer.hpp.
reference
template<typename Type , typename Allocator = std::allocator<Type>> typedef Allocator::reference uxn::patl::impl::ring_buffer< Type, Allocator >::reference
Definition at line 28 of file ring_buffer.hpp.
size_type
template<typename Type , typename Allocator = std::allocator<Type>> typedef word_t uxn::patl::impl::ring_buffer< Type, Allocator >::size_type
Definition at line 30 of file ring_buffer.hpp.
value_type
template<typename Type , typename Allocator = std::allocator<Type>> typedef Type uxn::patl::impl::ring_buffer< Type, Allocator >::value_type
Definition at line 24 of file ring_buffer.hpp.
Constructor & Destructor Documentation
ring_buffer()
template<typename Type , typename Allocator = std::allocator<Type>> uxn::patl::impl::ring_buffer< Type, Allocator >::ring_buffer (size_type initSize, const allocator_type & alloc = allocator_type()) inline explicit
Definition at line 32 of file ring_buffer.hpp.
        : alloc_(alloc)
        , size_(0)
    {
        begin_ = end_ = head_ = alloc_.allocate(initSize);
        tail_ = head_ + initSize;
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::alloc_, uxn::patl::impl::ring_buffer< Type, Allocator >::begin_, uxn::patl::impl::ring_buffer< Type, Allocator >::end_, uxn::patl::impl::ring_buffer< Type, Allocator >::head_, and uxn::patl::impl::ring_buffer< Type, Allocator >::tail_.
~ring_buffer()
template<typename Type , typename Allocator = std::allocator<Type>> uxn::patl::impl::ring_buffer< Type, Allocator >::~ring_buffer () inline
Definition at line 42 of file ring_buffer.hpp.
    {
        clear();
        alloc_.deallocate(head_, tail_ - head_);
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::alloc_, uxn::patl::impl::ring_buffer< Type, Allocator >::clear(), uxn::patl::impl::ring_buffer< Type, Allocator >::head_, and uxn::patl::impl::ring_buffer< Type, Allocator >::tail_.
Member Function Documentation
back() [1/2]
template<typename Type , typename Allocator = std::allocator<Type>> pointer uxn::patl::impl::ring_buffer< Type, Allocator >::back () inline
Definition at line 111 of file ring_buffer.hpp.
    {
        return end_ == head_ ? tail_ - 1 : end_ - 1;
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::end_, uxn::patl::impl::ring_buffer< Type, Allocator >::head_, and uxn::patl::impl::ring_buffer< Type, Allocator >::tail_.
back() [2/2]
template<typename Type , typename Allocator = std::allocator<Type>> const_pointer uxn::patl::impl::ring_buffer< Type, Allocator >::back () const inline
Definition at line 107 of file ring_buffer.hpp.
    {
        return end_ == head_ ? tail_ - 1 : end_ - 1;
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::end_, uxn::patl::impl::ring_buffer< Type, Allocator >::head_, and uxn::patl::impl::ring_buffer< Type, Allocator >::tail_.
Referenced by uxn::patl::impl::suffix_generic< T >::match_iterator::operator++(), uxn::patl::impl::suffix_generic< T >::pop_back(), uxn::patl::ngram_stat< Char, Q, N, Delta, BitComp, Allocator >::push_back(), uxn::patl::impl::suffix_generic< T >::push_back_generic(), and uxn::patl::impl::suffix_generic< T >::push_back_root().
capacity()
template<typename Type , typename Allocator = std::allocator<Type>> size_type uxn::patl::impl::ring_buffer< Type, Allocator >::capacity () const inline
Definition at line 69 of file ring_buffer.hpp.
    {
        return tail_ - head_;
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::head_, and uxn::patl::impl::ring_buffer< Type, Allocator >::tail_.
Referenced by uxn::patl::impl::suffix_generic< T >::capacity(), and uxn::patl::ngram_stat< Char, Q, N, Delta, BitComp, Allocator >::capacity().
clear()
template<typename Type , typename Allocator = std::allocator<Type>> void uxn::patl::impl::ring_buffer< Type, Allocator >::clear () inline
Definition at line 48 of file ring_buffer.hpp.
    {
        while (!empty())
            pop_front();
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::empty(), and uxn::patl::impl::ring_buffer< Type, Allocator >::pop_front().
Referenced by uxn::patl::impl::suffix_generic< T >::clear(), uxn::patl::ngram_stat< Char, Q, N, Delta, BitComp, Allocator >::clear(), and uxn::patl::impl::ring_buffer< Type, Allocator >::~ring_buffer().
empty()
template<typename Type , typename Allocator = std::allocator<Type>> bool uxn::patl::impl::ring_buffer< Type, Allocator >::empty () const inline
Definition at line 54 of file ring_buffer.hpp.
    {
        return !size_;
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::size_.
Referenced by uxn::patl::impl::ring_buffer< Type, Allocator >::clear().
endpoint()
template<typename Type , typename Allocator = std::allocator<Type>> bool uxn::patl::impl::ring_buffer< Type, Allocator >::endpoint () const inline
Definition at line 59 of file ring_buffer.hpp.
    {
        return begin_ == end_;
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::begin_, and uxn::patl::impl::ring_buffer< Type, Allocator >::end_.
Referenced by uxn::patl::impl::suffix_generic< T >::endpoint().
following() [1/2]
template<typename Type , typename Allocator = std::allocator<Type>> const_pointer uxn::patl::impl::ring_buffer< Type, Allocator >::following (const_pointer elem) const inline
Definition at line 145 of file ring_buffer.hpp.
    {
        return ++elem == tail_ ? head_ : elem;
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::head_, and uxn::patl::impl::ring_buffer< Type, Allocator >::tail_.
Referenced by uxn::patl::impl::suffix_generic< T >::match_iterator::operator++(), and uxn::patl::impl::suffix_generic< T >::push_back_generic().
following() [2/2]
template<typename Type , typename Allocator = std::allocator<Type>> pointer uxn::patl::impl::ring_buffer< Type, Allocator >::following (pointer elem) inline
Definition at line 149 of file ring_buffer.hpp.
    {
        return ++elem == tail_ ? head_ : elem;
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::head_, and uxn::patl::impl::ring_buffer< Type, Allocator >::tail_.
front() [1/2]
template<typename Type , typename Allocator = std::allocator<Type>> pointer uxn::patl::impl::ring_buffer< Type, Allocator >::front () inline
Definition at line 120 of file ring_buffer.hpp.
    {
        return begin_;
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::begin_.
front() [2/2]
template<typename Type , typename Allocator = std::allocator<Type>> const_pointer uxn::patl::impl::ring_buffer< Type, Allocator >::front () const inline
Definition at line 116 of file ring_buffer.hpp.
    {
        return begin_;
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::begin_.
Referenced by uxn::patl::impl::suffix_generic< T >::pop_front().
index_of()
template<typename Type , typename Allocator = std::allocator<Type>> size_type uxn::patl::impl::ring_buffer< Type, Allocator >::index_of (const_pointer elem) const inline
Definition at line 138 of file ring_buffer.hpp.
    {
        return elem < begin_
            ? (tail_ - begin_) + (elem - head_)
            : elem - begin_;
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::begin_, uxn::patl::impl::ring_buffer< Type, Allocator >::head_, and uxn::patl::impl::ring_buffer< Type, Allocator >::tail_.
Referenced by uxn::patl::impl::suffix_generic< T >::get_key(), uxn::patl::ngram_stat< Char, Q, N, Delta, BitComp, Allocator >::get_key(), uxn::patl::impl::suffix_generic< T >::index_of(), uxn::patl::impl::ring_buffer< Type, Allocator >::reserve_functor::operator()(), uxn::patl::impl::suffix_generic< T >::reserve(), and uxn::patl::impl::suffix_generic< T >::vertex_index_of().
operator[]() [1/2]
template<typename Type , typename Allocator = std::allocator<Type>> pointer uxn::patl::impl::ring_buffer< Type, Allocator >::operator[] (size_type id) inline
Definition at line 131 of file ring_buffer.hpp.
    {
        return begin_ + id < tail_
            ? begin_ + id
            : head_ + id - (tail_ - begin_);
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::begin_, uxn::patl::impl::ring_buffer< Type, Allocator >::head_, and uxn::patl::impl::ring_buffer< Type, Allocator >::tail_.
operator[]() [2/2]
template<typename Type , typename Allocator = std::allocator<Type>> const_pointer uxn::patl::impl::ring_buffer< Type, Allocator >::operator[] (size_type id) const inline
Definition at line 125 of file ring_buffer.hpp.
    {
        return begin_ + id < tail_
            ? begin_ + id
            : head_ + id - (tail_ - begin_);
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::begin_, uxn::patl::impl::ring_buffer< Type, Allocator >::head_, and uxn::patl::impl::ring_buffer< Type, Allocator >::tail_.
pop_back()
template<typename Type , typename Allocator = std::allocator<Type>> void uxn::patl::impl::ring_buffer< Type, Allocator >::pop_back () inline
Definition at line 99 of file ring_buffer.hpp.
    {
        if (end_-- == head_)
            end_ = tail_ - 1;
        alloc_.destroy(end_);
        --size_;
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::alloc_, uxn::patl::impl::ring_buffer< Type, Allocator >::end_, uxn::patl::impl::ring_buffer< Type, Allocator >::head_, uxn::patl::impl::ring_buffer< Type, Allocator >::size_, and uxn::patl::impl::ring_buffer< Type, Allocator >::tail_.
Referenced by uxn::patl::impl::suffix_generic< T >::pop_back().
pop_front()
template<typename Type , typename Allocator = std::allocator<Type>> void uxn::patl::impl::ring_buffer< Type, Allocator >::pop_front () inline
Definition at line 82 of file ring_buffer.hpp.
    {
        alloc_.destroy(begin_);
        --size_;
        if (++begin_ == tail_)
            begin_ = head_;
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::alloc_, uxn::patl::impl::ring_buffer< Type, Allocator >::begin_, uxn::patl::impl::ring_buffer< Type, Allocator >::head_, uxn::patl::impl::ring_buffer< Type, Allocator >::size_, and uxn::patl::impl::ring_buffer< Type, Allocator >::tail_.
Referenced by uxn::patl::impl::ring_buffer< Type, Allocator >::clear(), and uxn::patl::impl::suffix_generic< T >::pop_front().
preceding() [1/2]
template<typename Type , typename Allocator = std::allocator<Type>> const_pointer uxn::patl::impl::ring_buffer< Type, Allocator >::preceding (const_pointer elem) const inline
Definition at line 154 of file ring_buffer.hpp.
    {
        return elem == head_ ? tail_ - 1 : --elem;
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::head_, and uxn::patl::impl::ring_buffer< Type, Allocator >::tail_.
preceding() [2/2]
template<typename Type , typename Allocator = std::allocator<Type>> pointer uxn::patl::impl::ring_buffer< Type, Allocator >::preceding (pointer elem) inline
Definition at line 158 of file ring_buffer.hpp.
    {
        return elem == head_ ? tail_ - 1 : --elem;
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::head_, and uxn::patl::impl::ring_buffer< Type, Allocator >::tail_.
push_back()
template<typename Type , typename Allocator = std::allocator<Type>> void uxn::patl::impl::ring_buffer< Type, Allocator >::push_back (const_reference value) inline
Definition at line 74 of file ring_buffer.hpp.
    {
        alloc_.construct(end_, value);
        ++size_;
        if (++end_ == tail_)
            end_ = head_;
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::alloc_, uxn::patl::impl::ring_buffer< Type, Allocator >::end_, uxn::patl::impl::ring_buffer< Type, Allocator >::head_, uxn::patl::impl::ring_buffer< Type, Allocator >::size_, and uxn::patl::impl::ring_buffer< Type, Allocator >::tail_.
Referenced by uxn::patl::ngram_stat< Char, Q, N, Delta, BitComp, Allocator >::push_back(), uxn::patl::impl::suffix_generic< T >::push_back_generic(), and uxn::patl::impl::suffix_generic< T >::push_back_root().
push_front()
template<typename Type , typename Allocator = std::allocator<Type>> void uxn::patl::impl::ring_buffer< Type, Allocator >::push_front (const_reference value) inline
Definition at line 91 of file ring_buffer.hpp.
    {
        if (begin_-- == head_)
            begin_ = tail_ - 1;
        alloc_.construct(begin_, value);
        ++size_;
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::alloc_, uxn::patl::impl::ring_buffer< Type, Allocator >::begin_, uxn::patl::impl::ring_buffer< Type, Allocator >::head_, uxn::patl::impl::ring_buffer< Type, Allocator >::size_, and uxn::patl::impl::ring_buffer< Type, Allocator >::tail_.
reserve()
template<typename Type , typename Allocator = std::allocator<Type>> void uxn::patl::impl::ring_buffer< Type, Allocator >::reserve (sword_t new_size, void(Type::*)(const reserve_functor &) mem_fun = &Type::realloc) inline
Definition at line 184 of file ring_buffer.hpp.
    {
        //
        if (new_size > tail_ - head_)
        {
            //
            pointer
                new_head = alloc_.allocate(new_size),
                new_end = new_head;
            //
            reserve_functor functor(this, new_head);
            //
            pointer cur = begin_;
            if (size_) do
            {
                //
                (cur->*mem_fun)(functor);
                //
                alloc_.construct(new_end++, *cur);
                //
                alloc_.destroy(cur);
                //
                if (++cur == tail_)
                    cur = head_;
            } while (cur != end_);
            //
            alloc_.deallocate(head_, tail_ - head_);
            //
            begin_ = head_ = new_head;
            tail_ = head_ + new_size;
            end_ = begin_ + size_; // size_
        }
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::alloc_, uxn::patl::impl::ring_buffer< Type, Allocator >::begin_, uxn::patl::impl::ring_buffer< Type, Allocator >::end_, uxn::patl::impl::ring_buffer< Type, Allocator >::head_, uxn::patl::impl::ring_buffer< Type, Allocator >::size_, and uxn::patl::impl::ring_buffer< Type, Allocator >::tail_.
Referenced by uxn::patl::impl::suffix_generic< T >::reserve().
size()
template<typename Type , typename Allocator = std::allocator<Type>> size_type uxn::patl::impl::ring_buffer< Type, Allocator >::size () const inline
Definition at line 64 of file ring_buffer.hpp.
    {
        return size_;
    }
References uxn::patl::impl::ring_buffer< Type, Allocator >::size_.
Referenced by uxn::patl::ngram_stat< Char, Q, N, Delta, BitComp, Allocator >::push_back(), uxn::patl::impl::suffix_generic< T >::push_back_generic(), and uxn::patl::impl::suffix_generic< T >::size().
Member Data Documentation
alloc_
template<typename Type , typename Allocator = std::allocator<Type>> allocator_type uxn::patl::impl::ring_buffer< Type, Allocator >::alloc_ private
Definition at line 224 of file ring_buffer.hpp.
Referenced by uxn::patl::impl::ring_buffer< Type, Allocator >::pop_back(), uxn::patl::impl::ring_buffer< Type, Allocator >::pop_front(), uxn::patl::impl::ring_buffer< Type, Allocator >::push_back(), uxn::patl::impl::ring_buffer< Type, Allocator >::push_front(), uxn::patl::impl::ring_buffer< Type, Allocator >::reserve(), uxn::patl::impl::ring_buffer< Type, Allocator >::ring_buffer(), and uxn::patl::impl::ring_buffer< Type, Allocator >::~ring_buffer().
begin_
template<typename Type , typename Allocator = std::allocator<Type>> pointer uxn::patl::impl::ring_buffer< Type, Allocator >::begin_ private
Definition at line 225 of file ring_buffer.hpp.
Referenced by uxn::patl::impl::ring_buffer< Type, Allocator >::endpoint(), uxn::patl::impl::ring_buffer< Type, Allocator >::front(), uxn::patl::impl::ring_buffer< Type, Allocator >::index_of(), uxn::patl::impl::ring_buffer< Type, Allocator >::operator[](), uxn::patl::impl::ring_buffer< Type, Allocator >::pop_front(), uxn::patl::impl::ring_buffer< Type, Allocator >::push_front(), uxn::patl::impl::ring_buffer< Type, Allocator >::reserve(), and uxn::patl::impl::ring_buffer< Type, Allocator >::ring_buffer().
end_
template<typename Type , typename Allocator = std::allocator<Type>> pointer uxn::patl::impl::ring_buffer< Type, Allocator >::end_ private
Definition at line 225 of file ring_buffer.hpp.
Referenced by uxn::patl::impl::ring_buffer< Type, Allocator >::back(), uxn::patl::impl::ring_buffer< Type, Allocator >::endpoint(), uxn::patl::impl::ring_buffer< Type, Allocator >::pop_back(), uxn::patl::impl::ring_buffer< Type, Allocator >::push_back(), uxn::patl::impl::ring_buffer< Type, Allocator >::reserve(), and uxn::patl::impl::ring_buffer< Type, Allocator >::ring_buffer().
head_
template<typename Type , typename Allocator = std::allocator<Type>> pointer uxn::patl::impl::ring_buffer< Type, Allocator >::head_ private
Definition at line 225 of file ring_buffer.hpp.
Referenced by uxn::patl::impl::ring_buffer< Type, Allocator >::back(), uxn::patl::impl::ring_buffer< Type, Allocator >::capacity(), uxn::patl::impl::ring_buffer< Type, Allocator >::following(), uxn::patl::impl::ring_buffer< Type, Allocator >::index_of(), uxn::patl::impl::ring_buffer< Type, Allocator >::operator[](), uxn::patl::impl::ring_buffer< Type, Allocator >::pop_back(), uxn::patl::impl::ring_buffer< Type, Allocator >::pop_front(), uxn::patl::impl::ring_buffer< Type, Allocator >::preceding(), uxn::patl::impl::ring_buffer< Type, Allocator >::push_back(), uxn::patl::impl::ring_buffer< Type, Allocator >::push_front(), uxn::patl::impl::ring_buffer< Type, Allocator >::reserve(), uxn::patl::impl::ring_buffer< Type, Allocator >::ring_buffer(), and uxn::patl::impl::ring_buffer< Type, Allocator >::~ring_buffer().
size_
template<typename Type , typename Allocator = std::allocator<Type>> size_type uxn::patl::impl::ring_buffer< Type, Allocator >::size_ private
Definition at line 226 of file ring_buffer.hpp.
Referenced by uxn::patl::impl::ring_buffer< Type, Allocator >::empty(), uxn::patl::impl::ring_buffer< Type, Allocator >::pop_back(), uxn::patl::impl::ring_buffer< Type, Allocator >::pop_front(), uxn::patl::impl::ring_buffer< Type, Allocator >::push_back(), uxn::patl::impl::ring_buffer< Type, Allocator >::push_front(), uxn::patl::impl::ring_buffer< Type, Allocator >::reserve(), and uxn::patl::impl::ring_buffer< Type, Allocator >::size().
tail_
template<typename Type , typename Allocator = std::allocator<Type>> pointer uxn::patl::impl::ring_buffer< Type, Allocator >::tail_ private
Definition at line 225 of file ring_buffer.hpp.
Referenced by uxn::patl::impl::ring_buffer< Type, Allocator >::back(), uxn::patl::impl::ring_buffer< Type, Allocator >::capacity(), uxn::patl::impl::ring_buffer< Type, Allocator >::following(), uxn::patl::impl::ring_buffer< Type, Allocator >::index_of(), uxn::patl::impl::ring_buffer< Type, Allocator >::operator[](), uxn::patl::impl::ring_buffer< Type, Allocator >::pop_back(), uxn::patl::impl::ring_buffer< Type, Allocator >::pop_front(), uxn::patl::impl::ring_buffer< Type, Allocator >::preceding(), uxn::patl::impl::ring_buffer< Type, Allocator >::push_back(), uxn::patl::impl::ring_buffer< Type, Allocator >::push_front(), uxn::patl::impl::ring_buffer< Type, Allocator >::reserve(), uxn::patl::impl::ring_buffer< Type, Allocator >::ring_buffer(), and uxn::patl::impl::ring_buffer< Type, Allocator >::~ring_buffer().
The documentation for this class was generated from the following file:
uxn/patl/impl/ring_buffer.hpp